// Auto-generated by generate-ts-package - DO NOT EDIT

import type { SerializableEffect } from './protocol.js';

export type EffectCategory = 'internal' | 'yielded';
export type EffectSemantics = 'fire_and_forget' | 'blocking';

export function getEffectCategory(effect: SerializableEffect): EffectCategory {
  switch (effect.type) {
    case "LogInfo": return "internal";
    case "LogError": return "internal";
    case "LlmComplete": return "internal";
    case "LlmCall": return "internal";
    case "Habitica": return "internal";
    case "TelegramSend": return "yielded";
    case "TelegramAsk": return "yielded";
    case "GetState": return "internal";
    case "SetState": return "internal";
    case "EmitEvent": return "yielded";
    case "RandomInt": return "internal";
    case "GetTime": return "internal";
    default:
      // Exhaustiveness check: unknown effects default to internal
      return 'internal';
  }
}

export function getEffectSemantics(effect: SerializableEffect): EffectSemantics {
  switch (effect.type) {
    case "LogInfo": return "fire_and_forget";
    case "LogError": return "fire_and_forget";
    case "LlmComplete": return "blocking";
    case "LlmCall": return "blocking";
    case "Habitica": return "blocking";
    case "TelegramSend": return "fire_and_forget";
    case "TelegramAsk": return "blocking";
    case "GetState": return "blocking";
    case "SetState": return "fire_and_forget";
    case "EmitEvent": return "fire_and_forget";
    case "RandomInt": return "blocking";
    case "GetTime": return "blocking";
    default:
      // Exhaustiveness check: unknown effects default to blocking
      return 'blocking';
  }
}

export function isYieldedEffect(effect: SerializableEffect): boolean {
  return getEffectCategory(effect) === 'yielded';
}

export function isInternalEffect(effect: SerializableEffect): boolean {
  return getEffectCategory(effect) === 'internal';
}

export function isBlockingEffect(effect: SerializableEffect): boolean {
  return getEffectSemantics(effect) === 'blocking';
}
