#!/usr/bin/env bash
# Extract narrative from baseline run artifacts
#
# Usage:
#   ./scripts/extract-narrative.sh <run-name>
#
# Produces structured narrative from workflow log and generated code.

set -euo pipefail

RUN="${1:-}"
BASELINE_DIR="$HOME/tidepool-labs/dev-runs/baseline"

if [ -z "$RUN" ]; then
  echo "Usage: $0 <run-name>"
  echo ""
  echo "Available runs:"
  ls -1 "$BASELINE_DIR" 2>/dev/null || echo "  (none)"
  exit 1
fi

RUN_DIR="$BASELINE_DIR/$RUN"
ARTIFACTS="$RUN_DIR/artifacts"
LOG="$RUN_DIR/workflow.log"

if [ ! -d "$RUN_DIR" ]; then
  echo "ERROR: Run not found: $RUN_DIR"
  exit 1
fi

echo "# Narrative Extract: $RUN"
echo ""

# Run info
if [ -f "$RUN_DIR/run-info.json" ]; then
  BRANCH=$(jq -r '.branch // "unknown"' "$RUN_DIR/run-info.json")
  STARTED=$(jq -r '.started // "?"' "$RUN_DIR/run-info.json")
  echo "**Branch:** $BRANCH"
  echo "**Started:** $STARTED"
  echo ""
fi

# Automated scores
if [ -f "$RUN_DIR/automated-scores.json" ]; then
  echo "## Automated Scores"
  echo ""
  BUILD=$(jq -r 'if .compiles then "PASS" else "FAIL" end' "$RUN_DIR/automated-scores.json")
  TESTS=$(jq -r 'if .tests_pass then "PASS" else "FAIL" end' "$RUN_DIR/automated-scores.json")
  ENDPOINTS=$(jq -r '.endpoint_count // 0' "$RUN_DIR/automated-scores.json")
  DURATION=$(jq -r '.duration_seconds // 0' "$RUN_DIR/automated-scores.json")
  echo "- Build: $BUILD"
  echo "- Tests: $TESTS"
  echo "- Endpoints: $ENDPOINTS/3"
  echo "- Duration: ${DURATION}s"
  echo ""
fi

# Types/API analysis
echo "## Generated Types"
echo ""
if [ -f "$ARTIFACTS/src/UrlShortener.hs" ]; then
  echo '```haskell'
  # Extract data types
  grep -E "^data |^newtype |^type [A-Z]" "$ARTIFACTS/src/UrlShortener.hs" 2>/dev/null || echo "-- no data types found"
  echo ""
  # Extract API type
  grep -E "type.*API|:<\|>" "$ARTIFACTS/src/UrlShortener.hs" 2>/dev/null | head -10 || echo "-- no API type found"
  echo '```'
else
  echo "_No source file generated_"
fi
echo ""

# Key functions
echo "## Implementation Highlights"
echo ""
if [ -f "$ARTIFACTS/src/UrlShortener.hs" ]; then
  echo '```haskell'
  # Extract function signatures
  grep -E "^[a-z][a-zA-Z]+ ::" "$ARTIFACTS/src/UrlShortener.hs" 2>/dev/null | head -10 || echo "-- no signatures found"
  echo '```'
  echo ""

  # Check for key patterns
  echo "**Patterns detected:**"
  grep -q "IORef" "$ARTIFACTS/src/UrlShortener.hs" && echo "- Uses IORef for state" || true
  grep -q "TVar" "$ARTIFACTS/src/UrlShortener.hs" && echo "- Uses TVar for state" || true
  grep -q "Map" "$ARTIFACTS/src/UrlShortener.hs" && echo "- Uses Map for storage" || true
  grep -q "hash" "$ARTIFACTS/src/UrlShortener.hs" && echo "- Has hash-based short codes" || true
  grep -q "throwError\|throw\|ServerError" "$ARTIFACTS/src/UrlShortener.hs" && echo "- Has error handling" || true
fi
echo ""

# Tests analysis
echo "## Test Strategy"
echo ""
if [ -f "$ARTIFACTS/test/Main.hs" ]; then
  echo '```haskell'
  # Extract test names/descriptions
  grep -E "describe|it |prop |property" "$ARTIFACTS/test/Main.hs" 2>/dev/null | head -15 || echo "-- no test structure found"
  echo '```'
  echo ""

  # Check for test patterns
  echo "**Test patterns:**"
  grep -q "QuickCheck\|Property\|prop_" "$ARTIFACTS/test/Main.hs" && echo "- Property-based tests" || echo "- Unit tests only"
  grep -q "hspec-wai\|with.*app\|request" "$ARTIFACTS/test/Main.hs" && echo "- HTTP integration tests" || true
  ASSERTION_COUNT=$(grep -c "shouldBe\|shouldReturn\|shouldSatisfy\|===\|==>" "$ARTIFACTS/test/Main.hs" 2>/dev/null || echo "0")
  echo "- ~$ASSERTION_COUNT assertions"
else
  echo "_No test file generated_"
fi
echo ""

# Git history
echo "## Commit History"
echo ""
if [ -f "$ARTIFACTS/git-log.txt" ]; then
  echo '```'
  cat "$ARTIFACTS/git-log.txt"
  echo '```'
else
  echo "_No git history captured_"
fi
echo ""

# Workflow phases from log
echo "## Workflow Phases"
echo ""
if [ -f "$LOG" ]; then
  # Extract phase markers
  grep -E "═══.*PHASE|═══.*FORK|═══.*MERGE|agent.*starting|agent.*completed" "$LOG" 2>/dev/null | head -20 || echo "_No phase markers found_"
  echo ""

  # Check for retries
  RETRY_COUNT=$(grep -c "retry\|Retrying\|attempt [2-9]" "$LOG" 2>/dev/null || echo "0")
  if [ "$RETRY_COUNT" -gt 0 ]; then
    echo "**Retries detected:** $RETRY_COUNT"
    echo ""
  fi

  # Check for errors
  ERROR_COUNT=$(grep -ci "error\|failed\|exception" "$LOG" 2>/dev/null || echo "0")
  if [ "$ERROR_COUNT" -gt 0 ]; then
    echo "**Errors/failures in log:** $ERROR_COUNT mentions"
  fi
fi
echo ""

echo "---"
echo "_Generated by extract-narrative.sh_"
