// Auto-generated by generate-ts-package - DO NOT EDIT

export type GraphId = "test" | "example" | "habitica";

export interface GraphEdge {
  from: string;
  to: string;
}

export interface GraphInfo {
  id: GraphId;
  name: string;
  nodes: string[];
  edges: GraphEdge[];
}

export const graphRegistry: Record<GraphId, GraphInfo> = {
  "test": {
    id: "test",
    name: "TestGraph",
    nodes: ["entry", "compute", "exit"],
    edges: [{ from: "entry", to: "compute" }, { from: "compute", to: "exit" }]
  }
,
  "example": {
    id: "example",
    name: "ExampleGraph",
    nodes: ["entry", "classify", "handleGreeting", "handleQuestion", "handleStatement", "exit"],
    edges: [{ from: "entry", to: "classify" }, { from: "classify", to: "handleGreeting" }, { from: "classify", to: "handleQuestion" }, { from: "classify", to: "handleStatement" }, { from: "handleGreeting", to: "exit" }, { from: "handleQuestion", to: "exit" }, { from: "handleStatement", to: "exit" }]
  }
,
  "habitica": {
    id: "habitica",
    name: "HabiticaRoutingGraph",
    nodes: ["entry", "extractTask", "fetchExisting", "matchTask", "suggestAction", "confirmWithUser", "executeAction", "exit"],
    edges: [{ from: "entry", to: "extractTask" }, { from: "extractTask", to: "fetchExisting" }, { from: "fetchExisting", to: "matchTask" }, { from: "matchTask", to: "suggestAction" }, { from: "suggestAction", to: "confirmWithUser" }, { from: "confirmWithUser", to: "executeAction" }, { from: "confirmWithUser", to: "suggestAction" }, { from: "confirmWithUser", to: "exit" }, { from: "executeAction", to: "exit" }]
  }

};
