# Base service fragments for DRY configuration
# Services can extend these to inherit common settings

services:
  # Fragment for services needing Docker socket access
  # - group_add: Adds GID to initial process (works for non-gosu containers)
  # - DOCKER_GID env: Allows entrypoints to add user to group (for gosu containers)
  # DOCKER_GID is detected by ide/refresh-ide scripts before docker compose runs
  docker-socket-access:
    group_add:
      - "${DOCKER_GID:-999}"
    environment:
      - DOCKER_GID=${DOCKER_GID:-999}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
