version: "0.5"

processes:
  control-server:
    command: |
      # Binaries are resolved from EXOMONAD_BIN_DIR (injected by spawner)
      if [ -z "$EXOMONAD_BIN_DIR" ]; then
        echo "ERROR: EXOMONAD_BIN_DIR not set in environment" >&2
        exit 1
      fi
      rm -f .exomonad/sockets/control.sock .exomonad/sockets/tui.sock && \
      "$EXOMONAD_BIN_DIR/exomonad-control-server"
    working_dir: "."
    environment:
      - "HANGAR_ROOT=${HANGAR_ROOT}"
      - "EXOMONAD_BIN_DIR=${EXOMONAD_BIN_DIR}"
      - "EXOMONAD_CONTROL_SOCKET=.exomonad/sockets/control.sock"
      - "EXOMONAD_TUI_SOCKET=.exomonad/sockets/tui.sock"
    readiness_probe:
      exec:
        # Socket existence check (no connection attempt - avoids JSON parse errors)
        command: "test -S .exomonad/sockets/control.sock"
      initial_delay_seconds: 2
      period_seconds: 3
      failure_threshold: 10
    availability:
      restart: on_failure
      max_restarts: 5
    shutdown:
      command: "rm -f .exomonad/sockets/control.sock .exomonad/sockets/tui.sock"
      timeout_seconds: 5

  ssh-proxy:
    command: |
      if [ -z "$EXOMONAD_BIN_DIR" ]; then
        echo "ERROR: EXOMONAD_BIN_DIR not set in environment" >&2
        exit 1
      fi
      "$EXOMONAD_BIN_DIR/ssh-proxy"
    working_dir: "."
    environment:
      - "SSH_PROXY_KEY_PATH=${SSH_PROXY_KEY_PATH:-/etc/ssh-proxy/orchestrator_key}"
      - "SSH_PROXY_PORT=7433"
    readiness_probe:
      http_get:
        host: "127.0.0.1"
        port: 7433
        path: "/health"
      initial_delay_seconds: 1
      period_seconds: 5
    availability:
      restart: on_failure