version: "0.5"

# Global config
log_location: .tidepool/logs/process-compose.log
log_level: info
ordered_shutdown: true  # Shutdown in reverse dependency order (tui-sidebar before control-server)

# Process definitions
processes:
  # 1. Control Server (Haskell)
  # Orchestrates tools, graph execution, and MCP
  control-server:
    command: "dist-newstyle/build/aarch64-osx/ghc-9.12.2/tidepool-control-server-0.1.0.0/x/tidepool-control-server/noopt/build/tidepool-control-server/tidepool-control-server +RTS -N4"
    availability:
      restart: "on_failure"
    readiness_probe:
      # Connect to Unix socket via mantle-agent health command
      exec:
        command: "./scripts/health-check.sh"
      initial_delay_seconds: 2
      period_seconds: 2
      timeout_seconds: 2
      success_threshold: 1
      failure_threshold: 10
    environment:
      - "TIDEPOOL_PROJECT_DIR=."
      - "TIDEPOOL_CONTROL_SOCKET=.tidepool/sockets/control.sock"
      - "TIDEPOOL_TUI_SOCKET=.tidepool/sockets/tui.sock"

  # 2. TUI Sidebar (Rust)
  # Renders interactive UIs for graph handlers
  tui-sidebar:
    command: "rust/target/debug/tui-sidebar --socket .tidepool/sockets/tui.sock --health-socket .tidepool/sockets/tui-sidebar.sock"
    availability:
      restart: "on_failure"
    depends_on:
      control-server:
        condition: process_healthy
    readiness_probe:
      exec:
        command: "nc -zU .tidepool/sockets/tui-sidebar.sock"
      initial_delay_seconds: 2
      period_seconds: 5
      failure_threshold: 5
      timeout_seconds: 1

