version: "0.5"
log_location: .tidepool/logs/process-compose.log

processes:
  control-server:
    # Binaries are on PATH from start-augmented.sh (single source of truth)
    command: |
      rm -f "$TIDEPOOL_CONTROL_SOCKET" "$TIDEPOOL_TUI_SOCKET" && \
      tidepool-control-server
    working_dir: "."
    readiness_probe:
      exec:
        # Socket existence check (no connection attempt - avoids JSON parse errors)
        command: "test -S $TIDEPOOL_CONTROL_SOCKET"
      initial_delay_seconds: 2
      period_seconds: 3
      failure_threshold: 10
    availability:
      restart: on_failure
      max_restarts: 5
    shutdown:
      command: "rm -f $TIDEPOOL_CONTROL_SOCKET $TIDEPOOL_TUI_SOCKET"
      timeout_seconds: 5