# Tidepool Backend Orchestrator
#
# Manages headless services with health probes and auto-restart.
# TTY-dependent processes (Claude Code, tui-sidebar) run in Zellij panes
# and wait for this backend via socket polling.
#
# See .zellij/tidepool.kdl for the frontend layout.

version: "0.5"

log_location: .tidepool/logs/process-compose.log

processes:
  control-server:
    # Pre-cleanup socket to prevent EADDRINUSE, then run server
    command: |
      if [ -z "${HANGAR_ROOT:-}" ]; then echo "HANGAR_ROOT is not set" >&2; exit 1; fi && \
      rm -f .tidepool/sockets/control.sock .tidepool/sockets/tui.sock && \
      $HANGAR_ROOT/bin/exomonad
    working_dir: "."
    availability:
      restart: on_failure
      max_restarts: 5
    readiness_probe:
      exec:
        # Socket existence check (no connection attempt - avoids JSON parse errors)
        command: "test -S .tidepool/sockets/control.sock"
      initial_delay_seconds: 2
      period_seconds: 3
      failure_threshold: 10
    shutdown:
      command: "rm -f .tidepool/sockets/control.sock .tidepool/sockets/tui.sock"
    environment:
      - "TIDEPOOL_PROJECT_DIR=."
      - "TIDEPOOL_CONTROL_SOCKET=.tidepool/sockets/control.sock"
      - "TIDEPOOL_TUI_SOCKET=.tidepool/sockets/tui.sock"
