version: "0.5"

# Global config
log_location: .tidepool/logs/process-compose.log
log_level: info
ordered_shutdown: true  # Shutdown in reverse dependency order (tui-sidebar before control-server)

# Process definitions
processes:
  # 1. Control Server (Haskell)
  # Orchestrates tools, graph execution, and MCP
  control-server:
    command: "dist-newstyle/build/aarch64-osx/ghc-9.12.2/tidepool-control-server-0.1.0.0/x/tidepool-control-server/noopt/build/tidepool-control-server/tidepool-control-server +RTS -N4"
    availability:
      restart: "on_failure"
    readiness_probe:
      # Connect to Unix socket via mantle-agent health command
      exec:
        command: "./scripts/health-check.sh"
      initial_delay_seconds: 2
      period_seconds: 2
      timeout_seconds: 2
      success_threshold: 1
      failure_threshold: 10
    environment:
      - "TIDEPOOL_PROJECT_DIR=."
      - "TIDEPOOL_CONTROL_SOCKET=.tidepool/sockets/control.sock"
      - "TIDEPOOL_TUI_SOCKET=.tidepool/sockets/tui.sock"

  # NOTE: tui-sidebar is NOT managed by process-compose because it requires
  # a TTY for terminal rendering (raw mode, alternate screen). It runs directly
  # in a Zellij pane instead - see .zellij/tidepool.kdl "TUI" pane.

