{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE NegativeLiterals #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeOperators #-}
{-# OPTIONS_GHC -fno-warn-missing-export-lists #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-- | Generated by Haskell protocol buffer compiler. DO NOT EDIT!
module Effects.Agent where
import qualified Prelude as Hs
import qualified Proto3.Suite.Class as HsProtobuf
import qualified Proto3.Suite.DotProto as HsProtobufAST
import qualified Proto3.Suite.JSONPB as HsJSONPB
import Proto3.Suite.JSONPB ( (.=), (.:) )
import qualified Proto3.Suite.Types as HsProtobuf
import qualified Proto3.Wire as HsProtobuf
import qualified Proto3.Wire.Decode as HsProtobuf
    ( Parser, RawField )
import qualified Control.Applicative as Hs
import Control.Applicative ( (<*>), (<|>), (<$>) )
import qualified Control.DeepSeq as Hs
import qualified Control.Monad as Hs
import qualified Data.ByteString as Hs
import qualified Data.Coerce as Hs
import qualified Data.Int as Hs ( Int16, Int32, Int64 )
import qualified Data.List.NonEmpty as Hs ( NonEmpty(..) )
import qualified Data.Map as Hs ( Map, mapKeysMonotonic )
import qualified Data.Proxy as Proxy
import qualified Data.String as Hs ( fromString )
import qualified Data.Text.Lazy as Hs ( Text )
import qualified Data.Vector as Hs ( Vector )
import qualified Data.Word as Hs ( Word16, Word32, Word64 )
import qualified GHC.Enum as Hs
import qualified GHC.Generics as Hs
import qualified Google.Protobuf.Wrappers.Polymorphic as HsProtobuf
    ( Wrapped(..) )
import qualified Unsafe.Coerce as Hs




import qualified ExoMonad.Common
data AgentType
  = AgentTypeAGENT_TYPE_UNSPECIFIED |
    AgentTypeAGENT_TYPE_CLAUDE |
    AgentTypeAGENT_TYPE_GEMINI
  deriving (Hs.Show, Hs.Eq, Hs.Generic, Hs.NFData)
instance (HsProtobuf.Named AgentType) where
  nameOf _ = Hs.fromString "AgentType"
instance (HsProtobuf.HasDefault AgentType)
instance (Hs.Bounded AgentType) where
  minBound = AgentTypeAGENT_TYPE_UNSPECIFIED
  maxBound = AgentTypeAGENT_TYPE_GEMINI
instance (Hs.Ord AgentType) where
  compare x y
    = Hs.compare
        (HsProtobuf.fromProtoEnum x) (HsProtobuf.fromProtoEnum y)
instance (HsProtobuf.ProtoEnum AgentType) where
  toProtoEnumMay 0 = Hs.Just AgentTypeAGENT_TYPE_UNSPECIFIED
  toProtoEnumMay 1 = Hs.Just AgentTypeAGENT_TYPE_CLAUDE
  toProtoEnumMay 2 = Hs.Just AgentTypeAGENT_TYPE_GEMINI
  toProtoEnumMay _ = Hs.Nothing
  fromProtoEnum AgentTypeAGENT_TYPE_UNSPECIFIED = 0
  fromProtoEnum AgentTypeAGENT_TYPE_CLAUDE = 1
  fromProtoEnum AgentTypeAGENT_TYPE_GEMINI = 2
instance (HsJSONPB.ToJSONPB AgentType) where
  toJSONPB x _ = HsJSONPB.enumFieldString x
  toEncodingPB x _ = HsJSONPB.enumFieldEncoding x
instance (HsJSONPB.FromJSONPB AgentType) where
  parseJSONPB (HsJSONPB.String "AGENT_TYPE_UNSPECIFIED")
    = Hs.pure AgentTypeAGENT_TYPE_UNSPECIFIED
  parseJSONPB (HsJSONPB.String "AGENT_TYPE_CLAUDE")
    = Hs.pure AgentTypeAGENT_TYPE_CLAUDE
  parseJSONPB (HsJSONPB.String "AGENT_TYPE_GEMINI")
    = Hs.pure AgentTypeAGENT_TYPE_GEMINI
  parseJSONPB v = HsJSONPB.typeMismatch "AgentType" v
instance (HsJSONPB.ToJSON AgentType) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON AgentType) where
  parseJSON = HsJSONPB.parseJSONPB
instance (HsProtobuf.Finite AgentType)
data AgentStatus
  = AgentStatusAGENT_STATUS_UNSPECIFIED |
    AgentStatusAGENT_STATUS_RUNNING |
    AgentStatusAGENT_STATUS_STOPPED |
    AgentStatusAGENT_STATUS_FAILED |
    AgentStatusAGENT_STATUS_WAITING
  deriving (Hs.Show, Hs.Eq, Hs.Generic, Hs.NFData)
instance (HsProtobuf.Named AgentStatus) where
  nameOf _ = Hs.fromString "AgentStatus"
instance (HsProtobuf.HasDefault AgentStatus)
instance (Hs.Bounded AgentStatus) where
  minBound = AgentStatusAGENT_STATUS_UNSPECIFIED
  maxBound = AgentStatusAGENT_STATUS_WAITING
instance (Hs.Ord AgentStatus) where
  compare x y
    = Hs.compare
        (HsProtobuf.fromProtoEnum x) (HsProtobuf.fromProtoEnum y)
instance (HsProtobuf.ProtoEnum AgentStatus) where
  toProtoEnumMay 0 = Hs.Just AgentStatusAGENT_STATUS_UNSPECIFIED
  toProtoEnumMay 1 = Hs.Just AgentStatusAGENT_STATUS_RUNNING
  toProtoEnumMay 2 = Hs.Just AgentStatusAGENT_STATUS_STOPPED
  toProtoEnumMay 3 = Hs.Just AgentStatusAGENT_STATUS_FAILED
  toProtoEnumMay 4 = Hs.Just AgentStatusAGENT_STATUS_WAITING
  toProtoEnumMay _ = Hs.Nothing
  fromProtoEnum AgentStatusAGENT_STATUS_UNSPECIFIED = 0
  fromProtoEnum AgentStatusAGENT_STATUS_RUNNING = 1
  fromProtoEnum AgentStatusAGENT_STATUS_STOPPED = 2
  fromProtoEnum AgentStatusAGENT_STATUS_FAILED = 3
  fromProtoEnum AgentStatusAGENT_STATUS_WAITING = 4
instance (HsJSONPB.ToJSONPB AgentStatus) where
  toJSONPB x _ = HsJSONPB.enumFieldString x
  toEncodingPB x _ = HsJSONPB.enumFieldEncoding x
instance (HsJSONPB.FromJSONPB AgentStatus) where
  parseJSONPB (HsJSONPB.String "AGENT_STATUS_UNSPECIFIED")
    = Hs.pure AgentStatusAGENT_STATUS_UNSPECIFIED
  parseJSONPB (HsJSONPB.String "AGENT_STATUS_RUNNING")
    = Hs.pure AgentStatusAGENT_STATUS_RUNNING
  parseJSONPB (HsJSONPB.String "AGENT_STATUS_STOPPED")
    = Hs.pure AgentStatusAGENT_STATUS_STOPPED
  parseJSONPB (HsJSONPB.String "AGENT_STATUS_FAILED")
    = Hs.pure AgentStatusAGENT_STATUS_FAILED
  parseJSONPB (HsJSONPB.String "AGENT_STATUS_WAITING")
    = Hs.pure AgentStatusAGENT_STATUS_WAITING
  parseJSONPB v = HsJSONPB.typeMismatch "AgentStatus" v
instance (HsJSONPB.ToJSON AgentStatus) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON AgentStatus) where
  parseJSON = HsJSONPB.parseJSONPB
instance (HsProtobuf.Finite AgentStatus)
data WorkspaceTopology
  = WorkspaceTopologyWORKSPACE_TOPOLOGY_UNSPECIFIED |
    WorkspaceTopologyWORKSPACE_TOPOLOGY_WORKTREE_PER_AGENT |
    WorkspaceTopologyWORKSPACE_TOPOLOGY_SHARED_DIR
  deriving (Hs.Show, Hs.Eq, Hs.Generic, Hs.NFData)
instance (HsProtobuf.Named WorkspaceTopology) where
  nameOf _ = Hs.fromString "WorkspaceTopology"
instance (HsProtobuf.HasDefault WorkspaceTopology)
instance (Hs.Bounded WorkspaceTopology) where
  minBound = WorkspaceTopologyWORKSPACE_TOPOLOGY_UNSPECIFIED
  maxBound = WorkspaceTopologyWORKSPACE_TOPOLOGY_SHARED_DIR
instance (Hs.Ord WorkspaceTopology) where
  compare x y
    = Hs.compare
        (HsProtobuf.fromProtoEnum x) (HsProtobuf.fromProtoEnum y)
instance (HsProtobuf.ProtoEnum WorkspaceTopology) where
  toProtoEnumMay 0
    = Hs.Just WorkspaceTopologyWORKSPACE_TOPOLOGY_UNSPECIFIED
  toProtoEnumMay 1
    = Hs.Just WorkspaceTopologyWORKSPACE_TOPOLOGY_WORKTREE_PER_AGENT
  toProtoEnumMay 2
    = Hs.Just WorkspaceTopologyWORKSPACE_TOPOLOGY_SHARED_DIR
  toProtoEnumMay _ = Hs.Nothing
  fromProtoEnum WorkspaceTopologyWORKSPACE_TOPOLOGY_UNSPECIFIED = 0
  fromProtoEnum
    WorkspaceTopologyWORKSPACE_TOPOLOGY_WORKTREE_PER_AGENT
    = 1
  fromProtoEnum WorkspaceTopologyWORKSPACE_TOPOLOGY_SHARED_DIR = 2
instance (HsJSONPB.ToJSONPB WorkspaceTopology) where
  toJSONPB x _ = HsJSONPB.enumFieldString x
  toEncodingPB x _ = HsJSONPB.enumFieldEncoding x
instance (HsJSONPB.FromJSONPB WorkspaceTopology) where
  parseJSONPB (HsJSONPB.String "WORKSPACE_TOPOLOGY_UNSPECIFIED")
    = Hs.pure WorkspaceTopologyWORKSPACE_TOPOLOGY_UNSPECIFIED
  parseJSONPB
    (HsJSONPB.String "WORKSPACE_TOPOLOGY_WORKTREE_PER_AGENT")
    = Hs.pure WorkspaceTopologyWORKSPACE_TOPOLOGY_WORKTREE_PER_AGENT
  parseJSONPB (HsJSONPB.String "WORKSPACE_TOPOLOGY_SHARED_DIR")
    = Hs.pure WorkspaceTopologyWORKSPACE_TOPOLOGY_SHARED_DIR
  parseJSONPB v = HsJSONPB.typeMismatch "WorkspaceTopology" v
instance (HsJSONPB.ToJSON WorkspaceTopology) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON WorkspaceTopology) where
  parseJSON = HsJSONPB.parseJSONPB
instance (HsProtobuf.Finite WorkspaceTopology)
data AgentInfo
  = AgentInfo {agentInfoId :: Hs.Text,
               agentInfoIssue :: Hs.Text,
               agentInfoWorktreePath :: Hs.Text,
               agentInfoBranchName :: Hs.Text,
               agentInfoAgentType :: (HsProtobuf.Enumerated Effects.Agent.AgentType),
               agentInfoRole :: (HsProtobuf.Enumerated ExoMonad.Common.Role),
               agentInfoStatus :: (HsProtobuf.Enumerated Effects.Agent.AgentStatus),
               agentInfoZellijTab :: Hs.Text,
               agentInfoError :: Hs.Text,
               agentInfoPrNumber :: Hs.Int32,
               agentInfoPrUrl :: Hs.Text,
               agentInfoTopology :: (HsProtobuf.Enumerated Effects.Agent.WorkspaceTopology)}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData AgentInfo)
instance (HsProtobuf.Named AgentInfo) where
  nameOf _ = Hs.fromString "AgentInfo"
instance (HsProtobuf.HasDefault AgentInfo)
instance (HsProtobuf.Message AgentInfo) where
  encodeMessage
    _
    AgentInfo {agentInfoId, agentInfoIssue, agentInfoWorktreePath,
               agentInfoBranchName, agentInfoAgentType, agentInfoRole,
               agentInfoStatus, agentInfoZellijTab, agentInfoError,
               agentInfoPrNumber, agentInfoPrUrl, agentInfoTopology}
    = Hs.mappend
        (Hs.mappend
           (Hs.mappend
              (Hs.mappend
                 (Hs.mappend
                    (Hs.mappend
                       (Hs.mappend
                          (Hs.mappend
                             (Hs.mappend
                                (Hs.mappend
                                   (Hs.mappend
                                      (HsProtobuf.encodeMessageField
                                         (HsProtobuf.FieldNumber 1)
                                         ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                                            agentInfoId))
                                      (HsProtobuf.encodeMessageField
                                         (HsProtobuf.FieldNumber 2)
                                         ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                                            agentInfoIssue)))
                                   (HsProtobuf.encodeMessageField
                                      (HsProtobuf.FieldNumber 3)
                                      ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                                         agentInfoWorktreePath)))
                                (HsProtobuf.encodeMessageField
                                   (HsProtobuf.FieldNumber 4)
                                   ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                                      agentInfoBranchName)))
                             (HsProtobuf.encodeMessageField
                                (HsProtobuf.FieldNumber 5) agentInfoAgentType))
                          (HsProtobuf.encodeMessageField
                             (HsProtobuf.FieldNumber 6) agentInfoRole))
                       (HsProtobuf.encodeMessageField
                          (HsProtobuf.FieldNumber 7) agentInfoStatus))
                    (HsProtobuf.encodeMessageField
                       (HsProtobuf.FieldNumber 8)
                       ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                          agentInfoZellijTab)))
                 (HsProtobuf.encodeMessageField
                    (HsProtobuf.FieldNumber 9)
                    ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                       agentInfoError)))
              (HsProtobuf.encodeMessageField
                 (HsProtobuf.FieldNumber 10) agentInfoPrNumber))
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 11)
              ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                 agentInfoPrUrl)))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 12) agentInfoTopology)
  decodeMessage _
    = Hs.pure AgentInfo
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 3)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 4)))
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 5)
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 6)
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 7)
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 8)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 9)))
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 10)
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 11)))
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 12)
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "id") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "issue") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 3)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "worktree_path") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 4)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "branch_name") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 5)
         (HsProtobufAST.Prim
            (HsProtobufAST.Named (HsProtobufAST.Single "AgentType")))
         (HsProtobufAST.Single "agent_type") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 6)
         (HsProtobufAST.Prim
            (HsProtobufAST.Named
               (HsProtobufAST.Dots
                  (HsProtobufAST.Path ("exomonad" Hs.:| ["common", "Role"])))))
         (HsProtobufAST.Single "role") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 7)
         (HsProtobufAST.Prim
            (HsProtobufAST.Named (HsProtobufAST.Single "AgentStatus")))
         (HsProtobufAST.Single "status") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 8)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "zellij_tab") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 9)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "error") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 10)
         (HsProtobufAST.Prim HsProtobufAST.Int32)
         (HsProtobufAST.Single "pr_number") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 11)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "pr_url") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 12)
         (HsProtobufAST.Prim
            (HsProtobufAST.Named (HsProtobufAST.Single "WorkspaceTopology")))
         (HsProtobufAST.Single "topology") [] ""]
instance (HsJSONPB.ToJSONPB AgentInfo) where
  toJSONPB (AgentInfo f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12)
    = HsJSONPB.object
        ["id" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "issue" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
         "worktree_path"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3),
         "branch_name"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f4),
         "agent_type" .= f5, "role" .= f6, "status" .= f7,
         "zellij_tab"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f8),
         "error" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f9),
         "pr_number" .= f10,
         "pr_url"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f11),
         "topology" .= f12]
  toEncodingPB (AgentInfo f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12)
    = HsJSONPB.pairs
        ["id" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "issue" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
         "worktree_path"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3),
         "branch_name"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f4),
         "agent_type" .= f5, "role" .= f6, "status" .= f7,
         "zellij_tab"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f8),
         "error" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f9),
         "pr_number" .= f10,
         "pr_url"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f11),
         "topology" .= f12]
instance (HsJSONPB.FromJSONPB AgentInfo) where
  parseJSONPB
    = HsJSONPB.withObject
        "AgentInfo"
        (\ obj
           -> Hs.pure AgentInfo
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "id"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "issue"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "worktree_path"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "branch_name"))
                <*> obj .: "agent_type"
                <*> obj .: "role"
                <*> obj .: "status"
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "zellij_tab"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "error"))
                <*> obj .: "pr_number"
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "pr_url"))
                <*> obj .: "topology")
instance (HsJSONPB.ToJSON AgentInfo) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON AgentInfo) where
  parseJSON = HsJSONPB.parseJSONPB
data SpawnRequest
  = SpawnRequest {spawnRequestIssue :: Hs.Text,
                  spawnRequestOwner :: Hs.Text,
                  spawnRequestRepo :: Hs.Text,
                  spawnRequestAgentType :: (HsProtobuf.Enumerated Effects.Agent.AgentType),
                  spawnRequestRole :: (HsProtobuf.Enumerated ExoMonad.Common.Role),
                  spawnRequestWorktreeDir :: Hs.Text,
                  spawnRequestSubrepo :: Hs.Text,
                  spawnRequestTopology :: (HsProtobuf.Enumerated Effects.Agent.WorkspaceTopology),
                  spawnRequestBaseBranch :: Hs.Text,
                  spawnRequestContext :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData SpawnRequest)
instance (HsProtobuf.Named SpawnRequest) where
  nameOf _ = Hs.fromString "SpawnRequest"
instance (HsProtobuf.HasDefault SpawnRequest)
instance (HsProtobuf.Message SpawnRequest) where
  encodeMessage
    _
    SpawnRequest {spawnRequestIssue, spawnRequestOwner,
                  spawnRequestRepo, spawnRequestAgentType, spawnRequestRole,
                  spawnRequestWorktreeDir, spawnRequestSubrepo, spawnRequestTopology,
                  spawnRequestBaseBranch, spawnRequestContext}
    = Hs.mappend
        (Hs.mappend
           (Hs.mappend
              (Hs.mappend
                 (Hs.mappend
                    (Hs.mappend
                       (Hs.mappend
                          (Hs.mappend
                             (Hs.mappend
                                (HsProtobuf.encodeMessageField
                                   (HsProtobuf.FieldNumber 1)
                                   ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                                      spawnRequestIssue))
                                (HsProtobuf.encodeMessageField
                                   (HsProtobuf.FieldNumber 2)
                                   ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                                      spawnRequestOwner)))
                             (HsProtobuf.encodeMessageField
                                (HsProtobuf.FieldNumber 3)
                                ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                                   spawnRequestRepo)))
                          (HsProtobuf.encodeMessageField
                             (HsProtobuf.FieldNumber 4) spawnRequestAgentType))
                       (HsProtobuf.encodeMessageField
                          (HsProtobuf.FieldNumber 5) spawnRequestRole))
                    (HsProtobuf.encodeMessageField
                       (HsProtobuf.FieldNumber 6)
                       ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                          spawnRequestWorktreeDir)))
                 (HsProtobuf.encodeMessageField
                    (HsProtobuf.FieldNumber 7)
                    ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                       spawnRequestSubrepo)))
              (HsProtobuf.encodeMessageField
                 (HsProtobuf.FieldNumber 8) spawnRequestTopology))
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 9)
              ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                 spawnRequestBaseBranch)))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 10)
           ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              spawnRequestContext))
  decodeMessage _
    = Hs.pure SpawnRequest
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 3)))
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 4)
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 5)
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 6)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 7)))
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 8)
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 9)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 10)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "issue") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "owner") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 3)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "repo") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 4)
         (HsProtobufAST.Prim
            (HsProtobufAST.Named (HsProtobufAST.Single "AgentType")))
         (HsProtobufAST.Single "agent_type") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 5)
         (HsProtobufAST.Prim
            (HsProtobufAST.Named
               (HsProtobufAST.Dots
                  (HsProtobufAST.Path ("exomonad" Hs.:| ["common", "Role"])))))
         (HsProtobufAST.Single "role") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 6)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "worktree_dir") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 7)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "subrepo") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 8)
         (HsProtobufAST.Prim
            (HsProtobufAST.Named (HsProtobufAST.Single "WorkspaceTopology")))
         (HsProtobufAST.Single "topology") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 9)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "base_branch") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 10)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "context") [] ""]
instance (HsJSONPB.ToJSONPB SpawnRequest) where
  toJSONPB (SpawnRequest f1 f2 f3 f4 f5 f6 f7 f8 f9 f10)
    = HsJSONPB.object
        ["issue" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "owner" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
         "repo" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3),
         "agent_type" .= f4, "role" .= f5,
         "worktree_dir"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f6),
         "subrepo"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f7),
         "topology" .= f8,
         "base_branch"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f9),
         "context"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f10)]
  toEncodingPB (SpawnRequest f1 f2 f3 f4 f5 f6 f7 f8 f9 f10)
    = HsJSONPB.pairs
        ["issue" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "owner" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
         "repo" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3),
         "agent_type" .= f4, "role" .= f5,
         "worktree_dir"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f6),
         "subrepo"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f7),
         "topology" .= f8,
         "base_branch"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f9),
         "context"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f10)]
instance (HsJSONPB.FromJSONPB SpawnRequest) where
  parseJSONPB
    = HsJSONPB.withObject
        "SpawnRequest"
        (\ obj
           -> Hs.pure SpawnRequest
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "issue"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "owner"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "repo"))
                <*> obj .: "agent_type"
                <*> obj .: "role"
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "worktree_dir"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "subrepo"))
                <*> obj .: "topology"
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "base_branch"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "context")))
instance (HsJSONPB.ToJSON SpawnRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON SpawnRequest) where
  parseJSON = HsJSONPB.parseJSONPB
newtype SpawnResponse
  = SpawnResponse {spawnResponseAgent :: (Hs.Maybe Effects.Agent.AgentInfo)}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData SpawnResponse)
instance (HsProtobuf.Named SpawnResponse) where
  nameOf _ = Hs.fromString "SpawnResponse"
instance (HsProtobuf.HasDefault SpawnResponse)
instance (HsProtobuf.Message SpawnResponse) where
  encodeMessage _ SpawnResponse {spawnResponseAgent}
    = (HsProtobuf.encodeMessageField
         (HsProtobuf.FieldNumber 1)
         ((Hs.coerce
             @(Hs.Maybe Effects.Agent.AgentInfo)
             @(HsProtobuf.Nested Effects.Agent.AgentInfo))
            spawnResponseAgent))
  decodeMessage _
    = Hs.pure SpawnResponse
        <*>
          ((HsProtobuf.coerceOver
              @(HsProtobuf.Nested Effects.Agent.AgentInfo)
              @(Hs.Maybe Effects.Agent.AgentInfo))
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim
            (HsProtobufAST.Named (HsProtobufAST.Single "AgentInfo")))
         (HsProtobufAST.Single "agent") [] ""]
instance (HsJSONPB.ToJSONPB SpawnResponse) where
  toJSONPB (SpawnResponse f1)
    = HsJSONPB.object
        ["agent"
           .=
             ((Hs.coerce
                 @(Hs.Maybe Effects.Agent.AgentInfo)
                 @(HsProtobuf.Nested Effects.Agent.AgentInfo))
                f1)]
  toEncodingPB (SpawnResponse f1)
    = HsJSONPB.pairs
        ["agent"
           .=
             ((Hs.coerce
                 @(Hs.Maybe Effects.Agent.AgentInfo)
                 @(HsProtobuf.Nested Effects.Agent.AgentInfo))
                f1)]
instance (HsJSONPB.FromJSONPB SpawnResponse) where
  parseJSONPB
    = HsJSONPB.withObject
        "SpawnResponse"
        (\ obj
           -> Hs.pure SpawnResponse
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.Nested Effects.Agent.AgentInfo)
                      @(Hs.Maybe Effects.Agent.AgentInfo))
                     (obj .: "agent")))
instance (HsJSONPB.ToJSON SpawnResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON SpawnResponse) where
  parseJSON = HsJSONPB.parseJSONPB
data SpawnBatchRequest
  = SpawnBatchRequest {spawnBatchRequestIssues :: (Hs.Vector Hs.Text),
                       spawnBatchRequestOwner :: Hs.Text,
                       spawnBatchRequestRepo :: Hs.Text,
                       spawnBatchRequestAgentType :: (HsProtobuf.Enumerated Effects.Agent.AgentType),
                       spawnBatchRequestRole :: (HsProtobuf.Enumerated ExoMonad.Common.Role),
                       spawnBatchRequestWorktreeDir :: Hs.Text,
                       spawnBatchRequestSubrepo :: Hs.Text,
                       spawnBatchRequestTopology :: (HsProtobuf.Enumerated Effects.Agent.WorkspaceTopology)}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData SpawnBatchRequest)
instance (HsProtobuf.Named SpawnBatchRequest) where
  nameOf _ = Hs.fromString "SpawnBatchRequest"
instance (HsProtobuf.HasDefault SpawnBatchRequest)
instance (HsProtobuf.Message SpawnBatchRequest) where
  encodeMessage
    _
    SpawnBatchRequest {spawnBatchRequestIssues, spawnBatchRequestOwner,
                       spawnBatchRequestRepo, spawnBatchRequestAgentType,
                       spawnBatchRequestRole, spawnBatchRequestWorktreeDir,
                       spawnBatchRequestSubrepo, spawnBatchRequestTopology}
    = Hs.mappend
        (Hs.mappend
           (Hs.mappend
              (Hs.mappend
                 (Hs.mappend
                    (Hs.mappend
                       (Hs.mappend
                          (HsProtobuf.encodeMessageField
                             (HsProtobuf.FieldNumber 1)
                             ((Hs.coerce
                                 @(Hs.Vector Hs.Text)
                                 @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
                                spawnBatchRequestIssues))
                          (HsProtobuf.encodeMessageField
                             (HsProtobuf.FieldNumber 2)
                             ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                                spawnBatchRequestOwner)))
                       (HsProtobuf.encodeMessageField
                          (HsProtobuf.FieldNumber 3)
                          ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                             spawnBatchRequestRepo)))
                    (HsProtobuf.encodeMessageField
                       (HsProtobuf.FieldNumber 4) spawnBatchRequestAgentType))
                 (HsProtobuf.encodeMessageField
                    (HsProtobuf.FieldNumber 5) spawnBatchRequestRole))
              (HsProtobuf.encodeMessageField
                 (HsProtobuf.FieldNumber 6)
                 ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                    spawnBatchRequestWorktreeDir)))
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 7)
              ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                 spawnBatchRequestSubrepo)))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 8) spawnBatchRequestTopology)
  decodeMessage _
    = Hs.pure SpawnBatchRequest
        <*>
          ((HsProtobuf.coerceOver
              @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
              @(Hs.Vector Hs.Text))
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 3)))
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 4)
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 5)
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 6)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 7)))
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 8)
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Repeated HsProtobufAST.String)
         (HsProtobufAST.Single "issues") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "owner") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 3)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "repo") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 4)
         (HsProtobufAST.Prim
            (HsProtobufAST.Named (HsProtobufAST.Single "AgentType")))
         (HsProtobufAST.Single "agent_type") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 5)
         (HsProtobufAST.Prim
            (HsProtobufAST.Named
               (HsProtobufAST.Dots
                  (HsProtobufAST.Path ("exomonad" Hs.:| ["common", "Role"])))))
         (HsProtobufAST.Single "role") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 6)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "worktree_dir") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 7)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "subrepo") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 8)
         (HsProtobufAST.Prim
            (HsProtobufAST.Named (HsProtobufAST.Single "WorkspaceTopology")))
         (HsProtobufAST.Single "topology") [] ""]
instance (HsJSONPB.ToJSONPB SpawnBatchRequest) where
  toJSONPB (SpawnBatchRequest f1 f2 f3 f4 f5 f6 f7 f8)
    = HsJSONPB.object
        ["issues"
           .=
             ((Hs.coerce
                 @(Hs.Vector Hs.Text)
                 @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
                f1),
         "owner" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
         "repo" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3),
         "agent_type" .= f4, "role" .= f5,
         "worktree_dir"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f6),
         "subrepo"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f7),
         "topology" .= f8]
  toEncodingPB (SpawnBatchRequest f1 f2 f3 f4 f5 f6 f7 f8)
    = HsJSONPB.pairs
        ["issues"
           .=
             ((Hs.coerce
                 @(Hs.Vector Hs.Text)
                 @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
                f1),
         "owner" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
         "repo" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3),
         "agent_type" .= f4, "role" .= f5,
         "worktree_dir"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f6),
         "subrepo"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f7),
         "topology" .= f8]
instance (HsJSONPB.FromJSONPB SpawnBatchRequest) where
  parseJSONPB
    = HsJSONPB.withObject
        "SpawnBatchRequest"
        (\ obj
           -> Hs.pure SpawnBatchRequest
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
                      @(Hs.Vector Hs.Text))
                     (obj .: "issues"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "owner"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "repo"))
                <*> obj .: "agent_type"
                <*> obj .: "role"
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "worktree_dir"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "subrepo"))
                <*> obj .: "topology")
instance (HsJSONPB.ToJSON SpawnBatchRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON SpawnBatchRequest) where
  parseJSON = HsJSONPB.parseJSONPB
data SpawnBatchResponse
  = SpawnBatchResponse {spawnBatchResponseAgents :: (Hs.Vector Effects.Agent.AgentInfo),
                        spawnBatchResponseErrors :: (Hs.Vector Hs.Text)}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData SpawnBatchResponse)
instance (HsProtobuf.Named SpawnBatchResponse) where
  nameOf _ = Hs.fromString "SpawnBatchResponse"
instance (HsProtobuf.HasDefault SpawnBatchResponse)
instance (HsProtobuf.Message SpawnBatchResponse) where
  encodeMessage
    _
    SpawnBatchResponse {spawnBatchResponseAgents,
                        spawnBatchResponseErrors}
    = Hs.mappend
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 1)
           ((Hs.coerce
               @(Hs.Vector Effects.Agent.AgentInfo)
               @(HsProtobuf.NestedVec Effects.Agent.AgentInfo))
              spawnBatchResponseAgents))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 2)
           ((Hs.coerce
               @(Hs.Vector Hs.Text)
               @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
              spawnBatchResponseErrors))
  decodeMessage _
    = Hs.pure SpawnBatchResponse
        <*>
          ((HsProtobuf.coerceOver
              @(HsProtobuf.NestedVec Effects.Agent.AgentInfo)
              @(Hs.Vector Effects.Agent.AgentInfo))
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          ((HsProtobuf.coerceOver
              @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
              @(Hs.Vector Hs.Text))
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Repeated
            (HsProtobufAST.Named (HsProtobufAST.Single "AgentInfo")))
         (HsProtobufAST.Single "agents") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2)
         (HsProtobufAST.Repeated HsProtobufAST.String)
         (HsProtobufAST.Single "errors") [] ""]
instance (HsJSONPB.ToJSONPB SpawnBatchResponse) where
  toJSONPB (SpawnBatchResponse f1 f2)
    = HsJSONPB.object
        ["agents"
           .=
             ((Hs.coerce
                 @(Hs.Vector Effects.Agent.AgentInfo)
                 @(HsProtobuf.NestedVec Effects.Agent.AgentInfo))
                f1),
         "errors"
           .=
             ((Hs.coerce
                 @(Hs.Vector Hs.Text)
                 @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
                f2)]
  toEncodingPB (SpawnBatchResponse f1 f2)
    = HsJSONPB.pairs
        ["agents"
           .=
             ((Hs.coerce
                 @(Hs.Vector Effects.Agent.AgentInfo)
                 @(HsProtobuf.NestedVec Effects.Agent.AgentInfo))
                f1),
         "errors"
           .=
             ((Hs.coerce
                 @(Hs.Vector Hs.Text)
                 @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
                f2)]
instance (HsJSONPB.FromJSONPB SpawnBatchResponse) where
  parseJSONPB
    = HsJSONPB.withObject
        "SpawnBatchResponse"
        (\ obj
           -> Hs.pure SpawnBatchResponse
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.NestedVec Effects.Agent.AgentInfo)
                      @(Hs.Vector Effects.Agent.AgentInfo))
                     (obj .: "agents"))
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
                      @(Hs.Vector Hs.Text))
                     (obj .: "errors")))
instance (HsJSONPB.ToJSON SpawnBatchResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON SpawnBatchResponse) where
  parseJSON = HsJSONPB.parseJSONPB
data SpawnGeminiTeammateRequest
  = SpawnGeminiTeammateRequest {spawnGeminiTeammateRequestName :: Hs.Text,
                                spawnGeminiTeammateRequestPrompt :: Hs.Text,
                                spawnGeminiTeammateRequestAgentType :: (HsProtobuf.Enumerated Effects.Agent.AgentType),
                                spawnGeminiTeammateRequestSubrepo :: Hs.Text,
                                spawnGeminiTeammateRequestTopology :: (HsProtobuf.Enumerated Effects.Agent.WorkspaceTopology),
                                spawnGeminiTeammateRequestBaseBranch :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData SpawnGeminiTeammateRequest)
instance (HsProtobuf.Named SpawnGeminiTeammateRequest) where
  nameOf _ = Hs.fromString "SpawnGeminiTeammateRequest"
instance (HsProtobuf.HasDefault SpawnGeminiTeammateRequest)
instance (HsProtobuf.Message SpawnGeminiTeammateRequest) where
  encodeMessage
    _
    SpawnGeminiTeammateRequest {spawnGeminiTeammateRequestName,
                                spawnGeminiTeammateRequestPrompt,
                                spawnGeminiTeammateRequestAgentType,
                                spawnGeminiTeammateRequestSubrepo,
                                spawnGeminiTeammateRequestTopology,
                                spawnGeminiTeammateRequestBaseBranch}
    = Hs.mappend
        (Hs.mappend
           (Hs.mappend
              (Hs.mappend
                 (Hs.mappend
                    (HsProtobuf.encodeMessageField
                       (HsProtobuf.FieldNumber 1)
                       ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                          spawnGeminiTeammateRequestName))
                    (HsProtobuf.encodeMessageField
                       (HsProtobuf.FieldNumber 2)
                       ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                          spawnGeminiTeammateRequestPrompt)))
                 (HsProtobuf.encodeMessageField
                    (HsProtobuf.FieldNumber 3) spawnGeminiTeammateRequestAgentType))
              (HsProtobuf.encodeMessageField
                 (HsProtobuf.FieldNumber 4)
                 ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                    spawnGeminiTeammateRequestSubrepo)))
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 6) spawnGeminiTeammateRequestTopology))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 7)
           ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              spawnGeminiTeammateRequestBaseBranch))
  decodeMessage _
    = Hs.pure SpawnGeminiTeammateRequest
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)))
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 3)
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 4)))
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 6)
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 7)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "name") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "prompt") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 3)
         (HsProtobufAST.Prim
            (HsProtobufAST.Named (HsProtobufAST.Single "AgentType")))
         (HsProtobufAST.Single "agent_type") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 4)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "subrepo") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 6)
         (HsProtobufAST.Prim
            (HsProtobufAST.Named (HsProtobufAST.Single "WorkspaceTopology")))
         (HsProtobufAST.Single "topology") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 7)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "base_branch") [] ""]
instance (HsJSONPB.ToJSONPB SpawnGeminiTeammateRequest) where
  toJSONPB (SpawnGeminiTeammateRequest f1 f2 f3 f4 f6 f7)
    = HsJSONPB.object
        ["name" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "prompt" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
         "agent_type" .= f3,
         "subrepo"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f4),
         "topology" .= f6,
         "base_branch"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f7)]
  toEncodingPB (SpawnGeminiTeammateRequest f1 f2 f3 f4 f6 f7)
    = HsJSONPB.pairs
        ["name" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "prompt" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
         "agent_type" .= f3,
         "subrepo"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f4),
         "topology" .= f6,
         "base_branch"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f7)]
instance (HsJSONPB.FromJSONPB SpawnGeminiTeammateRequest) where
  parseJSONPB
    = HsJSONPB.withObject
        "SpawnGeminiTeammateRequest"
        (\ obj
           -> Hs.pure SpawnGeminiTeammateRequest
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "name"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "prompt"))
                <*> obj .: "agent_type"
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "subrepo"))
                <*> obj .: "topology"
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "base_branch")))
instance (HsJSONPB.ToJSON SpawnGeminiTeammateRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON SpawnGeminiTeammateRequest) where
  parseJSON = HsJSONPB.parseJSONPB
newtype SpawnGeminiTeammateResponse
  = SpawnGeminiTeammateResponse {spawnGeminiTeammateResponseAgent :: (Hs.Maybe Effects.Agent.AgentInfo)}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData SpawnGeminiTeammateResponse)
instance (HsProtobuf.Named SpawnGeminiTeammateResponse) where
  nameOf _ = Hs.fromString "SpawnGeminiTeammateResponse"
instance (HsProtobuf.HasDefault SpawnGeminiTeammateResponse)
instance (HsProtobuf.Message SpawnGeminiTeammateResponse) where
  encodeMessage
    _
    SpawnGeminiTeammateResponse {spawnGeminiTeammateResponseAgent}
    = (HsProtobuf.encodeMessageField
         (HsProtobuf.FieldNumber 1)
         ((Hs.coerce
             @(Hs.Maybe Effects.Agent.AgentInfo)
             @(HsProtobuf.Nested Effects.Agent.AgentInfo))
            spawnGeminiTeammateResponseAgent))
  decodeMessage _
    = Hs.pure SpawnGeminiTeammateResponse
        <*>
          ((HsProtobuf.coerceOver
              @(HsProtobuf.Nested Effects.Agent.AgentInfo)
              @(Hs.Maybe Effects.Agent.AgentInfo))
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim
            (HsProtobufAST.Named (HsProtobufAST.Single "AgentInfo")))
         (HsProtobufAST.Single "agent") [] ""]
instance (HsJSONPB.ToJSONPB SpawnGeminiTeammateResponse) where
  toJSONPB (SpawnGeminiTeammateResponse f1)
    = HsJSONPB.object
        ["agent"
           .=
             ((Hs.coerce
                 @(Hs.Maybe Effects.Agent.AgentInfo)
                 @(HsProtobuf.Nested Effects.Agent.AgentInfo))
                f1)]
  toEncodingPB (SpawnGeminiTeammateResponse f1)
    = HsJSONPB.pairs
        ["agent"
           .=
             ((Hs.coerce
                 @(Hs.Maybe Effects.Agent.AgentInfo)
                 @(HsProtobuf.Nested Effects.Agent.AgentInfo))
                f1)]
instance (HsJSONPB.FromJSONPB SpawnGeminiTeammateResponse) where
  parseJSONPB
    = HsJSONPB.withObject
        "SpawnGeminiTeammateResponse"
        (\ obj
           -> Hs.pure SpawnGeminiTeammateResponse
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.Nested Effects.Agent.AgentInfo)
                      @(Hs.Maybe Effects.Agent.AgentInfo))
                     (obj .: "agent")))
instance (HsJSONPB.ToJSON SpawnGeminiTeammateResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON SpawnGeminiTeammateResponse) where
  parseJSON = HsJSONPB.parseJSONPB
data CleanupRequest
  = CleanupRequest {cleanupRequestIssue :: Hs.Text,
                    cleanupRequestForce :: Hs.Bool,
                    cleanupRequestSubrepo :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData CleanupRequest)
instance (HsProtobuf.Named CleanupRequest) where
  nameOf _ = Hs.fromString "CleanupRequest"
instance (HsProtobuf.HasDefault CleanupRequest)
instance (HsProtobuf.Message CleanupRequest) where
  encodeMessage
    _
    CleanupRequest {cleanupRequestIssue, cleanupRequestForce,
                    cleanupRequestSubrepo}
    = Hs.mappend
        (Hs.mappend
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 1)
              ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                 cleanupRequestIssue))
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 2) cleanupRequestForce))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 3)
           ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              cleanupRequestSubrepo))
  decodeMessage _
    = Hs.pure CleanupRequest
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 3)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "issue") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2) (HsProtobufAST.Prim HsProtobufAST.Bool)
         (HsProtobufAST.Single "force") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 3)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "subrepo") [] ""]
instance (HsJSONPB.ToJSONPB CleanupRequest) where
  toJSONPB (CleanupRequest f1 f2 f3)
    = HsJSONPB.object
        ["issue" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "force" .= f2,
         "subrepo"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3)]
  toEncodingPB (CleanupRequest f1 f2 f3)
    = HsJSONPB.pairs
        ["issue" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "force" .= f2,
         "subrepo"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3)]
instance (HsJSONPB.FromJSONPB CleanupRequest) where
  parseJSONPB
    = HsJSONPB.withObject
        "CleanupRequest"
        (\ obj
           -> Hs.pure CleanupRequest
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "issue"))
                <*> obj .: "force"
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "subrepo")))
instance (HsJSONPB.ToJSON CleanupRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON CleanupRequest) where
  parseJSON = HsJSONPB.parseJSONPB
data CleanupResponse
  = CleanupResponse {cleanupResponseSuccess :: Hs.Bool,
                     cleanupResponseError :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData CleanupResponse)
instance (HsProtobuf.Named CleanupResponse) where
  nameOf _ = Hs.fromString "CleanupResponse"
instance (HsProtobuf.HasDefault CleanupResponse)
instance (HsProtobuf.Message CleanupResponse) where
  encodeMessage
    _
    CleanupResponse {cleanupResponseSuccess, cleanupResponseError}
    = Hs.mappend
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 1) cleanupResponseSuccess)
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 2)
           ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              cleanupResponseError))
  decodeMessage _
    = Hs.pure CleanupResponse
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1) (HsProtobufAST.Prim HsProtobufAST.Bool)
         (HsProtobufAST.Single "success") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "error") [] ""]
instance (HsJSONPB.ToJSONPB CleanupResponse) where
  toJSONPB (CleanupResponse f1 f2)
    = HsJSONPB.object
        ["success" .= f1,
         "error" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)]
  toEncodingPB (CleanupResponse f1 f2)
    = HsJSONPB.pairs
        ["success" .= f1,
         "error" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)]
instance (HsJSONPB.FromJSONPB CleanupResponse) where
  parseJSONPB
    = HsJSONPB.withObject
        "CleanupResponse"
        (\ obj
           -> Hs.pure CleanupResponse <*> obj .: "success"
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "error")))
instance (HsJSONPB.ToJSON CleanupResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON CleanupResponse) where
  parseJSON = HsJSONPB.parseJSONPB
data CleanupBatchRequest
  = CleanupBatchRequest {cleanupBatchRequestIssues :: (Hs.Vector Hs.Text),
                         cleanupBatchRequestForce :: Hs.Bool,
                         cleanupBatchRequestSubrepo :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData CleanupBatchRequest)
instance (HsProtobuf.Named CleanupBatchRequest) where
  nameOf _ = Hs.fromString "CleanupBatchRequest"
instance (HsProtobuf.HasDefault CleanupBatchRequest)
instance (HsProtobuf.Message CleanupBatchRequest) where
  encodeMessage
    _
    CleanupBatchRequest {cleanupBatchRequestIssues,
                         cleanupBatchRequestForce, cleanupBatchRequestSubrepo}
    = Hs.mappend
        (Hs.mappend
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 1)
              ((Hs.coerce
                  @(Hs.Vector Hs.Text)
                  @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
                 cleanupBatchRequestIssues))
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 2) cleanupBatchRequestForce))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 3)
           ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              cleanupBatchRequestSubrepo))
  decodeMessage _
    = Hs.pure CleanupBatchRequest
        <*>
          ((HsProtobuf.coerceOver
              @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
              @(Hs.Vector Hs.Text))
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 3)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Repeated HsProtobufAST.String)
         (HsProtobufAST.Single "issues") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2) (HsProtobufAST.Prim HsProtobufAST.Bool)
         (HsProtobufAST.Single "force") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 3)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "subrepo") [] ""]
instance (HsJSONPB.ToJSONPB CleanupBatchRequest) where
  toJSONPB (CleanupBatchRequest f1 f2 f3)
    = HsJSONPB.object
        ["issues"
           .=
             ((Hs.coerce
                 @(Hs.Vector Hs.Text)
                 @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
                f1),
         "force" .= f2,
         "subrepo"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3)]
  toEncodingPB (CleanupBatchRequest f1 f2 f3)
    = HsJSONPB.pairs
        ["issues"
           .=
             ((Hs.coerce
                 @(Hs.Vector Hs.Text)
                 @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
                f1),
         "force" .= f2,
         "subrepo"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3)]
instance (HsJSONPB.FromJSONPB CleanupBatchRequest) where
  parseJSONPB
    = HsJSONPB.withObject
        "CleanupBatchRequest"
        (\ obj
           -> Hs.pure CleanupBatchRequest
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
                      @(Hs.Vector Hs.Text))
                     (obj .: "issues"))
                <*> obj .: "force"
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "subrepo")))
instance (HsJSONPB.ToJSON CleanupBatchRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON CleanupBatchRequest) where
  parseJSON = HsJSONPB.parseJSONPB
data CleanupBatchResponse
  = CleanupBatchResponse {cleanupBatchResponseCleaned :: (Hs.Vector Hs.Text),
                          cleanupBatchResponseFailed :: (Hs.Vector Hs.Text),
                          cleanupBatchResponseErrors :: (Hs.Vector Hs.Text)}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData CleanupBatchResponse)
instance (HsProtobuf.Named CleanupBatchResponse) where
  nameOf _ = Hs.fromString "CleanupBatchResponse"
instance (HsProtobuf.HasDefault CleanupBatchResponse)
instance (HsProtobuf.Message CleanupBatchResponse) where
  encodeMessage
    _
    CleanupBatchResponse {cleanupBatchResponseCleaned,
                          cleanupBatchResponseFailed, cleanupBatchResponseErrors}
    = Hs.mappend
        (Hs.mappend
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 1)
              ((Hs.coerce
                  @(Hs.Vector Hs.Text)
                  @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
                 cleanupBatchResponseCleaned))
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 2)
              ((Hs.coerce
                  @(Hs.Vector Hs.Text)
                  @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
                 cleanupBatchResponseFailed)))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 3)
           ((Hs.coerce
               @(Hs.Vector Hs.Text)
               @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
              cleanupBatchResponseErrors))
  decodeMessage _
    = Hs.pure CleanupBatchResponse
        <*>
          ((HsProtobuf.coerceOver
              @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
              @(Hs.Vector Hs.Text))
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          ((HsProtobuf.coerceOver
              @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
              @(Hs.Vector Hs.Text))
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)))
        <*>
          ((HsProtobuf.coerceOver
              @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
              @(Hs.Vector Hs.Text))
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 3)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Repeated HsProtobufAST.String)
         (HsProtobufAST.Single "cleaned") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2)
         (HsProtobufAST.Repeated HsProtobufAST.String)
         (HsProtobufAST.Single "failed") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 3)
         (HsProtobufAST.Repeated HsProtobufAST.String)
         (HsProtobufAST.Single "errors") [] ""]
instance (HsJSONPB.ToJSONPB CleanupBatchResponse) where
  toJSONPB (CleanupBatchResponse f1 f2 f3)
    = HsJSONPB.object
        ["cleaned"
           .=
             ((Hs.coerce
                 @(Hs.Vector Hs.Text)
                 @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
                f1),
         "failed"
           .=
             ((Hs.coerce
                 @(Hs.Vector Hs.Text)
                 @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
                f2),
         "errors"
           .=
             ((Hs.coerce
                 @(Hs.Vector Hs.Text)
                 @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
                f3)]
  toEncodingPB (CleanupBatchResponse f1 f2 f3)
    = HsJSONPB.pairs
        ["cleaned"
           .=
             ((Hs.coerce
                 @(Hs.Vector Hs.Text)
                 @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
                f1),
         "failed"
           .=
             ((Hs.coerce
                 @(Hs.Vector Hs.Text)
                 @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
                f2),
         "errors"
           .=
             ((Hs.coerce
                 @(Hs.Vector Hs.Text)
                 @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
                f3)]
instance (HsJSONPB.FromJSONPB CleanupBatchResponse) where
  parseJSONPB
    = HsJSONPB.withObject
        "CleanupBatchResponse"
        (\ obj
           -> Hs.pure CleanupBatchResponse
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
                      @(Hs.Vector Hs.Text))
                     (obj .: "cleaned"))
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
                      @(Hs.Vector Hs.Text))
                     (obj .: "failed"))
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
                      @(Hs.Vector Hs.Text))
                     (obj .: "errors")))
instance (HsJSONPB.ToJSON CleanupBatchResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON CleanupBatchResponse) where
  parseJSON = HsJSONPB.parseJSONPB
data CleanupMergedRequest
  = CleanupMergedRequest {cleanupMergedRequestIssues :: (Hs.Vector Hs.Text),
                          cleanupMergedRequestSubrepo :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData CleanupMergedRequest)
instance (HsProtobuf.Named CleanupMergedRequest) where
  nameOf _ = Hs.fromString "CleanupMergedRequest"
instance (HsProtobuf.HasDefault CleanupMergedRequest)
instance (HsProtobuf.Message CleanupMergedRequest) where
  encodeMessage
    _
    CleanupMergedRequest {cleanupMergedRequestIssues,
                          cleanupMergedRequestSubrepo}
    = Hs.mappend
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 1)
           ((Hs.coerce
               @(Hs.Vector Hs.Text)
               @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
              cleanupMergedRequestIssues))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 2)
           ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              cleanupMergedRequestSubrepo))
  decodeMessage _
    = Hs.pure CleanupMergedRequest
        <*>
          ((HsProtobuf.coerceOver
              @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
              @(Hs.Vector Hs.Text))
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Repeated HsProtobufAST.String)
         (HsProtobufAST.Single "issues") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "subrepo") [] ""]
instance (HsJSONPB.ToJSONPB CleanupMergedRequest) where
  toJSONPB (CleanupMergedRequest f1 f2)
    = HsJSONPB.object
        ["issues"
           .=
             ((Hs.coerce
                 @(Hs.Vector Hs.Text)
                 @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
                f1),
         "subrepo"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)]
  toEncodingPB (CleanupMergedRequest f1 f2)
    = HsJSONPB.pairs
        ["issues"
           .=
             ((Hs.coerce
                 @(Hs.Vector Hs.Text)
                 @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
                f1),
         "subrepo"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)]
instance (HsJSONPB.FromJSONPB CleanupMergedRequest) where
  parseJSONPB
    = HsJSONPB.withObject
        "CleanupMergedRequest"
        (\ obj
           -> Hs.pure CleanupMergedRequest
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
                      @(Hs.Vector Hs.Text))
                     (obj .: "issues"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "subrepo")))
instance (HsJSONPB.ToJSON CleanupMergedRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON CleanupMergedRequest) where
  parseJSON = HsJSONPB.parseJSONPB
data CleanupMergedResponse
  = CleanupMergedResponse {cleanupMergedResponseCleaned :: (Hs.Vector Hs.Text),
                           cleanupMergedResponseSkipped :: (Hs.Vector Hs.Text),
                           cleanupMergedResponseErrors :: (Hs.Vector Hs.Text)}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData CleanupMergedResponse)
instance (HsProtobuf.Named CleanupMergedResponse) where
  nameOf _ = Hs.fromString "CleanupMergedResponse"
instance (HsProtobuf.HasDefault CleanupMergedResponse)
instance (HsProtobuf.Message CleanupMergedResponse) where
  encodeMessage
    _
    CleanupMergedResponse {cleanupMergedResponseCleaned,
                           cleanupMergedResponseSkipped, cleanupMergedResponseErrors}
    = Hs.mappend
        (Hs.mappend
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 1)
              ((Hs.coerce
                  @(Hs.Vector Hs.Text)
                  @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
                 cleanupMergedResponseCleaned))
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 2)
              ((Hs.coerce
                  @(Hs.Vector Hs.Text)
                  @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
                 cleanupMergedResponseSkipped)))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 3)
           ((Hs.coerce
               @(Hs.Vector Hs.Text)
               @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
              cleanupMergedResponseErrors))
  decodeMessage _
    = Hs.pure CleanupMergedResponse
        <*>
          ((HsProtobuf.coerceOver
              @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
              @(Hs.Vector Hs.Text))
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          ((HsProtobuf.coerceOver
              @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
              @(Hs.Vector Hs.Text))
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)))
        <*>
          ((HsProtobuf.coerceOver
              @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
              @(Hs.Vector Hs.Text))
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 3)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Repeated HsProtobufAST.String)
         (HsProtobufAST.Single "cleaned") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2)
         (HsProtobufAST.Repeated HsProtobufAST.String)
         (HsProtobufAST.Single "skipped") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 3)
         (HsProtobufAST.Repeated HsProtobufAST.String)
         (HsProtobufAST.Single "errors") [] ""]
instance (HsJSONPB.ToJSONPB CleanupMergedResponse) where
  toJSONPB (CleanupMergedResponse f1 f2 f3)
    = HsJSONPB.object
        ["cleaned"
           .=
             ((Hs.coerce
                 @(Hs.Vector Hs.Text)
                 @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
                f1),
         "skipped"
           .=
             ((Hs.coerce
                 @(Hs.Vector Hs.Text)
                 @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
                f2),
         "errors"
           .=
             ((Hs.coerce
                 @(Hs.Vector Hs.Text)
                 @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
                f3)]
  toEncodingPB (CleanupMergedResponse f1 f2 f3)
    = HsJSONPB.pairs
        ["cleaned"
           .=
             ((Hs.coerce
                 @(Hs.Vector Hs.Text)
                 @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
                f1),
         "skipped"
           .=
             ((Hs.coerce
                 @(Hs.Vector Hs.Text)
                 @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
                f2),
         "errors"
           .=
             ((Hs.coerce
                 @(Hs.Vector Hs.Text)
                 @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
                f3)]
instance (HsJSONPB.FromJSONPB CleanupMergedResponse) where
  parseJSONPB
    = HsJSONPB.withObject
        "CleanupMergedResponse"
        (\ obj
           -> Hs.pure CleanupMergedResponse
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
                      @(Hs.Vector Hs.Text))
                     (obj .: "cleaned"))
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
                      @(Hs.Vector Hs.Text))
                     (obj .: "skipped"))
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
                      @(Hs.Vector Hs.Text))
                     (obj .: "errors")))
instance (HsJSONPB.ToJSON CleanupMergedResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON CleanupMergedResponse) where
  parseJSON = HsJSONPB.parseJSONPB
data ListRequest
  = ListRequest {listRequestFilterStatus :: (HsProtobuf.Enumerated Effects.Agent.AgentStatus),
                 listRequestFilterRole :: (HsProtobuf.Enumerated ExoMonad.Common.Role),
                 listRequestSubrepo :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData ListRequest)
instance (HsProtobuf.Named ListRequest) where
  nameOf _ = Hs.fromString "ListRequest"
instance (HsProtobuf.HasDefault ListRequest)
instance (HsProtobuf.Message ListRequest) where
  encodeMessage
    _
    ListRequest {listRequestFilterStatus, listRequestFilterRole,
                 listRequestSubrepo}
    = Hs.mappend
        (Hs.mappend
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 1) listRequestFilterStatus)
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 2) listRequestFilterRole))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 3)
           ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              listRequestSubrepo))
  decodeMessage _
    = Hs.pure ListRequest
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 3)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim
            (HsProtobufAST.Named (HsProtobufAST.Single "AgentStatus")))
         (HsProtobufAST.Single "filter_status") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2)
         (HsProtobufAST.Prim
            (HsProtobufAST.Named
               (HsProtobufAST.Dots
                  (HsProtobufAST.Path ("exomonad" Hs.:| ["common", "Role"])))))
         (HsProtobufAST.Single "filter_role") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 3)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "subrepo") [] ""]
instance (HsJSONPB.ToJSONPB ListRequest) where
  toJSONPB (ListRequest f1 f2 f3)
    = HsJSONPB.object
        ["filter_status" .= f1, "filter_role" .= f2,
         "subrepo"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3)]
  toEncodingPB (ListRequest f1 f2 f3)
    = HsJSONPB.pairs
        ["filter_status" .= f1, "filter_role" .= f2,
         "subrepo"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3)]
instance (HsJSONPB.FromJSONPB ListRequest) where
  parseJSONPB
    = HsJSONPB.withObject
        "ListRequest"
        (\ obj
           -> Hs.pure ListRequest <*> obj .: "filter_status"
                <*> obj .: "filter_role"
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "subrepo")))
instance (HsJSONPB.ToJSON ListRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON ListRequest) where
  parseJSON = HsJSONPB.parseJSONPB
newtype ListResponse
  = ListResponse {listResponseAgents :: (Hs.Vector Effects.Agent.AgentInfo)}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData ListResponse)
instance (HsProtobuf.Named ListResponse) where
  nameOf _ = Hs.fromString "ListResponse"
instance (HsProtobuf.HasDefault ListResponse)
instance (HsProtobuf.Message ListResponse) where
  encodeMessage _ ListResponse {listResponseAgents}
    = (HsProtobuf.encodeMessageField
         (HsProtobuf.FieldNumber 1)
         ((Hs.coerce
             @(Hs.Vector Effects.Agent.AgentInfo)
             @(HsProtobuf.NestedVec Effects.Agent.AgentInfo))
            listResponseAgents))
  decodeMessage _
    = Hs.pure ListResponse
        <*>
          ((HsProtobuf.coerceOver
              @(HsProtobuf.NestedVec Effects.Agent.AgentInfo)
              @(Hs.Vector Effects.Agent.AgentInfo))
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Repeated
            (HsProtobufAST.Named (HsProtobufAST.Single "AgentInfo")))
         (HsProtobufAST.Single "agents") [] ""]
instance (HsJSONPB.ToJSONPB ListResponse) where
  toJSONPB (ListResponse f1)
    = HsJSONPB.object
        ["agents"
           .=
             ((Hs.coerce
                 @(Hs.Vector Effects.Agent.AgentInfo)
                 @(HsProtobuf.NestedVec Effects.Agent.AgentInfo))
                f1)]
  toEncodingPB (ListResponse f1)
    = HsJSONPB.pairs
        ["agents"
           .=
             ((Hs.coerce
                 @(Hs.Vector Effects.Agent.AgentInfo)
                 @(HsProtobuf.NestedVec Effects.Agent.AgentInfo))
                f1)]
instance (HsJSONPB.FromJSONPB ListResponse) where
  parseJSONPB
    = HsJSONPB.withObject
        "ListResponse"
        (\ obj
           -> Hs.pure ListResponse
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.NestedVec Effects.Agent.AgentInfo)
                      @(Hs.Vector Effects.Agent.AgentInfo))
                     (obj .: "agents")))
instance (HsJSONPB.ToJSON ListResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON ListResponse) where
  parseJSON = HsJSONPB.parseJSONPB
