{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE NegativeLiterals #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeOperators #-}
{-# OPTIONS_GHC -fno-warn-missing-export-lists #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-- | Generated by Haskell protocol buffer compiler. DO NOT EDIT!
module Effects.Copilot where
import qualified Prelude as Hs
import qualified Proto3.Suite.Class as HsProtobuf
import qualified Proto3.Suite.DotProto as HsProtobufAST
import qualified Proto3.Suite.JSONPB as HsJSONPB
import Proto3.Suite.JSONPB ( (.=), (.:) )
import qualified Proto3.Suite.Types as HsProtobuf
import qualified Proto3.Wire as HsProtobuf
import qualified Proto3.Wire.Decode as HsProtobuf
    ( Parser, RawField )
import qualified Control.Applicative as Hs
import Control.Applicative ( (<*>), (<|>), (<$>) )
import qualified Control.DeepSeq as Hs
import qualified Control.Monad as Hs
import qualified Data.ByteString as Hs
import qualified Data.Coerce as Hs
import qualified Data.Int as Hs ( Int16, Int32, Int64 )
import qualified Data.List.NonEmpty as Hs ( NonEmpty(..) )
import qualified Data.Map as Hs ( Map, mapKeysMonotonic )
import qualified Data.Proxy as Proxy
import qualified Data.String as Hs ( fromString )
import qualified Data.Text.Lazy as Hs ( Text )
import qualified Data.Vector as Hs ( Vector )
import qualified Data.Word as Hs ( Word16, Word32, Word64 )
import qualified GHC.Enum as Hs
import qualified GHC.Generics as Hs
import qualified Google.Protobuf.Wrappers.Polymorphic as HsProtobuf
    ( Wrapped(..) )
import qualified Unsafe.Coerce as Hs




data CopilotComment
  = CopilotComment {copilotCommentPath :: Hs.Text,
                    copilotCommentLine :: Hs.Int64,
                    copilotCommentBody :: Hs.Text,
                    copilotCommentDiffHunk :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData CopilotComment)
instance (HsProtobuf.Named CopilotComment) where
  nameOf _ = Hs.fromString "CopilotComment"
instance (HsProtobuf.HasDefault CopilotComment)
instance (HsProtobuf.Message CopilotComment) where
  encodeMessage
    _
    CopilotComment {copilotCommentPath, copilotCommentLine,
                    copilotCommentBody, copilotCommentDiffHunk}
    = Hs.mappend
        (Hs.mappend
           (Hs.mappend
              (HsProtobuf.encodeMessageField
                 (HsProtobuf.FieldNumber 1)
                 ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                    copilotCommentPath))
              (HsProtobuf.encodeMessageField
                 (HsProtobuf.FieldNumber 2) copilotCommentLine))
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 3)
              ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                 copilotCommentBody)))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 4)
           ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              copilotCommentDiffHunk))
  decodeMessage _
    = Hs.pure CopilotComment
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 3)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 4)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "path") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2) (HsProtobufAST.Prim HsProtobufAST.Int64)
         (HsProtobufAST.Single "line") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 3)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "body") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 4)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "diff_hunk") [] ""]
instance (HsJSONPB.ToJSONPB CopilotComment) where
  toJSONPB (CopilotComment f1 f2 f3 f4)
    = HsJSONPB.object
        ["path" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "line" .= f2,
         "body" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3),
         "diff_hunk"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f4)]
  toEncodingPB (CopilotComment f1 f2 f3 f4)
    = HsJSONPB.pairs
        ["path" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "line" .= f2,
         "body" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3),
         "diff_hunk"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f4)]
instance (HsJSONPB.FromJSONPB CopilotComment) where
  parseJSONPB
    = HsJSONPB.withObject
        "CopilotComment"
        (\ obj
           -> Hs.pure CopilotComment
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "path"))
                <*> obj .: "line"
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "body"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "diff_hunk")))
instance (HsJSONPB.ToJSON CopilotComment) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON CopilotComment) where
  parseJSON = HsJSONPB.parseJSONPB
data WaitForCopilotReviewRequest
  = WaitForCopilotReviewRequest {waitForCopilotReviewRequestPrNumber :: Hs.Int64,
                                 waitForCopilotReviewRequestTimeoutSecs :: Hs.Int64,
                                 waitForCopilotReviewRequestPollIntervalSecs :: Hs.Int64}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData WaitForCopilotReviewRequest)
instance (HsProtobuf.Named WaitForCopilotReviewRequest) where
  nameOf _ = Hs.fromString "WaitForCopilotReviewRequest"
instance (HsProtobuf.HasDefault WaitForCopilotReviewRequest)
instance (HsProtobuf.Message WaitForCopilotReviewRequest) where
  encodeMessage
    _
    WaitForCopilotReviewRequest {waitForCopilotReviewRequestPrNumber,
                                 waitForCopilotReviewRequestTimeoutSecs,
                                 waitForCopilotReviewRequestPollIntervalSecs}
    = Hs.mappend
        (Hs.mappend
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 1) waitForCopilotReviewRequestPrNumber)
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 2) waitForCopilotReviewRequestTimeoutSecs))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 3)
           waitForCopilotReviewRequestPollIntervalSecs)
  decodeMessage _
    = Hs.pure WaitForCopilotReviewRequest
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 3)
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1) (HsProtobufAST.Prim HsProtobufAST.Int64)
         (HsProtobufAST.Single "pr_number") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2) (HsProtobufAST.Prim HsProtobufAST.Int64)
         (HsProtobufAST.Single "timeout_secs") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 3) (HsProtobufAST.Prim HsProtobufAST.Int64)
         (HsProtobufAST.Single "poll_interval_secs") [] ""]
instance (HsJSONPB.ToJSONPB WaitForCopilotReviewRequest) where
  toJSONPB (WaitForCopilotReviewRequest f1 f2 f3)
    = HsJSONPB.object
        ["pr_number" .= f1, "timeout_secs" .= f2,
         "poll_interval_secs" .= f3]
  toEncodingPB (WaitForCopilotReviewRequest f1 f2 f3)
    = HsJSONPB.pairs
        ["pr_number" .= f1, "timeout_secs" .= f2,
         "poll_interval_secs" .= f3]
instance (HsJSONPB.FromJSONPB WaitForCopilotReviewRequest) where
  parseJSONPB
    = HsJSONPB.withObject
        "WaitForCopilotReviewRequest"
        (\ obj
           -> Hs.pure WaitForCopilotReviewRequest <*> obj .: "pr_number"
                <*> obj .: "timeout_secs"
                <*> obj .: "poll_interval_secs")
instance (HsJSONPB.ToJSON WaitForCopilotReviewRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON WaitForCopilotReviewRequest) where
  parseJSON = HsJSONPB.parseJSONPB
data WaitForCopilotReviewResponse
  = WaitForCopilotReviewResponse {waitForCopilotReviewResponseStatus :: Hs.Text,
                                  waitForCopilotReviewResponseComments :: (Hs.Vector Effects.Copilot.CopilotComment)}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData WaitForCopilotReviewResponse)
instance (HsProtobuf.Named WaitForCopilotReviewResponse) where
  nameOf _ = Hs.fromString "WaitForCopilotReviewResponse"
instance (HsProtobuf.HasDefault WaitForCopilotReviewResponse)
instance (HsProtobuf.Message WaitForCopilotReviewResponse) where
  encodeMessage
    _
    WaitForCopilotReviewResponse {waitForCopilotReviewResponseStatus,
                                  waitForCopilotReviewResponseComments}
    = Hs.mappend
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 1)
           ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              waitForCopilotReviewResponseStatus))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 2)
           ((Hs.coerce
               @(Hs.Vector Effects.Copilot.CopilotComment)
               @(HsProtobuf.NestedVec Effects.Copilot.CopilotComment))
              waitForCopilotReviewResponseComments))
  decodeMessage _
    = Hs.pure WaitForCopilotReviewResponse
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          ((HsProtobuf.coerceOver
              @(HsProtobuf.NestedVec Effects.Copilot.CopilotComment)
              @(Hs.Vector Effects.Copilot.CopilotComment))
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "status") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2)
         (HsProtobufAST.Repeated
            (HsProtobufAST.Named (HsProtobufAST.Single "CopilotComment")))
         (HsProtobufAST.Single "comments") [] ""]
instance (HsJSONPB.ToJSONPB WaitForCopilotReviewResponse) where
  toJSONPB (WaitForCopilotReviewResponse f1 f2)
    = HsJSONPB.object
        ["status"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "comments"
           .=
             ((Hs.coerce
                 @(Hs.Vector Effects.Copilot.CopilotComment)
                 @(HsProtobuf.NestedVec Effects.Copilot.CopilotComment))
                f2)]
  toEncodingPB (WaitForCopilotReviewResponse f1 f2)
    = HsJSONPB.pairs
        ["status"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "comments"
           .=
             ((Hs.coerce
                 @(Hs.Vector Effects.Copilot.CopilotComment)
                 @(HsProtobuf.NestedVec Effects.Copilot.CopilotComment))
                f2)]
instance (HsJSONPB.FromJSONPB WaitForCopilotReviewResponse) where
  parseJSONPB
    = HsJSONPB.withObject
        "WaitForCopilotReviewResponse"
        (\ obj
           -> Hs.pure WaitForCopilotReviewResponse
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "status"))
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.NestedVec Effects.Copilot.CopilotComment)
                      @(Hs.Vector Effects.Copilot.CopilotComment))
                     (obj .: "comments")))
instance (HsJSONPB.ToJSON WaitForCopilotReviewResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON WaitForCopilotReviewResponse) where
  parseJSON = HsJSONPB.parseJSONPB