{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE NegativeLiterals #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeOperators #-}
{-# OPTIONS_GHC -fno-warn-missing-export-lists #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-- | Generated by Haskell protocol buffer compiler. DO NOT EDIT!
module Effects.Events where
import qualified Prelude as Hs
import qualified Proto3.Suite.Class as HsProtobuf
import qualified Proto3.Suite.DotProto as HsProtobufAST
import qualified Proto3.Suite.JSONPB as HsJSONPB
import Proto3.Suite.JSONPB ( (.=), (.:) )
import qualified Proto3.Suite.Types as HsProtobuf
import qualified Proto3.Wire as HsProtobuf
import qualified Proto3.Wire.Decode as HsProtobuf
    ( Parser, RawField )
import qualified Control.Applicative as Hs
import Control.Applicative ( (<*>), (<|>), (<$>) )
import qualified Control.DeepSeq as Hs
import qualified Control.Monad as Hs
import qualified Data.ByteString as Hs
import qualified Data.Coerce as Hs
import qualified Data.Int as Hs ( Int16, Int32, Int64 )
import qualified Data.List.NonEmpty as Hs ( NonEmpty(..) )
import qualified Data.Map as Hs ( Map, mapKeysMonotonic )
import qualified Data.Proxy as Proxy
import qualified Data.String as Hs ( fromString )
import qualified Data.Text.Lazy as Hs ( Text )
import qualified Data.Vector as Hs ( Vector )
import qualified Data.Word as Hs ( Word16, Word32, Word64 )
import qualified GHC.Enum as Hs
import qualified GHC.Generics as Hs
import qualified Google.Protobuf.Wrappers.Polymorphic as HsProtobuf
    ( Wrapped(..) )
import qualified Unsafe.Coerce as Hs




data WaitForEventRequest
  = WaitForEventRequest {waitForEventRequestTypes :: (Hs.Vector Hs.Text),
                         waitForEventRequestTimeoutSecs :: Hs.Int32,
                         waitForEventRequestAfterEventId :: Hs.Word64}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData WaitForEventRequest)
instance (HsProtobuf.Named WaitForEventRequest) where
  nameOf _ = Hs.fromString "WaitForEventRequest"
instance (HsProtobuf.HasDefault WaitForEventRequest)
instance (HsProtobuf.Message WaitForEventRequest) where
  encodeMessage
    _
    WaitForEventRequest {waitForEventRequestTypes,
                         waitForEventRequestTimeoutSecs, waitForEventRequestAfterEventId}
    = Hs.mappend
        (Hs.mappend
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 1)
              ((Hs.coerce
                  @(Hs.Vector Hs.Text)
                  @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
                 waitForEventRequestTypes))
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 2) waitForEventRequestTimeoutSecs))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 3) waitForEventRequestAfterEventId)
  decodeMessage _
    = Hs.pure WaitForEventRequest
        <*>
          ((HsProtobuf.coerceOver
              @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
              @(Hs.Vector Hs.Text))
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 3)
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Repeated HsProtobufAST.String)
         (HsProtobufAST.Single "types") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2) (HsProtobufAST.Prim HsProtobufAST.Int32)
         (HsProtobufAST.Single "timeout_secs") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 3)
         (HsProtobufAST.Prim HsProtobufAST.UInt64)
         (HsProtobufAST.Single "after_event_id") [] ""]
instance (HsJSONPB.ToJSONPB WaitForEventRequest) where
  toJSONPB (WaitForEventRequest f1 f2 f3)
    = HsJSONPB.object
        ["types"
           .=
             ((Hs.coerce
                 @(Hs.Vector Hs.Text)
                 @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
                f1),
         "timeout_secs" .= f2, "after_event_id" .= f3]
  toEncodingPB (WaitForEventRequest f1 f2 f3)
    = HsJSONPB.pairs
        ["types"
           .=
             ((Hs.coerce
                 @(Hs.Vector Hs.Text)
                 @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
                f1),
         "timeout_secs" .= f2, "after_event_id" .= f3]
instance (HsJSONPB.FromJSONPB WaitForEventRequest) where
  parseJSONPB
    = HsJSONPB.withObject
        "WaitForEventRequest"
        (\ obj
           -> Hs.pure WaitForEventRequest
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
                      @(Hs.Vector Hs.Text))
                     (obj .: "types"))
                <*> obj .: "timeout_secs"
                <*> obj .: "after_event_id")
instance (HsJSONPB.ToJSON WaitForEventRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON WaitForEventRequest) where
  parseJSON = HsJSONPB.parseJSONPB
newtype WaitForEventResponse
  = WaitForEventResponse {waitForEventResponseEvent :: (Hs.Maybe Effects.Events.Event)}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData WaitForEventResponse)
instance (HsProtobuf.Named WaitForEventResponse) where
  nameOf _ = Hs.fromString "WaitForEventResponse"
instance (HsProtobuf.HasDefault WaitForEventResponse)
instance (HsProtobuf.Message WaitForEventResponse) where
  encodeMessage _ WaitForEventResponse {waitForEventResponseEvent}
    = (HsProtobuf.encodeMessageField
         (HsProtobuf.FieldNumber 1)
         ((Hs.coerce
             @(Hs.Maybe Effects.Events.Event)
             @(HsProtobuf.Nested Effects.Events.Event))
            waitForEventResponseEvent))
  decodeMessage _
    = Hs.pure WaitForEventResponse
        <*>
          ((HsProtobuf.coerceOver
              @(HsProtobuf.Nested Effects.Events.Event)
              @(Hs.Maybe Effects.Events.Event))
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim
            (HsProtobufAST.Named (HsProtobufAST.Single "Event")))
         (HsProtobufAST.Single "event") [] ""]
instance (HsJSONPB.ToJSONPB WaitForEventResponse) where
  toJSONPB (WaitForEventResponse f1)
    = HsJSONPB.object
        ["event"
           .=
             ((Hs.coerce
                 @(Hs.Maybe Effects.Events.Event)
                 @(HsProtobuf.Nested Effects.Events.Event))
                f1)]
  toEncodingPB (WaitForEventResponse f1)
    = HsJSONPB.pairs
        ["event"
           .=
             ((Hs.coerce
                 @(Hs.Maybe Effects.Events.Event)
                 @(HsProtobuf.Nested Effects.Events.Event))
                f1)]
instance (HsJSONPB.FromJSONPB WaitForEventResponse) where
  parseJSONPB
    = HsJSONPB.withObject
        "WaitForEventResponse"
        (\ obj
           -> Hs.pure WaitForEventResponse
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.Nested Effects.Events.Event)
                      @(Hs.Maybe Effects.Events.Event))
                     (obj .: "event")))
instance (HsJSONPB.ToJSON WaitForEventResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON WaitForEventResponse) where
  parseJSON = HsJSONPB.parseJSONPB
data NotifyEventRequest
  = NotifyEventRequest {notifyEventRequestSessionId :: Hs.Text,
                        notifyEventRequestEvent :: (Hs.Maybe Effects.Events.Event)}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData NotifyEventRequest)
instance (HsProtobuf.Named NotifyEventRequest) where
  nameOf _ = Hs.fromString "NotifyEventRequest"
instance (HsProtobuf.HasDefault NotifyEventRequest)
instance (HsProtobuf.Message NotifyEventRequest) where
  encodeMessage
    _
    NotifyEventRequest {notifyEventRequestSessionId,
                        notifyEventRequestEvent}
    = Hs.mappend
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 1)
           ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              notifyEventRequestSessionId))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 2)
           ((Hs.coerce
               @(Hs.Maybe Effects.Events.Event)
               @(HsProtobuf.Nested Effects.Events.Event))
              notifyEventRequestEvent))
  decodeMessage _
    = Hs.pure NotifyEventRequest
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          ((HsProtobuf.coerceOver
              @(HsProtobuf.Nested Effects.Events.Event)
              @(Hs.Maybe Effects.Events.Event))
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "session_id") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2)
         (HsProtobufAST.Prim
            (HsProtobufAST.Named (HsProtobufAST.Single "Event")))
         (HsProtobufAST.Single "event") [] ""]
instance (HsJSONPB.ToJSONPB NotifyEventRequest) where
  toJSONPB (NotifyEventRequest f1 f2)
    = HsJSONPB.object
        ["session_id"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "event"
           .=
             ((Hs.coerce
                 @(Hs.Maybe Effects.Events.Event)
                 @(HsProtobuf.Nested Effects.Events.Event))
                f2)]
  toEncodingPB (NotifyEventRequest f1 f2)
    = HsJSONPB.pairs
        ["session_id"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "event"
           .=
             ((Hs.coerce
                 @(Hs.Maybe Effects.Events.Event)
                 @(HsProtobuf.Nested Effects.Events.Event))
                f2)]
instance (HsJSONPB.FromJSONPB NotifyEventRequest) where
  parseJSONPB
    = HsJSONPB.withObject
        "NotifyEventRequest"
        (\ obj
           -> Hs.pure NotifyEventRequest
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "session_id"))
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.Nested Effects.Events.Event)
                      @(Hs.Maybe Effects.Events.Event))
                     (obj .: "event")))
instance (HsJSONPB.ToJSON NotifyEventRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON NotifyEventRequest) where
  parseJSON = HsJSONPB.parseJSONPB
newtype NotifyEventResponse
  = NotifyEventResponse {notifyEventResponseSuccess :: Hs.Bool}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData NotifyEventResponse)
instance (HsProtobuf.Named NotifyEventResponse) where
  nameOf _ = Hs.fromString "NotifyEventResponse"
instance (HsProtobuf.HasDefault NotifyEventResponse)
instance (HsProtobuf.Message NotifyEventResponse) where
  encodeMessage _ NotifyEventResponse {notifyEventResponseSuccess}
    = (HsProtobuf.encodeMessageField
         (HsProtobuf.FieldNumber 1) notifyEventResponseSuccess)
  decodeMessage _
    = Hs.pure NotifyEventResponse
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1) (HsProtobufAST.Prim HsProtobufAST.Bool)
         (HsProtobufAST.Single "success") [] ""]
instance (HsJSONPB.ToJSONPB NotifyEventResponse) where
  toJSONPB (NotifyEventResponse f1)
    = HsJSONPB.object ["success" .= f1]
  toEncodingPB (NotifyEventResponse f1)
    = HsJSONPB.pairs ["success" .= f1]
instance (HsJSONPB.FromJSONPB NotifyEventResponse) where
  parseJSONPB
    = HsJSONPB.withObject
        "NotifyEventResponse"
        (\ obj -> Hs.pure NotifyEventResponse <*> obj .: "success")
instance (HsJSONPB.ToJSON NotifyEventResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON NotifyEventResponse) where
  parseJSON = HsJSONPB.parseJSONPB
data Event
  = Event {eventEventId :: Hs.Word64,
           eventEventType :: (Hs.Maybe EventEventType)}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData Event)
instance (HsProtobuf.Named Event) where
  nameOf _ = Hs.fromString "Event"
instance (HsProtobuf.HasDefault Event)
instance (HsProtobuf.Message Event) where
  encodeMessage _ Event {eventEventId, eventEventType}
    = Hs.mappend
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 3) eventEventId)
        (case eventEventType of
           Hs.Nothing -> Hs.mempty
           Hs.Just x
             -> case x of
                  EventEventTypeAgentMessage y
                    -> HsProtobuf.encodeMessageField
                         (HsProtobuf.FieldNumber 1)
                         ((Hs.coerce
                             @(Hs.Maybe Effects.Events.AgentMessage)
                             @(HsProtobuf.Nested Effects.Events.AgentMessage))
                            (Hs.Just y))
                  EventEventTypeTimeout y
                    -> HsProtobuf.encodeMessageField
                         (HsProtobuf.FieldNumber 2)
                         ((Hs.coerce
                             @(Hs.Maybe Effects.Events.Timeout)
                             @(HsProtobuf.Nested Effects.Events.Timeout))
                            (Hs.Just y)))
  decodeMessage _
    = Hs.pure Event
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 3)
        <*>
          HsProtobuf.oneof
            Hs.Nothing
            [((HsProtobuf.FieldNumber 1), 
              Hs.pure (Hs.fmap EventEventTypeAgentMessage)
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.Nested Effects.Events.AgentMessage)
                      @(Hs.Maybe Effects.Events.AgentMessage))
                     HsProtobuf.decodeMessageField)),
             ((HsProtobuf.FieldNumber 2), 
              Hs.pure (Hs.fmap EventEventTypeTimeout)
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.Nested Effects.Events.Timeout)
                      @(Hs.Maybe Effects.Events.Timeout))
                     HsProtobuf.decodeMessageField))]
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 3)
         (HsProtobufAST.Prim HsProtobufAST.UInt64)
         (HsProtobufAST.Single "event_id") [] ""]
instance (HsJSONPB.ToJSONPB Event) where
  toJSONPB (Event f3 f1_or_f2)
    = HsJSONPB.object
        ["event_id" .= f3,
         (let
            encodeEvent_type
              = (case f1_or_f2 of
                   Hs.Just (EventEventTypeAgentMessage f1)
                     -> HsJSONPB.pair "agent_message" f1
                   Hs.Just (EventEventTypeTimeout f2) -> HsJSONPB.pair "timeout" f2
                   Hs.Nothing -> Hs.mempty)
          in
            (\ options
               -> if HsJSONPB.optEmitNamedOneof options then
                      ("event_type" .= HsJSONPB.objectOrNull [encodeEvent_type] options)
                        options
                  else
                      encodeEvent_type options))]
  toEncodingPB (Event f3 f1_or_f2)
    = HsJSONPB.pairs
        ["event_id" .= f3,
         (let
            encodeEvent_type
              = (case f1_or_f2 of
                   Hs.Just (EventEventTypeAgentMessage f1)
                     -> HsJSONPB.pair "agent_message" f1
                   Hs.Just (EventEventTypeTimeout f2) -> HsJSONPB.pair "timeout" f2
                   Hs.Nothing -> Hs.mempty)
          in
            (\ options
               -> if HsJSONPB.optEmitNamedOneof options then
                      ("event_type" .= HsJSONPB.pairsOrNull [encodeEvent_type] options)
                        options
                  else
                      encodeEvent_type options))]
instance (HsJSONPB.FromJSONPB Event) where
  parseJSONPB
    = HsJSONPB.withObject
        "Event"
        (\ obj
           -> Hs.pure Event <*> obj .: "event_id"
                <*>
                  (let
                     parseEvent_type parseObj
                       = Hs.msum
                           [Hs.Just Hs.. EventEventTypeAgentMessage
                              <$> HsJSONPB.parseField parseObj "agent_message",
                            Hs.Just Hs.. EventEventTypeTimeout
                              <$> HsJSONPB.parseField parseObj "timeout",
                            Hs.pure Hs.Nothing]
                   in
                     (obj .: "event_type"
                        Hs.>>= HsJSONPB.withObject "event_type" parseEvent_type)
                       <|> (parseEvent_type obj)))
instance (HsJSONPB.ToJSON Event) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON Event) where
  parseJSON = HsJSONPB.parseJSONPB
data EventEventType
  = EventEventTypeAgentMessage Effects.Events.AgentMessage |
    EventEventTypeTimeout Effects.Events.Timeout
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData EventEventType)
instance (HsProtobuf.Named EventEventType) where
  nameOf _ = Hs.fromString "EventEventType"
data AgentMessage
  = AgentMessage {agentMessageAgentId :: Hs.Text,
                  agentMessageStatus :: Hs.Text,
                  agentMessageChanges :: (Hs.Vector Hs.Text),
                  agentMessageMessage :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData AgentMessage)
instance (HsProtobuf.Named AgentMessage) where
  nameOf _ = Hs.fromString "AgentMessage"
instance (HsProtobuf.HasDefault AgentMessage)
instance (HsProtobuf.Message AgentMessage) where
  encodeMessage
    _
    AgentMessage {agentMessageAgentId, agentMessageStatus,
                  agentMessageChanges, agentMessageMessage}
    = Hs.mappend
        (Hs.mappend
           (Hs.mappend
              (HsProtobuf.encodeMessageField
                 (HsProtobuf.FieldNumber 1)
                 ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                    agentMessageAgentId))
              (HsProtobuf.encodeMessageField
                 (HsProtobuf.FieldNumber 2)
                 ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                    agentMessageStatus)))
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 3)
              ((Hs.coerce
                  @(Hs.Vector Hs.Text)
                  @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
                 agentMessageChanges)))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 4)
           ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              agentMessageMessage))
  decodeMessage _
    = Hs.pure AgentMessage
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)))
        <*>
          ((HsProtobuf.coerceOver
              @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
              @(Hs.Vector Hs.Text))
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 3)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 4)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "agent_id") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "status") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 3)
         (HsProtobufAST.Repeated HsProtobufAST.String)
         (HsProtobufAST.Single "changes") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 4)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "message") [] ""]
instance (HsJSONPB.ToJSONPB AgentMessage) where
  toJSONPB (AgentMessage f1 f2 f3 f4)
    = HsJSONPB.object
        ["agent_id"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "status" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
         "changes"
           .=
             ((Hs.coerce
                 @(Hs.Vector Hs.Text)
                 @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
                f3),
         "message"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f4)]
  toEncodingPB (AgentMessage f1 f2 f3 f4)
    = HsJSONPB.pairs
        ["agent_id"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "status" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
         "changes"
           .=
             ((Hs.coerce
                 @(Hs.Vector Hs.Text)
                 @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
                f3),
         "message"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f4)]
instance (HsJSONPB.FromJSONPB AgentMessage) where
  parseJSONPB
    = HsJSONPB.withObject
        "AgentMessage"
        (\ obj
           -> Hs.pure AgentMessage
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "agent_id"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "status"))
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
                      @(Hs.Vector Hs.Text))
                     (obj .: "changes"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "message")))
instance (HsJSONPB.ToJSON AgentMessage) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON AgentMessage) where
  parseJSON = HsJSONPB.parseJSONPB
newtype Timeout
  = Timeout {timeoutTimeoutSecs :: Hs.Int32}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData Timeout)
instance (HsProtobuf.Named Timeout) where
  nameOf _ = Hs.fromString "Timeout"
instance (HsProtobuf.HasDefault Timeout)
instance (HsProtobuf.Message Timeout) where
  encodeMessage _ Timeout {timeoutTimeoutSecs}
    = (HsProtobuf.encodeMessageField
         (HsProtobuf.FieldNumber 1) timeoutTimeoutSecs)
  decodeMessage _
    = Hs.pure Timeout
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1) (HsProtobufAST.Prim HsProtobufAST.Int32)
         (HsProtobufAST.Single "timeout_secs") [] ""]
instance (HsJSONPB.ToJSONPB Timeout) where
  toJSONPB (Timeout f1) = HsJSONPB.object ["timeout_secs" .= f1]
  toEncodingPB (Timeout f1) = HsJSONPB.pairs ["timeout_secs" .= f1]
instance (HsJSONPB.FromJSONPB Timeout) where
  parseJSONPB
    = HsJSONPB.withObject
        "Timeout" (\ obj -> Hs.pure Timeout <*> obj .: "timeout_secs")
instance (HsJSONPB.ToJSON Timeout) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON Timeout) where
  parseJSON = HsJSONPB.parseJSONPB
data SendMessageRequest
  = SendMessageRequest {sendMessageRequestRecipient :: Hs.Text,
                        sendMessageRequestContent :: Hs.Text,
                        sendMessageRequestSummary :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData SendMessageRequest)
instance (HsProtobuf.Named SendMessageRequest) where
  nameOf _ = Hs.fromString "SendMessageRequest"
instance (HsProtobuf.HasDefault SendMessageRequest)
instance (HsProtobuf.Message SendMessageRequest) where
  encodeMessage
    _
    SendMessageRequest {sendMessageRequestRecipient,
                        sendMessageRequestContent, sendMessageRequestSummary}
    = Hs.mappend
        (Hs.mappend
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 1)
              ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                 sendMessageRequestRecipient))
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 2)
              ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                 sendMessageRequestContent)))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 3)
           ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              sendMessageRequestSummary))
  decodeMessage _
    = Hs.pure SendMessageRequest
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 3)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "recipient") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "content") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 3)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "summary") [] ""]
instance (HsJSONPB.ToJSONPB SendMessageRequest) where
  toJSONPB (SendMessageRequest f1 f2 f3)
    = HsJSONPB.object
        ["recipient"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "content"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
         "summary"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3)]
  toEncodingPB (SendMessageRequest f1 f2 f3)
    = HsJSONPB.pairs
        ["recipient"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "content"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
         "summary"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3)]
instance (HsJSONPB.FromJSONPB SendMessageRequest) where
  parseJSONPB
    = HsJSONPB.withObject
        "SendMessageRequest"
        (\ obj
           -> Hs.pure SendMessageRequest
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "recipient"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "content"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "summary")))
instance (HsJSONPB.ToJSON SendMessageRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON SendMessageRequest) where
  parseJSON = HsJSONPB.parseJSONPB
data SendMessageResponse
  = SendMessageResponse {sendMessageResponseSuccess :: Hs.Bool,
                         sendMessageResponseDeliveryMethod :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData SendMessageResponse)
instance (HsProtobuf.Named SendMessageResponse) where
  nameOf _ = Hs.fromString "SendMessageResponse"
instance (HsProtobuf.HasDefault SendMessageResponse)
instance (HsProtobuf.Message SendMessageResponse) where
  encodeMessage
    _
    SendMessageResponse {sendMessageResponseSuccess,
                         sendMessageResponseDeliveryMethod}
    = Hs.mappend
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 1) sendMessageResponseSuccess)
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 2)
           ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              sendMessageResponseDeliveryMethod))
  decodeMessage _
    = Hs.pure SendMessageResponse
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1) (HsProtobufAST.Prim HsProtobufAST.Bool)
         (HsProtobufAST.Single "success") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "delivery_method") [] ""]
instance (HsJSONPB.ToJSONPB SendMessageResponse) where
  toJSONPB (SendMessageResponse f1 f2)
    = HsJSONPB.object
        ["success" .= f1,
         "delivery_method"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)]
  toEncodingPB (SendMessageResponse f1 f2)
    = HsJSONPB.pairs
        ["success" .= f1,
         "delivery_method"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)]
instance (HsJSONPB.FromJSONPB SendMessageResponse) where
  parseJSONPB
    = HsJSONPB.withObject
        "SendMessageResponse"
        (\ obj
           -> Hs.pure SendMessageResponse <*> obj .: "success"
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "delivery_method")))
instance (HsJSONPB.ToJSON SendMessageResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON SendMessageResponse) where
  parseJSON = HsJSONPB.parseJSONPB
data NotifyStatus
  = NotifyStatusNOTIFY_STATUS_UNSPECIFIED |
    NotifyStatusNOTIFY_STATUS_SUCCESS |
    NotifyStatusNOTIFY_STATUS_FAILURE
  deriving (Hs.Show, Hs.Eq, Hs.Generic, Hs.NFData)
instance (HsProtobuf.Named NotifyStatus) where
  nameOf _ = Hs.fromString "NotifyStatus"
instance (HsProtobuf.HasDefault NotifyStatus)
instance (Hs.Bounded NotifyStatus) where
  minBound = NotifyStatusNOTIFY_STATUS_UNSPECIFIED
  maxBound = NotifyStatusNOTIFY_STATUS_FAILURE
instance (Hs.Ord NotifyStatus) where
  compare x y
    = Hs.compare
        (HsProtobuf.fromProtoEnum x) (HsProtobuf.fromProtoEnum y)
instance (HsProtobuf.ProtoEnum NotifyStatus) where
  toProtoEnumMay 0 = Hs.Just NotifyStatusNOTIFY_STATUS_UNSPECIFIED
  toProtoEnumMay 1 = Hs.Just NotifyStatusNOTIFY_STATUS_SUCCESS
  toProtoEnumMay 2 = Hs.Just NotifyStatusNOTIFY_STATUS_FAILURE
  toProtoEnumMay _ = Hs.Nothing
  fromProtoEnum NotifyStatusNOTIFY_STATUS_UNSPECIFIED = 0
  fromProtoEnum NotifyStatusNOTIFY_STATUS_SUCCESS = 1
  fromProtoEnum NotifyStatusNOTIFY_STATUS_FAILURE = 2
instance (HsJSONPB.ToJSONPB NotifyStatus) where
  toJSONPB x _ = HsJSONPB.enumFieldString x
  toEncodingPB x _ = HsJSONPB.enumFieldEncoding x
instance (HsJSONPB.FromJSONPB NotifyStatus) where
  parseJSONPB (HsJSONPB.String "NOTIFY_STATUS_UNSPECIFIED")
    = Hs.pure NotifyStatusNOTIFY_STATUS_UNSPECIFIED
  parseJSONPB (HsJSONPB.String "NOTIFY_STATUS_SUCCESS")
    = Hs.pure NotifyStatusNOTIFY_STATUS_SUCCESS
  parseJSONPB (HsJSONPB.String "NOTIFY_STATUS_FAILURE")
    = Hs.pure NotifyStatusNOTIFY_STATUS_FAILURE
  parseJSONPB v = HsJSONPB.typeMismatch "NotifyStatus" v
instance (HsJSONPB.ToJSON NotifyStatus) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON NotifyStatus) where
  parseJSON = HsJSONPB.parseJSONPB
instance (HsProtobuf.Finite NotifyStatus)
data NotifyParentRequest
  = NotifyParentRequest {notifyParentRequestStatus :: (HsProtobuf.Enumerated Effects.Events.NotifyStatus),
                         notifyParentRequestMessage :: Hs.Text,
                         notifyParentRequestAgentId :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData NotifyParentRequest)
instance (HsProtobuf.Named NotifyParentRequest) where
  nameOf _ = Hs.fromString "NotifyParentRequest"
instance (HsProtobuf.HasDefault NotifyParentRequest)
instance (HsProtobuf.Message NotifyParentRequest) where
  encodeMessage
    _
    NotifyParentRequest {notifyParentRequestStatus,
                         notifyParentRequestMessage, notifyParentRequestAgentId}
    = Hs.mappend
        (Hs.mappend
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 1) notifyParentRequestStatus)
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 2)
              ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                 notifyParentRequestMessage)))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 3)
           ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              notifyParentRequestAgentId))
  decodeMessage _
    = Hs.pure NotifyParentRequest
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 3)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim
            (HsProtobufAST.Named (HsProtobufAST.Single "NotifyStatus")))
         (HsProtobufAST.Single "status") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "message") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 3)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "agent_id") [] ""]
instance (HsJSONPB.ToJSONPB NotifyParentRequest) where
  toJSONPB (NotifyParentRequest f1 f2 f3)
    = HsJSONPB.object
        ["status" .= f1,
         "message"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
         "agent_id"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3)]
  toEncodingPB (NotifyParentRequest f1 f2 f3)
    = HsJSONPB.pairs
        ["status" .= f1,
         "message"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
         "agent_id"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3)]
instance (HsJSONPB.FromJSONPB NotifyParentRequest) where
  parseJSONPB
    = HsJSONPB.withObject
        "NotifyParentRequest"
        (\ obj
           -> Hs.pure NotifyParentRequest <*> obj .: "status"
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "message"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "agent_id")))
instance (HsJSONPB.ToJSON NotifyParentRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON NotifyParentRequest) where
  parseJSON = HsJSONPB.parseJSONPB
newtype NotifyParentResponse
  = NotifyParentResponse {notifyParentResponseAck :: Hs.Bool}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData NotifyParentResponse)
instance (HsProtobuf.Named NotifyParentResponse) where
  nameOf _ = Hs.fromString "NotifyParentResponse"
instance (HsProtobuf.HasDefault NotifyParentResponse)
instance (HsProtobuf.Message NotifyParentResponse) where
  encodeMessage _ NotifyParentResponse {notifyParentResponseAck}
    = (HsProtobuf.encodeMessageField
         (HsProtobuf.FieldNumber 1) notifyParentResponseAck)
  decodeMessage _
    = Hs.pure NotifyParentResponse
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1) (HsProtobufAST.Prim HsProtobufAST.Bool)
         (HsProtobufAST.Single "ack") [] ""]
instance (HsJSONPB.ToJSONPB NotifyParentResponse) where
  toJSONPB (NotifyParentResponse f1) = HsJSONPB.object ["ack" .= f1]
  toEncodingPB (NotifyParentResponse f1)
    = HsJSONPB.pairs ["ack" .= f1]
instance (HsJSONPB.FromJSONPB NotifyParentResponse) where
  parseJSONPB
    = HsJSONPB.withObject
        "NotifyParentResponse"
        (\ obj -> Hs.pure NotifyParentResponse <*> obj .: "ack")
instance (HsJSONPB.ToJSON NotifyParentResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON NotifyParentResponse) where
  parseJSON = HsJSONPB.parseJSONPB
