{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE NegativeLiterals #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeOperators #-}
{-# OPTIONS_GHC -fno-warn-missing-export-lists #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-- | Generated by Haskell protocol buffer compiler. DO NOT EDIT!
module Effects.FilePr where
import qualified Prelude as Hs
import qualified Proto3.Suite.Class as HsProtobuf
import qualified Proto3.Suite.DotProto as HsProtobufAST
import qualified Proto3.Suite.JSONPB as HsJSONPB
import Proto3.Suite.JSONPB ( (.=), (.:) )
import qualified Proto3.Suite.Types as HsProtobuf
import qualified Proto3.Wire as HsProtobuf
import qualified Proto3.Wire.Decode as HsProtobuf
    ( Parser, RawField )
import qualified Control.Applicative as Hs
import Control.Applicative ( (<*>), (<|>), (<$>) )
import qualified Control.DeepSeq as Hs
import qualified Control.Monad as Hs
import qualified Data.ByteString as Hs
import qualified Data.Coerce as Hs
import qualified Data.Int as Hs ( Int16, Int32, Int64 )
import qualified Data.List.NonEmpty as Hs ( NonEmpty(..) )
import qualified Data.Map as Hs ( Map, mapKeysMonotonic )
import qualified Data.Proxy as Proxy
import qualified Data.String as Hs ( fromString )
import qualified Data.Text.Lazy as Hs ( Text )
import qualified Data.Vector as Hs ( Vector )
import qualified Data.Word as Hs ( Word16, Word32, Word64 )
import qualified GHC.Enum as Hs
import qualified GHC.Generics as Hs
import qualified Google.Protobuf.Wrappers.Polymorphic as HsProtobuf
    ( Wrapped(..) )
import qualified Unsafe.Coerce as Hs




data FilePrRequest
  = FilePrRequest {filePrRequestTitle :: Hs.Text,
                   filePrRequestBody :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData FilePrRequest)
instance (HsProtobuf.Named FilePrRequest) where
  nameOf _ = Hs.fromString "FilePrRequest"
instance (HsProtobuf.HasDefault FilePrRequest)
instance (HsProtobuf.Message FilePrRequest) where
  encodeMessage
    _
    FilePrRequest {filePrRequestTitle, filePrRequestBody}
    = Hs.mappend
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 1)
           ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              filePrRequestTitle))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 2)
           ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              filePrRequestBody))
  decodeMessage _
    = Hs.pure FilePrRequest
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "title") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "body") [] ""]
instance (HsJSONPB.ToJSONPB FilePrRequest) where
  toJSONPB (FilePrRequest f1 f2)
    = HsJSONPB.object
        ["title" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "body" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)]
  toEncodingPB (FilePrRequest f1 f2)
    = HsJSONPB.pairs
        ["title" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "body" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)]
instance (HsJSONPB.FromJSONPB FilePrRequest) where
  parseJSONPB
    = HsJSONPB.withObject
        "FilePrRequest"
        (\ obj
           -> Hs.pure FilePrRequest
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "title"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "body")))
instance (HsJSONPB.ToJSON FilePrRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON FilePrRequest) where
  parseJSON = HsJSONPB.parseJSONPB
data FilePrResponse
  = FilePrResponse {filePrResponsePrUrl :: Hs.Text,
                    filePrResponsePrNumber :: Hs.Int64,
                    filePrResponseHeadBranch :: Hs.Text,
                    filePrResponseBaseBranch :: Hs.Text,
                    filePrResponseCreated :: Hs.Bool}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData FilePrResponse)
instance (HsProtobuf.Named FilePrResponse) where
  nameOf _ = Hs.fromString "FilePrResponse"
instance (HsProtobuf.HasDefault FilePrResponse)
instance (HsProtobuf.Message FilePrResponse) where
  encodeMessage
    _
    FilePrResponse {filePrResponsePrUrl, filePrResponsePrNumber,
                    filePrResponseHeadBranch, filePrResponseBaseBranch,
                    filePrResponseCreated}
    = Hs.mappend
        (Hs.mappend
           (Hs.mappend
              (Hs.mappend
                 (HsProtobuf.encodeMessageField
                    (HsProtobuf.FieldNumber 1)
                    ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                       filePrResponsePrUrl))
                 (HsProtobuf.encodeMessageField
                    (HsProtobuf.FieldNumber 2) filePrResponsePrNumber))
              (HsProtobuf.encodeMessageField
                 (HsProtobuf.FieldNumber 3)
                 ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                    filePrResponseHeadBranch)))
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 4)
              ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                 filePrResponseBaseBranch)))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 5) filePrResponseCreated)
  decodeMessage _
    = Hs.pure FilePrResponse
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 3)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 4)))
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 5)
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "pr_url") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2) (HsProtobufAST.Prim HsProtobufAST.Int64)
         (HsProtobufAST.Single "pr_number") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 3)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "head_branch") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 4)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "base_branch") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 5) (HsProtobufAST.Prim HsProtobufAST.Bool)
         (HsProtobufAST.Single "created") [] ""]
instance (HsJSONPB.ToJSONPB FilePrResponse) where
  toJSONPB (FilePrResponse f1 f2 f3 f4 f5)
    = HsJSONPB.object
        ["pr_url"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "pr_number" .= f2,
         "head_branch"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3),
         "base_branch"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f4),
         "created" .= f5]
  toEncodingPB (FilePrResponse f1 f2 f3 f4 f5)
    = HsJSONPB.pairs
        ["pr_url"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "pr_number" .= f2,
         "head_branch"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3),
         "base_branch"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f4),
         "created" .= f5]
instance (HsJSONPB.FromJSONPB FilePrResponse) where
  parseJSONPB
    = HsJSONPB.withObject
        "FilePrResponse"
        (\ obj
           -> Hs.pure FilePrResponse
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "pr_url"))
                <*> obj .: "pr_number"
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "head_branch"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "base_branch"))
                <*> obj .: "created")
instance (HsJSONPB.ToJSON FilePrResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON FilePrResponse) where
  parseJSON = HsJSONPB.parseJSONPB
newtype FilePrEffects request response
  = FilePrEffects {filePrEffectsFilePr :: ((((request 'HsGRPC.Normal) Effects.FilePr.FilePrRequest) Effects.FilePr.FilePrResponse)
                                           -> (Hs.IO ((response 'HsGRPC.Normal) Effects.FilePr.FilePrResponse)))}
  deriving (Hs.Generic)
filePrEffectsServer ::
  ((FilePrEffects HsGRPC.ServerRequest) HsGRPC.ServerResponse)
  -> HsGRPC.ServiceOptions -> (Hs.IO ())
filePrEffectsServer
  FilePrEffects {filePrEffectsFilePr}
  (ServiceOptions serverHost serverPort useCompression
                  userAgentPrefix userAgentSuffix initialMetadata sslConfig logger
                  serverMaxReceiveMessageLength serverMaxMetadataSize)
  = HsGRPC.serverLoop
      HsGRPC.defaultOptions
        {HsGRPC.optNormalHandlers = [HsGRPC.UnaryHandler
                                       (HsGRPC.MethodName
                                          "/exomonad.effects.file_pr.FilePrEffects/FilePr")
                                       (HsGRPC.convertGeneratedServerHandler filePrEffectsFilePr)],
         HsGRPC.optClientStreamHandlers = [],
         HsGRPC.optServerStreamHandlers = [],
         HsGRPC.optBiDiStreamHandlers = [], optServerHost = serverHost,
         optServerPort = serverPort, optUseCompression = useCompression,
         optUserAgentPrefix = userAgentPrefix,
         optUserAgentSuffix = userAgentSuffix,
         optInitialMetadata = initialMetadata, optSSLConfig = sslConfig,
         optLogger = logger,
         optMaxReceiveMessageLength = serverMaxReceiveMessageLength,
         optMaxMetadataSize = serverMaxMetadataSize}
filePrEffectsClient ::
  HsGRPC.Client
  -> (Hs.IO ((FilePrEffects HsGRPC.ClientRequest) HsGRPC.ClientResult))
filePrEffectsClient client
  = Hs.pure FilePrEffects
      <*>
        (Hs.pure (HsGRPC.clientRequest client)
           <*>
             HsGRPC.clientRegisterMethod
               client
               (HsGRPC.MethodName
                  "/exomonad.effects.file_pr.FilePrEffects/FilePr"))