{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE NegativeLiterals #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeOperators #-}
{-# OPTIONS_GHC -fno-warn-missing-export-lists #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-- | Generated by Haskell protocol buffer compiler. DO NOT EDIT!
module Effects.FilePr where

import Control.Applicative ((<$>), (<*>), (<|>))
import Control.Applicative qualified as Hs
import Control.DeepSeq qualified as Hs
import Control.Monad qualified as Hs
import Data.ByteString qualified as Hs
import Data.Coerce qualified as Hs
import Data.Int qualified as Hs (Int16, Int32, Int64)
import Data.List.NonEmpty qualified as Hs (NonEmpty (..))
import Data.Map qualified as Hs (Map, mapKeysMonotonic)
import Data.Proxy qualified as Proxy
import Data.String qualified as Hs (fromString)
import Data.Text.Lazy qualified as Hs (Text)
import Data.Vector qualified as Hs (Vector)
import Data.Word qualified as Hs (Word16, Word32, Word64)
import GHC.Enum qualified as Hs
import GHC.Generics qualified as Hs
import Google.Protobuf.Wrappers.Polymorphic qualified as HsProtobuf
  ( Wrapped (..),
  )
import Proto3.Suite.Class qualified as HsProtobuf
import Proto3.Suite.DotProto qualified as HsProtobufAST
import Proto3.Suite.JSONPB ((.:), (.=))
import Proto3.Suite.JSONPB qualified as HsJSONPB
import Proto3.Suite.Types qualified as HsProtobuf
import Proto3.Wire qualified as HsProtobuf
import Proto3.Wire.Decode qualified as HsProtobuf
  ( Parser,
    RawField,
  )
import Unsafe.Coerce qualified as Hs
import Prelude qualified as Hs

data FilePrRequest
  = FilePrRequest
  { filePrRequestTitle :: Hs.Text,
    filePrRequestBody :: Hs.Text,
    filePrRequestBaseBranch :: Hs.Text
  }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData FilePrRequest)

instance (HsProtobuf.Named FilePrRequest) where
  nameOf _ = Hs.fromString "FilePrRequest"

instance (HsProtobuf.HasDefault FilePrRequest)

instance (HsProtobuf.Message FilePrRequest) where
  encodeMessage
    _
    FilePrRequest
      { filePrRequestTitle,
        filePrRequestBody,
        filePrRequestBaseBranch
      } =
      Hs.mappend
        ( Hs.mappend
            ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 1)
                ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                    filePrRequestTitle
                )
            )
            ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 2)
                ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                    filePrRequestBody
                )
            )
        )
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 3)
            ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                filePrRequestBaseBranch
            )
        )
  decodeMessage _ =
    Hs.pure FilePrRequest
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 1)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 2)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 3)
              )
          )
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "title")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 2)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "body")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 3)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "base_branch")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB FilePrRequest) where
  toJSONPB (FilePrRequest f1 f2 f3) =
    HsJSONPB.object
      [ "title" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
        "body" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
        "base_branch"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3)
      ]
  toEncodingPB (FilePrRequest f1 f2 f3) =
    HsJSONPB.pairs
      [ "title" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
        "body" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
        "base_branch"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3)
      ]

instance (HsJSONPB.FromJSONPB FilePrRequest) where
  parseJSONPB =
    HsJSONPB.withObject
      "FilePrRequest"
      ( \obj ->
          Hs.pure FilePrRequest
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "title")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "body")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "base_branch")
                )
      )

instance (HsJSONPB.ToJSON FilePrRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON FilePrRequest) where
  parseJSON = HsJSONPB.parseJSONPB

data FilePrResponse
  = FilePrResponse
  { filePrResponsePrUrl :: Hs.Text,
    filePrResponsePrNumber :: Hs.Int64,
    filePrResponseHeadBranch :: Hs.Text,
    filePrResponseBaseBranch :: Hs.Text,
    filePrResponseCreated :: Hs.Bool
  }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData FilePrResponse)

instance (HsProtobuf.Named FilePrResponse) where
  nameOf _ = Hs.fromString "FilePrResponse"

instance (HsProtobuf.HasDefault FilePrResponse)

instance (HsProtobuf.Message FilePrResponse) where
  encodeMessage
    _
    FilePrResponse
      { filePrResponsePrUrl,
        filePrResponsePrNumber,
        filePrResponseHeadBranch,
        filePrResponseBaseBranch,
        filePrResponseCreated
      } =
      Hs.mappend
        ( Hs.mappend
            ( Hs.mappend
                ( Hs.mappend
                    ( HsProtobuf.encodeMessageField
                        (HsProtobuf.FieldNumber 1)
                        ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                            filePrResponsePrUrl
                        )
                    )
                    ( HsProtobuf.encodeMessageField
                        (HsProtobuf.FieldNumber 2)
                        filePrResponsePrNumber
                    )
                )
                ( HsProtobuf.encodeMessageField
                    (HsProtobuf.FieldNumber 3)
                    ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                        filePrResponseHeadBranch
                    )
                )
            )
            ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 4)
                ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                    filePrResponseBaseBranch
                )
            )
        )
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 5)
            filePrResponseCreated
        )
  decodeMessage _ =
    Hs.pure FilePrResponse
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 1)
              )
          )
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 2)
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 3)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 4)
              )
          )
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 5)
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "pr_url")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 2)
        (HsProtobufAST.Prim HsProtobufAST.Int64)
        (HsProtobufAST.Single "pr_number")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 3)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "head_branch")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 4)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "base_branch")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 5)
        (HsProtobufAST.Prim HsProtobufAST.Bool)
        (HsProtobufAST.Single "created")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB FilePrResponse) where
  toJSONPB (FilePrResponse f1 f2 f3 f4 f5) =
    HsJSONPB.object
      [ "pr_url"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
        "pr_number" .= f2,
        "head_branch"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3),
        "base_branch"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f4),
        "created" .= f5
      ]
  toEncodingPB (FilePrResponse f1 f2 f3 f4 f5) =
    HsJSONPB.pairs
      [ "pr_url"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
        "pr_number" .= f2,
        "head_branch"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3),
        "base_branch"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f4),
        "created" .= f5
      ]

instance (HsJSONPB.FromJSONPB FilePrResponse) where
  parseJSONPB =
    HsJSONPB.withObject
      "FilePrResponse"
      ( \obj ->
          Hs.pure FilePrResponse
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "pr_url")
                )
            <*> obj .: "pr_number"
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "head_branch")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "base_branch")
                )
            <*> obj .: "created"
      )

instance (HsJSONPB.ToJSON FilePrResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON FilePrResponse) where
  parseJSON = HsJSONPB.parseJSONPB
