{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE NegativeLiterals #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeOperators #-}
{-# OPTIONS_GHC -fno-warn-missing-export-lists #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-- | Generated by Haskell protocol buffer compiler. DO NOT EDIT!
module Effects.Jj where
import qualified Prelude as Hs
import qualified Proto3.Suite.Class as HsProtobuf
import qualified Proto3.Suite.DotProto as HsProtobufAST
import qualified Proto3.Suite.JSONPB as HsJSONPB
import Proto3.Suite.JSONPB ( (.=), (.:) )
import qualified Proto3.Suite.Types as HsProtobuf
import qualified Proto3.Wire as HsProtobuf
import qualified Proto3.Wire.Decode as HsProtobuf
    ( Parser, RawField )
import qualified Control.Applicative as Hs
import Control.Applicative ( (<*>), (<|>), (<$>) )
import qualified Control.DeepSeq as Hs
import qualified Control.Monad as Hs
import qualified Data.ByteString as Hs
import qualified Data.Coerce as Hs
import qualified Data.Int as Hs ( Int16, Int32, Int64 )
import qualified Data.List.NonEmpty as Hs ( NonEmpty(..) )
import qualified Data.Map as Hs ( Map, mapKeysMonotonic )
import qualified Data.Proxy as Proxy
import qualified Data.String as Hs ( fromString )
import qualified Data.Text.Lazy as Hs ( Text )
import qualified Data.Vector as Hs ( Vector )
import qualified Data.Word as Hs ( Word16, Word32, Word64 )
import qualified GHC.Enum as Hs
import qualified GHC.Generics as Hs
import qualified Google.Protobuf.Wrappers.Polymorphic as HsProtobuf
    ( Wrapped(..) )
import qualified Unsafe.Coerce as Hs




data BookmarkCreateRequest
  = BookmarkCreateRequest {bookmarkCreateRequestName :: Hs.Text,
                           bookmarkCreateRequestRevision :: Hs.Text,
                           bookmarkCreateRequestWorkingDir :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData BookmarkCreateRequest)
instance (HsProtobuf.Named BookmarkCreateRequest) where
  nameOf _ = Hs.fromString "BookmarkCreateRequest"
instance (HsProtobuf.HasDefault BookmarkCreateRequest)
instance (HsProtobuf.Message BookmarkCreateRequest) where
  encodeMessage
    _
    BookmarkCreateRequest {bookmarkCreateRequestName,
                           bookmarkCreateRequestRevision, bookmarkCreateRequestWorkingDir}
    = Hs.mappend
        (Hs.mappend
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 1)
              ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                 bookmarkCreateRequestName))
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 2)
              ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                 bookmarkCreateRequestRevision)))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 3)
           ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              bookmarkCreateRequestWorkingDir))
  decodeMessage _
    = Hs.pure BookmarkCreateRequest
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 3)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "name") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "revision") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 3)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "working_dir") [] ""]
instance (HsJSONPB.ToJSONPB BookmarkCreateRequest) where
  toJSONPB (BookmarkCreateRequest f1 f2 f3)
    = HsJSONPB.object
        ["name" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "revision"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
         "working_dir"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3)]
  toEncodingPB (BookmarkCreateRequest f1 f2 f3)
    = HsJSONPB.pairs
        ["name" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "revision"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
         "working_dir"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3)]
instance (HsJSONPB.FromJSONPB BookmarkCreateRequest) where
  parseJSONPB
    = HsJSONPB.withObject
        "BookmarkCreateRequest"
        (\ obj
           -> Hs.pure BookmarkCreateRequest
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "name"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "revision"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "working_dir")))
instance (HsJSONPB.ToJSON BookmarkCreateRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON BookmarkCreateRequest) where
  parseJSON = HsJSONPB.parseJSONPB
newtype BookmarkCreateResponse
  = BookmarkCreateResponse {bookmarkCreateResponseChangeId :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData BookmarkCreateResponse)
instance (HsProtobuf.Named BookmarkCreateResponse) where
  nameOf _ = Hs.fromString "BookmarkCreateResponse"
instance (HsProtobuf.HasDefault BookmarkCreateResponse)
instance (HsProtobuf.Message BookmarkCreateResponse) where
  encodeMessage
    _
    BookmarkCreateResponse {bookmarkCreateResponseChangeId}
    = (HsProtobuf.encodeMessageField
         (HsProtobuf.FieldNumber 1)
         ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
            bookmarkCreateResponseChangeId))
  decodeMessage _
    = Hs.pure BookmarkCreateResponse
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "change_id") [] ""]
instance (HsJSONPB.ToJSONPB BookmarkCreateResponse) where
  toJSONPB (BookmarkCreateResponse f1)
    = HsJSONPB.object
        ["change_id"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1)]
  toEncodingPB (BookmarkCreateResponse f1)
    = HsJSONPB.pairs
        ["change_id"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1)]
instance (HsJSONPB.FromJSONPB BookmarkCreateResponse) where
  parseJSONPB
    = HsJSONPB.withObject
        "BookmarkCreateResponse"
        (\ obj
           -> Hs.pure BookmarkCreateResponse
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "change_id")))
instance (HsJSONPB.ToJSON BookmarkCreateResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON BookmarkCreateResponse) where
  parseJSON = HsJSONPB.parseJSONPB
data GitPushRequest
  = GitPushRequest {gitPushRequestBookmark :: Hs.Text,
                    gitPushRequestWorkingDir :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData GitPushRequest)
instance (HsProtobuf.Named GitPushRequest) where
  nameOf _ = Hs.fromString "GitPushRequest"
instance (HsProtobuf.HasDefault GitPushRequest)
instance (HsProtobuf.Message GitPushRequest) where
  encodeMessage
    _
    GitPushRequest {gitPushRequestBookmark, gitPushRequestWorkingDir}
    = Hs.mappend
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 1)
           ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              gitPushRequestBookmark))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 2)
           ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              gitPushRequestWorkingDir))
  decodeMessage _
    = Hs.pure GitPushRequest
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "bookmark") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "working_dir") [] ""]
instance (HsJSONPB.ToJSONPB GitPushRequest) where
  toJSONPB (GitPushRequest f1 f2)
    = HsJSONPB.object
        ["bookmark"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "working_dir"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)]
  toEncodingPB (GitPushRequest f1 f2)
    = HsJSONPB.pairs
        ["bookmark"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "working_dir"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)]
instance (HsJSONPB.FromJSONPB GitPushRequest) where
  parseJSONPB
    = HsJSONPB.withObject
        "GitPushRequest"
        (\ obj
           -> Hs.pure GitPushRequest
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "bookmark"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "working_dir")))
instance (HsJSONPB.ToJSON GitPushRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON GitPushRequest) where
  parseJSON = HsJSONPB.parseJSONPB
data GitPushResponse
  = GitPushResponse {gitPushResponseSuccess :: Hs.Bool,
                     gitPushResponseMessage :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData GitPushResponse)
instance (HsProtobuf.Named GitPushResponse) where
  nameOf _ = Hs.fromString "GitPushResponse"
instance (HsProtobuf.HasDefault GitPushResponse)
instance (HsProtobuf.Message GitPushResponse) where
  encodeMessage
    _
    GitPushResponse {gitPushResponseSuccess, gitPushResponseMessage}
    = Hs.mappend
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 1) gitPushResponseSuccess)
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 2)
           ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              gitPushResponseMessage))
  decodeMessage _
    = Hs.pure GitPushResponse
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1) (HsProtobufAST.Prim HsProtobufAST.Bool)
         (HsProtobufAST.Single "success") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "message") [] ""]
instance (HsJSONPB.ToJSONPB GitPushResponse) where
  toJSONPB (GitPushResponse f1 f2)
    = HsJSONPB.object
        ["success" .= f1,
         "message"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)]
  toEncodingPB (GitPushResponse f1 f2)
    = HsJSONPB.pairs
        ["success" .= f1,
         "message"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)]
instance (HsJSONPB.FromJSONPB GitPushResponse) where
  parseJSONPB
    = HsJSONPB.withObject
        "GitPushResponse"
        (\ obj
           -> Hs.pure GitPushResponse <*> obj .: "success"
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "message")))
instance (HsJSONPB.ToJSON GitPushResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON GitPushResponse) where
  parseJSON = HsJSONPB.parseJSONPB
newtype GitFetchRequest
  = GitFetchRequest {gitFetchRequestWorkingDir :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData GitFetchRequest)
instance (HsProtobuf.Named GitFetchRequest) where
  nameOf _ = Hs.fromString "GitFetchRequest"
instance (HsProtobuf.HasDefault GitFetchRequest)
instance (HsProtobuf.Message GitFetchRequest) where
  encodeMessage _ GitFetchRequest {gitFetchRequestWorkingDir}
    = (HsProtobuf.encodeMessageField
         (HsProtobuf.FieldNumber 1)
         ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
            gitFetchRequestWorkingDir))
  decodeMessage _
    = Hs.pure GitFetchRequest
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "working_dir") [] ""]
instance (HsJSONPB.ToJSONPB GitFetchRequest) where
  toJSONPB (GitFetchRequest f1)
    = HsJSONPB.object
        ["working_dir"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1)]
  toEncodingPB (GitFetchRequest f1)
    = HsJSONPB.pairs
        ["working_dir"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1)]
instance (HsJSONPB.FromJSONPB GitFetchRequest) where
  parseJSONPB
    = HsJSONPB.withObject
        "GitFetchRequest"
        (\ obj
           -> Hs.pure GitFetchRequest
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "working_dir")))
instance (HsJSONPB.ToJSON GitFetchRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON GitFetchRequest) where
  parseJSON = HsJSONPB.parseJSONPB
data GitFetchResponse
  = GitFetchResponse {gitFetchResponseSuccess :: Hs.Bool,
                      gitFetchResponseMessage :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData GitFetchResponse)
instance (HsProtobuf.Named GitFetchResponse) where
  nameOf _ = Hs.fromString "GitFetchResponse"
instance (HsProtobuf.HasDefault GitFetchResponse)
instance (HsProtobuf.Message GitFetchResponse) where
  encodeMessage
    _
    GitFetchResponse {gitFetchResponseSuccess, gitFetchResponseMessage}
    = Hs.mappend
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 1) gitFetchResponseSuccess)
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 2)
           ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              gitFetchResponseMessage))
  decodeMessage _
    = Hs.pure GitFetchResponse
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1) (HsProtobufAST.Prim HsProtobufAST.Bool)
         (HsProtobufAST.Single "success") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "message") [] ""]
instance (HsJSONPB.ToJSONPB GitFetchResponse) where
  toJSONPB (GitFetchResponse f1 f2)
    = HsJSONPB.object
        ["success" .= f1,
         "message"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)]
  toEncodingPB (GitFetchResponse f1 f2)
    = HsJSONPB.pairs
        ["success" .= f1,
         "message"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)]
instance (HsJSONPB.FromJSONPB GitFetchResponse) where
  parseJSONPB
    = HsJSONPB.withObject
        "GitFetchResponse"
        (\ obj
           -> Hs.pure GitFetchResponse <*> obj .: "success"
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "message")))
instance (HsJSONPB.ToJSON GitFetchResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON GitFetchResponse) where
  parseJSON = HsJSONPB.parseJSONPB
data LogRequest
  = LogRequest {logRequestRevset :: Hs.Text,
                logRequestWorkingDir :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData LogRequest)
instance (HsProtobuf.Named LogRequest) where
  nameOf _ = Hs.fromString "LogRequest"
instance (HsProtobuf.HasDefault LogRequest)
instance (HsProtobuf.Message LogRequest) where
  encodeMessage _ LogRequest {logRequestRevset, logRequestWorkingDir}
    = Hs.mappend
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 1)
           ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              logRequestRevset))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 2)
           ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              logRequestWorkingDir))
  decodeMessage _
    = Hs.pure LogRequest
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "revset") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "working_dir") [] ""]
instance (HsJSONPB.ToJSONPB LogRequest) where
  toJSONPB (LogRequest f1 f2)
    = HsJSONPB.object
        ["revset"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "working_dir"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)]
  toEncodingPB (LogRequest f1 f2)
    = HsJSONPB.pairs
        ["revset"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "working_dir"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)]
instance (HsJSONPB.FromJSONPB LogRequest) where
  parseJSONPB
    = HsJSONPB.withObject
        "LogRequest"
        (\ obj
           -> Hs.pure LogRequest
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "revset"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "working_dir")))
instance (HsJSONPB.ToJSON LogRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON LogRequest) where
  parseJSON = HsJSONPB.parseJSONPB
data LogEntry
  = LogEntry {logEntryChangeId :: Hs.Text,
              logEntryCommitId :: Hs.Text,
              logEntryDescription :: Hs.Text,
              logEntryAuthor :: Hs.Text,
              logEntryParents :: (Hs.Vector Hs.Text),
              logEntryIsConflicted :: Hs.Bool,
              logEntryIsEmpty :: Hs.Bool}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData LogEntry)
instance (HsProtobuf.Named LogEntry) where
  nameOf _ = Hs.fromString "LogEntry"
instance (HsProtobuf.HasDefault LogEntry)
instance (HsProtobuf.Message LogEntry) where
  encodeMessage
    _
    LogEntry {logEntryChangeId, logEntryCommitId, logEntryDescription,
              logEntryAuthor, logEntryParents, logEntryIsConflicted,
              logEntryIsEmpty}
    = Hs.mappend
        (Hs.mappend
           (Hs.mappend
              (Hs.mappend
                 (Hs.mappend
                    (Hs.mappend
                       (HsProtobuf.encodeMessageField
                          (HsProtobuf.FieldNumber 1)
                          ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                             logEntryChangeId))
                       (HsProtobuf.encodeMessageField
                          (HsProtobuf.FieldNumber 2)
                          ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                             logEntryCommitId)))
                    (HsProtobuf.encodeMessageField
                       (HsProtobuf.FieldNumber 3)
                       ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                          logEntryDescription)))
                 (HsProtobuf.encodeMessageField
                    (HsProtobuf.FieldNumber 4)
                    ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                       logEntryAuthor)))
              (HsProtobuf.encodeMessageField
                 (HsProtobuf.FieldNumber 5)
                 ((Hs.coerce
                     @(Hs.Vector Hs.Text)
                     @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
                    logEntryParents)))
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 6) logEntryIsConflicted))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 7) logEntryIsEmpty)
  decodeMessage _
    = Hs.pure LogEntry
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 3)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 4)))
        <*>
          ((HsProtobuf.coerceOver
              @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
              @(Hs.Vector Hs.Text))
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 5)))
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 6)
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 7)
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "change_id") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "commit_id") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 3)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "description") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 4)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "author") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 5)
         (HsProtobufAST.Repeated HsProtobufAST.String)
         (HsProtobufAST.Single "parents") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 6) (HsProtobufAST.Prim HsProtobufAST.Bool)
         (HsProtobufAST.Single "is_conflicted") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 7) (HsProtobufAST.Prim HsProtobufAST.Bool)
         (HsProtobufAST.Single "is_empty") [] ""]
instance (HsJSONPB.ToJSONPB LogEntry) where
  toJSONPB (LogEntry f1 f2 f3 f4 f5 f6 f7)
    = HsJSONPB.object
        ["change_id"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "commit_id"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
         "description"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3),
         "author" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f4),
         "parents"
           .=
             ((Hs.coerce
                 @(Hs.Vector Hs.Text)
                 @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
                f5),
         "is_conflicted" .= f6, "is_empty" .= f7]
  toEncodingPB (LogEntry f1 f2 f3 f4 f5 f6 f7)
    = HsJSONPB.pairs
        ["change_id"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "commit_id"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
         "description"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3),
         "author" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f4),
         "parents"
           .=
             ((Hs.coerce
                 @(Hs.Vector Hs.Text)
                 @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
                f5),
         "is_conflicted" .= f6, "is_empty" .= f7]
instance (HsJSONPB.FromJSONPB LogEntry) where
  parseJSONPB
    = HsJSONPB.withObject
        "LogEntry"
        (\ obj
           -> Hs.pure LogEntry
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "change_id"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "commit_id"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "description"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "author"))
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
                      @(Hs.Vector Hs.Text))
                     (obj .: "parents"))
                <*> obj .: "is_conflicted"
                <*> obj .: "is_empty")
instance (HsJSONPB.ToJSON LogEntry) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON LogEntry) where
  parseJSON = HsJSONPB.parseJSONPB
newtype LogResponse
  = LogResponse {logResponseEntries :: (Hs.Vector Effects.Jj.LogEntry)}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData LogResponse)
instance (HsProtobuf.Named LogResponse) where
  nameOf _ = Hs.fromString "LogResponse"
instance (HsProtobuf.HasDefault LogResponse)
instance (HsProtobuf.Message LogResponse) where
  encodeMessage _ LogResponse {logResponseEntries}
    = (HsProtobuf.encodeMessageField
         (HsProtobuf.FieldNumber 1)
         ((Hs.coerce
             @(Hs.Vector Effects.Jj.LogEntry)
             @(HsProtobuf.NestedVec Effects.Jj.LogEntry))
            logResponseEntries))
  decodeMessage _
    = Hs.pure LogResponse
        <*>
          ((HsProtobuf.coerceOver
              @(HsProtobuf.NestedVec Effects.Jj.LogEntry)
              @(Hs.Vector Effects.Jj.LogEntry))
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Repeated
            (HsProtobufAST.Named (HsProtobufAST.Single "LogEntry")))
         (HsProtobufAST.Single "entries") [] ""]
instance (HsJSONPB.ToJSONPB LogResponse) where
  toJSONPB (LogResponse f1)
    = HsJSONPB.object
        ["entries"
           .=
             ((Hs.coerce
                 @(Hs.Vector Effects.Jj.LogEntry)
                 @(HsProtobuf.NestedVec Effects.Jj.LogEntry))
                f1)]
  toEncodingPB (LogResponse f1)
    = HsJSONPB.pairs
        ["entries"
           .=
             ((Hs.coerce
                 @(Hs.Vector Effects.Jj.LogEntry)
                 @(HsProtobuf.NestedVec Effects.Jj.LogEntry))
                f1)]
instance (HsJSONPB.FromJSONPB LogResponse) where
  parseJSONPB
    = HsJSONPB.withObject
        "LogResponse"
        (\ obj
           -> Hs.pure LogResponse
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.NestedVec Effects.Jj.LogEntry)
                      @(Hs.Vector Effects.Jj.LogEntry))
                     (obj .: "entries")))
instance (HsJSONPB.ToJSON LogResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON LogResponse) where
  parseJSON = HsJSONPB.parseJSONPB
data NewRequest
  = NewRequest {newRequestRevision :: Hs.Text,
                newRequestWorkingDir :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData NewRequest)
instance (HsProtobuf.Named NewRequest) where
  nameOf _ = Hs.fromString "NewRequest"
instance (HsProtobuf.HasDefault NewRequest)
instance (HsProtobuf.Message NewRequest) where
  encodeMessage
    _
    NewRequest {newRequestRevision, newRequestWorkingDir}
    = Hs.mappend
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 1)
           ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              newRequestRevision))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 2)
           ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              newRequestWorkingDir))
  decodeMessage _
    = Hs.pure NewRequest
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "revision") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "working_dir") [] ""]
instance (HsJSONPB.ToJSONPB NewRequest) where
  toJSONPB (NewRequest f1 f2)
    = HsJSONPB.object
        ["revision"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "working_dir"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)]
  toEncodingPB (NewRequest f1 f2)
    = HsJSONPB.pairs
        ["revision"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "working_dir"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)]
instance (HsJSONPB.FromJSONPB NewRequest) where
  parseJSONPB
    = HsJSONPB.withObject
        "NewRequest"
        (\ obj
           -> Hs.pure NewRequest
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "revision"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "working_dir")))
instance (HsJSONPB.ToJSON NewRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON NewRequest) where
  parseJSON = HsJSONPB.parseJSONPB
newtype NewResponse
  = NewResponse {newResponseChangeId :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData NewResponse)
instance (HsProtobuf.Named NewResponse) where
  nameOf _ = Hs.fromString "NewResponse"
instance (HsProtobuf.HasDefault NewResponse)
instance (HsProtobuf.Message NewResponse) where
  encodeMessage _ NewResponse {newResponseChangeId}
    = (HsProtobuf.encodeMessageField
         (HsProtobuf.FieldNumber 1)
         ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
            newResponseChangeId))
  decodeMessage _
    = Hs.pure NewResponse
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "change_id") [] ""]
instance (HsJSONPB.ToJSONPB NewResponse) where
  toJSONPB (NewResponse f1)
    = HsJSONPB.object
        ["change_id"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1)]
  toEncodingPB (NewResponse f1)
    = HsJSONPB.pairs
        ["change_id"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1)]
instance (HsJSONPB.FromJSONPB NewResponse) where
  parseJSONPB
    = HsJSONPB.withObject
        "NewResponse"
        (\ obj
           -> Hs.pure NewResponse
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "change_id")))
instance (HsJSONPB.ToJSON NewResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON NewResponse) where
  parseJSON = HsJSONPB.parseJSONPB
newtype StatusRequest
  = StatusRequest {statusRequestWorkingDir :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData StatusRequest)
instance (HsProtobuf.Named StatusRequest) where
  nameOf _ = Hs.fromString "StatusRequest"
instance (HsProtobuf.HasDefault StatusRequest)
instance (HsProtobuf.Message StatusRequest) where
  encodeMessage _ StatusRequest {statusRequestWorkingDir}
    = (HsProtobuf.encodeMessageField
         (HsProtobuf.FieldNumber 1)
         ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
            statusRequestWorkingDir))
  decodeMessage _
    = Hs.pure StatusRequest
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "working_dir") [] ""]
instance (HsJSONPB.ToJSONPB StatusRequest) where
  toJSONPB (StatusRequest f1)
    = HsJSONPB.object
        ["working_dir"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1)]
  toEncodingPB (StatusRequest f1)
    = HsJSONPB.pairs
        ["working_dir"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1)]
instance (HsJSONPB.FromJSONPB StatusRequest) where
  parseJSONPB
    = HsJSONPB.withObject
        "StatusRequest"
        (\ obj
           -> Hs.pure StatusRequest
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "working_dir")))
instance (HsJSONPB.ToJSON StatusRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON StatusRequest) where
  parseJSON = HsJSONPB.parseJSONPB
data StatusResponse
  = StatusResponse {statusResponseChangeId :: Hs.Text,
                    statusResponseIsConflicted :: Hs.Bool,
                    statusResponseModifiedFiles :: (Hs.Vector Hs.Text)}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData StatusResponse)
instance (HsProtobuf.Named StatusResponse) where
  nameOf _ = Hs.fromString "StatusResponse"
instance (HsProtobuf.HasDefault StatusResponse)
instance (HsProtobuf.Message StatusResponse) where
  encodeMessage
    _
    StatusResponse {statusResponseChangeId, statusResponseIsConflicted,
                    statusResponseModifiedFiles}
    = Hs.mappend
        (Hs.mappend
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 1)
              ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                 statusResponseChangeId))
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 2) statusResponseIsConflicted))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 3)
           ((Hs.coerce
               @(Hs.Vector Hs.Text)
               @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
              statusResponseModifiedFiles))
  decodeMessage _
    = Hs.pure StatusResponse
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)
        <*>
          ((HsProtobuf.coerceOver
              @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
              @(Hs.Vector Hs.Text))
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 3)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "change_id") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2) (HsProtobufAST.Prim HsProtobufAST.Bool)
         (HsProtobufAST.Single "is_conflicted") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 3)
         (HsProtobufAST.Repeated HsProtobufAST.String)
         (HsProtobufAST.Single "modified_files") [] ""]
instance (HsJSONPB.ToJSONPB StatusResponse) where
  toJSONPB (StatusResponse f1 f2 f3)
    = HsJSONPB.object
        ["change_id"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "is_conflicted" .= f2,
         "modified_files"
           .=
             ((Hs.coerce
                 @(Hs.Vector Hs.Text)
                 @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
                f3)]
  toEncodingPB (StatusResponse f1 f2 f3)
    = HsJSONPB.pairs
        ["change_id"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "is_conflicted" .= f2,
         "modified_files"
           .=
             ((Hs.coerce
                 @(Hs.Vector Hs.Text)
                 @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text)))
                f3)]
instance (HsJSONPB.FromJSONPB StatusResponse) where
  parseJSONPB
    = HsJSONPB.withObject
        "StatusResponse"
        (\ obj
           -> Hs.pure StatusResponse
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "change_id"))
                <*> obj .: "is_conflicted"
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
                      @(Hs.Vector Hs.Text))
                     (obj .: "modified_files")))
instance (HsJSONPB.ToJSON StatusResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON StatusResponse) where
  parseJSON = HsJSONPB.parseJSONPB
