{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE NegativeLiterals #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeOperators #-}
{-# OPTIONS_GHC -fno-warn-missing-export-lists #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-- | Generated by Haskell protocol buffer compiler. DO NOT EDIT!
module Effects.Kv where

import Control.Applicative ((<$>), (<*>), (<|>))
import Control.Applicative qualified as Hs
import Control.DeepSeq qualified as Hs
import Control.Monad qualified as Hs
import Data.ByteString qualified as Hs
import Data.Coerce qualified as Hs
import Data.Int qualified as Hs (Int16, Int32, Int64)
import Data.List.NonEmpty qualified as Hs (NonEmpty (..))
import Data.Map qualified as Hs (Map, mapKeysMonotonic)
import Data.Proxy qualified as Proxy
import Data.String qualified as Hs (fromString)
import Data.Text.Lazy qualified as Hs (Text)
import Data.Vector qualified as Hs (Vector)
import Data.Word qualified as Hs (Word16, Word32, Word64)
import GHC.Enum qualified as Hs
import GHC.Generics qualified as Hs
import Google.Protobuf.Wrappers.Polymorphic qualified as HsProtobuf
  ( Wrapped (..),
  )
import Proto3.Suite.Class qualified as HsProtobuf
import Proto3.Suite.DotProto qualified as HsProtobufAST
import Proto3.Suite.JSONPB ((.:), (.=))
import Proto3.Suite.JSONPB qualified as HsJSONPB
import Proto3.Suite.Types qualified as HsProtobuf
import Proto3.Wire qualified as HsProtobuf
import Proto3.Wire.Decode qualified as HsProtobuf
  ( Parser,
    RawField,
  )
import Unsafe.Coerce qualified as Hs
import Prelude qualified as Hs

newtype GetRequest
  = GetRequest {getRequestKey :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData GetRequest)

instance (HsProtobuf.Named GetRequest) where
  nameOf _ = Hs.fromString "GetRequest"

instance (HsProtobuf.HasDefault GetRequest)

instance (HsProtobuf.Message GetRequest) where
  encodeMessage _ GetRequest {getRequestKey} =
    ( HsProtobuf.encodeMessageField
        (HsProtobuf.FieldNumber 1)
        ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) getRequestKey)
    )
  decodeMessage _ =
    Hs.pure GetRequest
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 1)
              )
          )
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "key")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB GetRequest) where
  toJSONPB (GetRequest f1) =
    HsJSONPB.object
      ["key" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1)]
  toEncodingPB (GetRequest f1) =
    HsJSONPB.pairs
      ["key" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1)]

instance (HsJSONPB.FromJSONPB GetRequest) where
  parseJSONPB =
    HsJSONPB.withObject
      "GetRequest"
      ( \obj ->
          Hs.pure GetRequest
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "key")
                )
      )

instance (HsJSONPB.ToJSON GetRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON GetRequest) where
  parseJSON = HsJSONPB.parseJSONPB

data GetResponse
  = GetResponse
  { getResponseFound :: Hs.Bool,
    getResponseValue :: Hs.Text
  }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData GetResponse)

instance (HsProtobuf.Named GetResponse) where
  nameOf _ = Hs.fromString "GetResponse"

instance (HsProtobuf.HasDefault GetResponse)

instance (HsProtobuf.Message GetResponse) where
  encodeMessage _ GetResponse {getResponseFound, getResponseValue} =
    Hs.mappend
      ( HsProtobuf.encodeMessageField
          (HsProtobuf.FieldNumber 1)
          getResponseFound
      )
      ( HsProtobuf.encodeMessageField
          (HsProtobuf.FieldNumber 2)
          ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              getResponseValue
          )
      )
  decodeMessage _ =
    Hs.pure GetResponse
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 1)
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 2)
              )
          )
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.Bool)
        (HsProtobufAST.Single "found")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 2)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "value")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB GetResponse) where
  toJSONPB (GetResponse f1 f2) =
    HsJSONPB.object
      [ "found" .= f1,
        "value" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)
      ]
  toEncodingPB (GetResponse f1 f2) =
    HsJSONPB.pairs
      [ "found" .= f1,
        "value" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)
      ]

instance (HsJSONPB.FromJSONPB GetResponse) where
  parseJSONPB =
    HsJSONPB.withObject
      "GetResponse"
      ( \obj ->
          Hs.pure GetResponse
            <*> obj .: "found"
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "value")
                )
      )

instance (HsJSONPB.ToJSON GetResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON GetResponse) where
  parseJSON = HsJSONPB.parseJSONPB

data SetRequest
  = SetRequest {setRequestKey :: Hs.Text, setRequestValue :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData SetRequest)

instance (HsProtobuf.Named SetRequest) where
  nameOf _ = Hs.fromString "SetRequest"

instance (HsProtobuf.HasDefault SetRequest)

instance (HsProtobuf.Message SetRequest) where
  encodeMessage _ SetRequest {setRequestKey, setRequestValue} =
    Hs.mappend
      ( HsProtobuf.encodeMessageField
          (HsProtobuf.FieldNumber 1)
          ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) setRequestKey)
      )
      ( HsProtobuf.encodeMessageField
          (HsProtobuf.FieldNumber 2)
          ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              setRequestValue
          )
      )
  decodeMessage _ =
    Hs.pure SetRequest
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 1)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 2)
              )
          )
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "key")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 2)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "value")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB SetRequest) where
  toJSONPB (SetRequest f1 f2) =
    HsJSONPB.object
      [ "key" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
        "value" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)
      ]
  toEncodingPB (SetRequest f1 f2) =
    HsJSONPB.pairs
      [ "key" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
        "value" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)
      ]

instance (HsJSONPB.FromJSONPB SetRequest) where
  parseJSONPB =
    HsJSONPB.withObject
      "SetRequest"
      ( \obj ->
          Hs.pure SetRequest
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "key")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "value")
                )
      )

instance (HsJSONPB.ToJSON SetRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON SetRequest) where
  parseJSON = HsJSONPB.parseJSONPB

newtype SetResponse
  = SetResponse {setResponseSuccess :: Hs.Bool}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData SetResponse)

instance (HsProtobuf.Named SetResponse) where
  nameOf _ = Hs.fromString "SetResponse"

instance (HsProtobuf.HasDefault SetResponse)

instance (HsProtobuf.Message SetResponse) where
  encodeMessage _ SetResponse {setResponseSuccess} =
    ( HsProtobuf.encodeMessageField
        (HsProtobuf.FieldNumber 1)
        setResponseSuccess
    )
  decodeMessage _ =
    Hs.pure SetResponse
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 1)
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.Bool)
        (HsProtobufAST.Single "success")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB SetResponse) where
  toJSONPB (SetResponse f1) = HsJSONPB.object ["success" .= f1]
  toEncodingPB (SetResponse f1) = HsJSONPB.pairs ["success" .= f1]

instance (HsJSONPB.FromJSONPB SetResponse) where
  parseJSONPB =
    HsJSONPB.withObject
      "SetResponse"
      (\obj -> Hs.pure SetResponse <*> obj .: "success")

instance (HsJSONPB.ToJSON SetResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON SetResponse) where
  parseJSON = HsJSONPB.parseJSONPB
