{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE NegativeLiterals #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeOperators #-}
{-# OPTIONS_GHC -fno-warn-missing-export-lists #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-- | Generated by Haskell protocol buffer compiler. DO NOT EDIT!
module Effects.Messaging where
import qualified Prelude as Hs
import qualified Proto3.Suite.Class as HsProtobuf
import qualified Proto3.Suite.DotProto as HsProtobufAST
import qualified Proto3.Suite.JSONPB as HsJSONPB
import Proto3.Suite.JSONPB ( (.=), (.:) )
import qualified Proto3.Suite.Types as HsProtobuf
import qualified Proto3.Wire as HsProtobuf
import qualified Proto3.Wire.Decode as HsProtobuf
    ( Parser, RawField )
import qualified Control.Applicative as Hs
import Control.Applicative ( (<*>), (<|>), (<$>) )
import qualified Control.DeepSeq as Hs
import qualified Control.Monad as Hs
import qualified Data.ByteString as Hs
import qualified Data.Coerce as Hs
import qualified Data.Int as Hs ( Int16, Int32, Int64 )
import qualified Data.List.NonEmpty as Hs ( NonEmpty(..) )
import qualified Data.Map as Hs ( Map, mapKeysMonotonic )
import qualified Data.Proxy as Proxy
import qualified Data.String as Hs ( fromString )
import qualified Data.Text.Lazy as Hs ( Text )
import qualified Data.Vector as Hs ( Vector )
import qualified Data.Word as Hs ( Word16, Word32, Word64 )
import qualified GHC.Enum as Hs
import qualified GHC.Generics as Hs
import qualified Google.Protobuf.Wrappers.Polymorphic as HsProtobuf
    ( Wrapped(..) )
import qualified Unsafe.Coerce as Hs




data SendNoteRequest
  = SendNoteRequest {sendNoteRequestContent :: Hs.Text,
                     sendNoteRequestTeamName :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData SendNoteRequest)
instance (HsProtobuf.Named SendNoteRequest) where
  nameOf _ = Hs.fromString "SendNoteRequest"
instance (HsProtobuf.HasDefault SendNoteRequest)
instance (HsProtobuf.Message SendNoteRequest) where
  encodeMessage
    _
    SendNoteRequest {sendNoteRequestContent, sendNoteRequestTeamName}
    = Hs.mappend
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 1)
           ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              sendNoteRequestContent))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 2)
           ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              sendNoteRequestTeamName))
  decodeMessage _
    = Hs.pure SendNoteRequest
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "content") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "team_name") [] ""]
instance (HsJSONPB.ToJSONPB SendNoteRequest) where
  toJSONPB (SendNoteRequest f1 f2)
    = HsJSONPB.object
        ["content"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "team_name"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)]
  toEncodingPB (SendNoteRequest f1 f2)
    = HsJSONPB.pairs
        ["content"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "team_name"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)]
instance (HsJSONPB.FromJSONPB SendNoteRequest) where
  parseJSONPB
    = HsJSONPB.withObject
        "SendNoteRequest"
        (\ obj
           -> Hs.pure SendNoteRequest
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "content"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "team_name")))
instance (HsJSONPB.ToJSON SendNoteRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON SendNoteRequest) where
  parseJSON = HsJSONPB.parseJSONPB
newtype SendNoteResponse
  = SendNoteResponse {sendNoteResponseAck :: Hs.Bool}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData SendNoteResponse)
instance (HsProtobuf.Named SendNoteResponse) where
  nameOf _ = Hs.fromString "SendNoteResponse"
instance (HsProtobuf.HasDefault SendNoteResponse)
instance (HsProtobuf.Message SendNoteResponse) where
  encodeMessage _ SendNoteResponse {sendNoteResponseAck}
    = (HsProtobuf.encodeMessageField
         (HsProtobuf.FieldNumber 1) sendNoteResponseAck)
  decodeMessage _
    = Hs.pure SendNoteResponse
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1) (HsProtobufAST.Prim HsProtobufAST.Bool)
         (HsProtobufAST.Single "ack") [] ""]
instance (HsJSONPB.ToJSONPB SendNoteResponse) where
  toJSONPB (SendNoteResponse f1) = HsJSONPB.object ["ack" .= f1]
  toEncodingPB (SendNoteResponse f1) = HsJSONPB.pairs ["ack" .= f1]
instance (HsJSONPB.FromJSONPB SendNoteResponse) where
  parseJSONPB
    = HsJSONPB.withObject
        "SendNoteResponse"
        (\ obj -> Hs.pure SendNoteResponse <*> obj .: "ack")
instance (HsJSONPB.ToJSON SendNoteResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON SendNoteResponse) where
  parseJSON = HsJSONPB.parseJSONPB
data SendQuestionRequest
  = SendQuestionRequest {sendQuestionRequestQuestion :: Hs.Text,
                         sendQuestionRequestTeamName :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData SendQuestionRequest)
instance (HsProtobuf.Named SendQuestionRequest) where
  nameOf _ = Hs.fromString "SendQuestionRequest"
instance (HsProtobuf.HasDefault SendQuestionRequest)
instance (HsProtobuf.Message SendQuestionRequest) where
  encodeMessage
    _
    SendQuestionRequest {sendQuestionRequestQuestion,
                         sendQuestionRequestTeamName}
    = Hs.mappend
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 1)
           ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              sendQuestionRequestQuestion))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 3)
           ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              sendQuestionRequestTeamName))
  decodeMessage _
    = Hs.pure SendQuestionRequest
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 3)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "question") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 3)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "team_name") [] ""]
instance (HsJSONPB.ToJSONPB SendQuestionRequest) where
  toJSONPB (SendQuestionRequest f1 f3)
    = HsJSONPB.object
        ["question"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "team_name"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3)]
  toEncodingPB (SendQuestionRequest f1 f3)
    = HsJSONPB.pairs
        ["question"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "team_name"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3)]
instance (HsJSONPB.FromJSONPB SendQuestionRequest) where
  parseJSONPB
    = HsJSONPB.withObject
        "SendQuestionRequest"
        (\ obj
           -> Hs.pure SendQuestionRequest
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "question"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "team_name")))
instance (HsJSONPB.ToJSON SendQuestionRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON SendQuestionRequest) where
  parseJSON = HsJSONPB.parseJSONPB
newtype SendQuestionResponse
  = SendQuestionResponse {sendQuestionResponseAnswer :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData SendQuestionResponse)
instance (HsProtobuf.Named SendQuestionResponse) where
  nameOf _ = Hs.fromString "SendQuestionResponse"
instance (HsProtobuf.HasDefault SendQuestionResponse)
instance (HsProtobuf.Message SendQuestionResponse) where
  encodeMessage _ SendQuestionResponse {sendQuestionResponseAnswer}
    = (HsProtobuf.encodeMessageField
         (HsProtobuf.FieldNumber 1)
         ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
            sendQuestionResponseAnswer))
  decodeMessage _
    = Hs.pure SendQuestionResponse
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "answer") [] ""]
instance (HsJSONPB.ToJSONPB SendQuestionResponse) where
  toJSONPB (SendQuestionResponse f1)
    = HsJSONPB.object
        ["answer"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1)]
  toEncodingPB (SendQuestionResponse f1)
    = HsJSONPB.pairs
        ["answer"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1)]
instance (HsJSONPB.FromJSONPB SendQuestionResponse) where
  parseJSONPB
    = HsJSONPB.withObject
        "SendQuestionResponse"
        (\ obj
           -> Hs.pure SendQuestionResponse
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "answer")))
instance (HsJSONPB.ToJSON SendQuestionResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON SendQuestionResponse) where
  parseJSON = HsJSONPB.parseJSONPB
data GetAgentMessagesRequest
  = GetAgentMessagesRequest {getAgentMessagesRequestAgentId :: Hs.Text,
                             getAgentMessagesRequestTeamName :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData GetAgentMessagesRequest)
instance (HsProtobuf.Named GetAgentMessagesRequest) where
  nameOf _ = Hs.fromString "GetAgentMessagesRequest"
instance (HsProtobuf.HasDefault GetAgentMessagesRequest)
instance (HsProtobuf.Message GetAgentMessagesRequest) where
  encodeMessage
    _
    GetAgentMessagesRequest {getAgentMessagesRequestAgentId,
                             getAgentMessagesRequestTeamName}
    = Hs.mappend
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 1)
           ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              getAgentMessagesRequestAgentId))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 2)
           ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              getAgentMessagesRequestTeamName))
  decodeMessage _
    = Hs.pure GetAgentMessagesRequest
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "agent_id") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "team_name") [] ""]
instance (HsJSONPB.ToJSONPB GetAgentMessagesRequest) where
  toJSONPB (GetAgentMessagesRequest f1 f2)
    = HsJSONPB.object
        ["agent_id"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "team_name"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)]
  toEncodingPB (GetAgentMessagesRequest f1 f2)
    = HsJSONPB.pairs
        ["agent_id"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "team_name"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)]
instance (HsJSONPB.FromJSONPB GetAgentMessagesRequest) where
  parseJSONPB
    = HsJSONPB.withObject
        "GetAgentMessagesRequest"
        (\ obj
           -> Hs.pure GetAgentMessagesRequest
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "agent_id"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "team_name")))
instance (HsJSONPB.ToJSON GetAgentMessagesRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON GetAgentMessagesRequest) where
  parseJSON = HsJSONPB.parseJSONPB
data AgentMessage
  = AgentMessage {agentMessageFrom :: Hs.Text,
                  agentMessageText :: Hs.Text,
                  agentMessageSummary :: Hs.Text,
                  agentMessageTimestamp :: Hs.Text,
                  agentMessageRead :: Hs.Bool}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData AgentMessage)
instance (HsProtobuf.Named AgentMessage) where
  nameOf _ = Hs.fromString "AgentMessage"
instance (HsProtobuf.HasDefault AgentMessage)
instance (HsProtobuf.Message AgentMessage) where
  encodeMessage
    _
    AgentMessage {agentMessageFrom, agentMessageText,
                  agentMessageSummary, agentMessageTimestamp, agentMessageRead}
    = Hs.mappend
        (Hs.mappend
           (Hs.mappend
              (Hs.mappend
                 (HsProtobuf.encodeMessageField
                    (HsProtobuf.FieldNumber 1)
                    ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                       agentMessageFrom))
                 (HsProtobuf.encodeMessageField
                    (HsProtobuf.FieldNumber 2)
                    ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                       agentMessageText)))
              (HsProtobuf.encodeMessageField
                 (HsProtobuf.FieldNumber 3)
                 ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                    agentMessageSummary)))
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 4)
              ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                 agentMessageTimestamp)))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 5) agentMessageRead)
  decodeMessage _
    = Hs.pure AgentMessage
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 3)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 4)))
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 5)
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "from") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "text") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 3)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "summary") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 4)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "timestamp") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 5) (HsProtobufAST.Prim HsProtobufAST.Bool)
         (HsProtobufAST.Single "read") [] ""]
instance (HsJSONPB.ToJSONPB AgentMessage) where
  toJSONPB (AgentMessage f1 f2 f3 f4 f5)
    = HsJSONPB.object
        ["from" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "text" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
         "summary"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3),
         "timestamp"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f4),
         "read" .= f5]
  toEncodingPB (AgentMessage f1 f2 f3 f4 f5)
    = HsJSONPB.pairs
        ["from" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "text" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
         "summary"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3),
         "timestamp"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f4),
         "read" .= f5]
instance (HsJSONPB.FromJSONPB AgentMessage) where
  parseJSONPB
    = HsJSONPB.withObject
        "AgentMessage"
        (\ obj
           -> Hs.pure AgentMessage
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "from"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "text"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "summary"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "timestamp"))
                <*> obj .: "read")
instance (HsJSONPB.ToJSON AgentMessage) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON AgentMessage) where
  parseJSON = HsJSONPB.parseJSONPB
data AgentMessages
  = AgentMessages {agentMessagesAgentId :: Hs.Text,
                   agentMessagesMessages :: (Hs.Vector Effects.Messaging.AgentMessage)}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData AgentMessages)
instance (HsProtobuf.Named AgentMessages) where
  nameOf _ = Hs.fromString "AgentMessages"
instance (HsProtobuf.HasDefault AgentMessages)
instance (HsProtobuf.Message AgentMessages) where
  encodeMessage
    _
    AgentMessages {agentMessagesAgentId, agentMessagesMessages}
    = Hs.mappend
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 1)
           ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              agentMessagesAgentId))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 2)
           ((Hs.coerce
               @(Hs.Vector Effects.Messaging.AgentMessage)
               @(HsProtobuf.NestedVec Effects.Messaging.AgentMessage))
              agentMessagesMessages))
  decodeMessage _
    = Hs.pure AgentMessages
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          ((HsProtobuf.coerceOver
              @(HsProtobuf.NestedVec Effects.Messaging.AgentMessage)
              @(Hs.Vector Effects.Messaging.AgentMessage))
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "agent_id") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2)
         (HsProtobufAST.Repeated
            (HsProtobufAST.Named (HsProtobufAST.Single "AgentMessage")))
         (HsProtobufAST.Single "messages") [] ""]
instance (HsJSONPB.ToJSONPB AgentMessages) where
  toJSONPB (AgentMessages f1 f2)
    = HsJSONPB.object
        ["agent_id"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "messages"
           .=
             ((Hs.coerce
                 @(Hs.Vector Effects.Messaging.AgentMessage)
                 @(HsProtobuf.NestedVec Effects.Messaging.AgentMessage))
                f2)]
  toEncodingPB (AgentMessages f1 f2)
    = HsJSONPB.pairs
        ["agent_id"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "messages"
           .=
             ((Hs.coerce
                 @(Hs.Vector Effects.Messaging.AgentMessage)
                 @(HsProtobuf.NestedVec Effects.Messaging.AgentMessage))
                f2)]
instance (HsJSONPB.FromJSONPB AgentMessages) where
  parseJSONPB
    = HsJSONPB.withObject
        "AgentMessages"
        (\ obj
           -> Hs.pure AgentMessages
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "agent_id"))
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.NestedVec Effects.Messaging.AgentMessage)
                      @(Hs.Vector Effects.Messaging.AgentMessage))
                     (obj .: "messages")))
instance (HsJSONPB.ToJSON AgentMessages) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON AgentMessages) where
  parseJSON = HsJSONPB.parseJSONPB
data GetAgentMessagesResponse
  = GetAgentMessagesResponse {getAgentMessagesResponseAgents :: (Hs.Vector Effects.Messaging.AgentMessages),
                              getAgentMessagesResponseWarning :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData GetAgentMessagesResponse)
instance (HsProtobuf.Named GetAgentMessagesResponse) where
  nameOf _ = Hs.fromString "GetAgentMessagesResponse"
instance (HsProtobuf.HasDefault GetAgentMessagesResponse)
instance (HsProtobuf.Message GetAgentMessagesResponse) where
  encodeMessage
    _
    GetAgentMessagesResponse {getAgentMessagesResponseAgents,
                              getAgentMessagesResponseWarning}
    = Hs.mappend
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 1)
           ((Hs.coerce
               @(Hs.Vector Effects.Messaging.AgentMessages)
               @(HsProtobuf.NestedVec Effects.Messaging.AgentMessages))
              getAgentMessagesResponseAgents))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 2)
           ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              getAgentMessagesResponseWarning))
  decodeMessage _
    = Hs.pure GetAgentMessagesResponse
        <*>
          ((HsProtobuf.coerceOver
              @(HsProtobuf.NestedVec Effects.Messaging.AgentMessages)
              @(Hs.Vector Effects.Messaging.AgentMessages))
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Repeated
            (HsProtobufAST.Named (HsProtobufAST.Single "AgentMessages")))
         (HsProtobufAST.Single "agents") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "warning") [] ""]
instance (HsJSONPB.ToJSONPB GetAgentMessagesResponse) where
  toJSONPB (GetAgentMessagesResponse f1 f2)
    = HsJSONPB.object
        ["agents"
           .=
             ((Hs.coerce
                 @(Hs.Vector Effects.Messaging.AgentMessages)
                 @(HsProtobuf.NestedVec Effects.Messaging.AgentMessages))
                f1),
         "warning"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)]
  toEncodingPB (GetAgentMessagesResponse f1 f2)
    = HsJSONPB.pairs
        ["agents"
           .=
             ((Hs.coerce
                 @(Hs.Vector Effects.Messaging.AgentMessages)
                 @(HsProtobuf.NestedVec Effects.Messaging.AgentMessages))
                f1),
         "warning"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)]
instance (HsJSONPB.FromJSONPB GetAgentMessagesResponse) where
  parseJSONPB
    = HsJSONPB.withObject
        "GetAgentMessagesResponse"
        (\ obj
           -> Hs.pure GetAgentMessagesResponse
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.NestedVec Effects.Messaging.AgentMessages)
                      @(Hs.Vector Effects.Messaging.AgentMessages))
                     (obj .: "agents"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "warning")))
instance (HsJSONPB.ToJSON GetAgentMessagesResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON GetAgentMessagesResponse) where
  parseJSON = HsJSONPB.parseJSONPB
data AnswerQuestionRequest
  = AnswerQuestionRequest {answerQuestionRequestAgentId :: Hs.Text,
                           answerQuestionRequestQuestionId :: Hs.Text,
                           answerQuestionRequestAnswer :: Hs.Text,
                           answerQuestionRequestTeamName :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData AnswerQuestionRequest)
instance (HsProtobuf.Named AnswerQuestionRequest) where
  nameOf _ = Hs.fromString "AnswerQuestionRequest"
instance (HsProtobuf.HasDefault AnswerQuestionRequest)
instance (HsProtobuf.Message AnswerQuestionRequest) where
  encodeMessage
    _
    AnswerQuestionRequest {answerQuestionRequestAgentId,
                           answerQuestionRequestQuestionId, answerQuestionRequestAnswer,
                           answerQuestionRequestTeamName}
    = Hs.mappend
        (Hs.mappend
           (Hs.mappend
              (HsProtobuf.encodeMessageField
                 (HsProtobuf.FieldNumber 1)
                 ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                    answerQuestionRequestAgentId))
              (HsProtobuf.encodeMessageField
                 (HsProtobuf.FieldNumber 2)
                 ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                    answerQuestionRequestQuestionId)))
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 3)
              ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                 answerQuestionRequestAnswer)))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 4)
           ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              answerQuestionRequestTeamName))
  decodeMessage _
    = Hs.pure AnswerQuestionRequest
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 3)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 4)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "agent_id") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "question_id") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 3)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "answer") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 4)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "team_name") [] ""]
instance (HsJSONPB.ToJSONPB AnswerQuestionRequest) where
  toJSONPB (AnswerQuestionRequest f1 f2 f3 f4)
    = HsJSONPB.object
        ["agent_id"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "question_id"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
         "answer" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3),
         "team_name"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f4)]
  toEncodingPB (AnswerQuestionRequest f1 f2 f3 f4)
    = HsJSONPB.pairs
        ["agent_id"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "question_id"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
         "answer" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3),
         "team_name"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f4)]
instance (HsJSONPB.FromJSONPB AnswerQuestionRequest) where
  parseJSONPB
    = HsJSONPB.withObject
        "AnswerQuestionRequest"
        (\ obj
           -> Hs.pure AnswerQuestionRequest
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "agent_id"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "question_id"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "answer"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "team_name")))
instance (HsJSONPB.ToJSON AnswerQuestionRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON AnswerQuestionRequest) where
  parseJSON = HsJSONPB.parseJSONPB
data AnswerQuestionResponse
  = AnswerQuestionResponse {answerQuestionResponseStatus :: Hs.Text,
                            answerQuestionResponseAgentId :: Hs.Text,
                            answerQuestionResponseQuestionId :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData AnswerQuestionResponse)
instance (HsProtobuf.Named AnswerQuestionResponse) where
  nameOf _ = Hs.fromString "AnswerQuestionResponse"
instance (HsProtobuf.HasDefault AnswerQuestionResponse)
instance (HsProtobuf.Message AnswerQuestionResponse) where
  encodeMessage
    _
    AnswerQuestionResponse {answerQuestionResponseStatus,
                            answerQuestionResponseAgentId, answerQuestionResponseQuestionId}
    = Hs.mappend
        (Hs.mappend
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 1)
              ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                 answerQuestionResponseStatus))
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 2)
              ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                 answerQuestionResponseAgentId)))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 3)
           ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              answerQuestionResponseQuestionId))
  decodeMessage _
    = Hs.pure AnswerQuestionResponse
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 3)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "status") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "agent_id") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 3)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "question_id") [] ""]
instance (HsJSONPB.ToJSONPB AnswerQuestionResponse) where
  toJSONPB (AnswerQuestionResponse f1 f2 f3)
    = HsJSONPB.object
        ["status"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "agent_id"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
         "question_id"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3)]
  toEncodingPB (AnswerQuestionResponse f1 f2 f3)
    = HsJSONPB.pairs
        ["status"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "agent_id"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
         "question_id"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3)]
instance (HsJSONPB.FromJSONPB AnswerQuestionResponse) where
  parseJSONPB
    = HsJSONPB.withObject
        "AnswerQuestionResponse"
        (\ obj
           -> Hs.pure AnswerQuestionResponse
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "status"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "agent_id"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "question_id")))
instance (HsJSONPB.ToJSON AnswerQuestionResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON AnswerQuestionResponse) where
  parseJSON = HsJSONPB.parseJSONPB
