{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE NegativeLiterals #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeOperators #-}
{-# OPTIONS_GHC -fno-warn-missing-export-lists #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-- | Generated by Haskell protocol buffer compiler. DO NOT EDIT!
module Effects.Popup where
import qualified Prelude as Hs
import qualified Proto3.Suite.Class as HsProtobuf
import qualified Proto3.Suite.DotProto as HsProtobufAST
import qualified Proto3.Suite.JSONPB as HsJSONPB
import Proto3.Suite.JSONPB ( (.=), (.:) )
import qualified Proto3.Suite.Types as HsProtobuf
import qualified Proto3.Wire as HsProtobuf
import qualified Proto3.Wire.Decode as HsProtobuf
    ( Parser, RawField )
import qualified Control.Applicative as Hs
import Control.Applicative ( (<*>), (<|>), (<$>) )
import qualified Control.DeepSeq as Hs
import qualified Control.Monad as Hs
import qualified Data.ByteString as Hs
import qualified Data.Coerce as Hs
import qualified Data.Int as Hs ( Int16, Int32, Int64 )
import qualified Data.List.NonEmpty as Hs ( NonEmpty(..) )
import qualified Data.Map as Hs ( Map, mapKeysMonotonic )
import qualified Data.Proxy as Proxy
import qualified Data.String as Hs ( fromString )
import qualified Data.Text.Lazy as Hs ( Text )
import qualified Data.Vector as Hs ( Vector )
import qualified Data.Word as Hs ( Word16, Word32, Word64 )
import qualified GHC.Enum as Hs
import qualified GHC.Generics as Hs
import qualified Google.Protobuf.Wrappers.Polymorphic as HsProtobuf
    ( Wrapped(..) )
import qualified Unsafe.Coerce as Hs




data ShowPopupRequest
  = ShowPopupRequest {showPopupRequestTitle :: Hs.Text,
                      showPopupRequestComponents :: Hs.ByteString}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData ShowPopupRequest)
instance (HsProtobuf.Named ShowPopupRequest) where
  nameOf _ = Hs.fromString "ShowPopupRequest"
instance (HsProtobuf.HasDefault ShowPopupRequest)
instance (HsProtobuf.Message ShowPopupRequest) where
  encodeMessage
    _
    ShowPopupRequest {showPopupRequestTitle,
                      showPopupRequestComponents}
    = Hs.mappend
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 1)
           ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              showPopupRequestTitle))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 2)
           ((Hs.coerce @Hs.ByteString @(HsProtobuf.Bytes Hs.ByteString))
              showPopupRequestComponents))
  decodeMessage _
    = Hs.pure ShowPopupRequest
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          ((HsProtobuf.coerceOver
              @(HsProtobuf.Bytes Hs.ByteString) @Hs.ByteString)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "title") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2) (HsProtobufAST.Prim HsProtobufAST.Bytes)
         (HsProtobufAST.Single "components") [] ""]
instance (HsJSONPB.ToJSONPB ShowPopupRequest) where
  toJSONPB (ShowPopupRequest f1 f2)
    = HsJSONPB.object
        ["title" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "components"
           .=
             ((Hs.coerce @Hs.ByteString @(HsProtobuf.Bytes Hs.ByteString)) f2)]
  toEncodingPB (ShowPopupRequest f1 f2)
    = HsJSONPB.pairs
        ["title" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "components"
           .=
             ((Hs.coerce @Hs.ByteString @(HsProtobuf.Bytes Hs.ByteString)) f2)]
instance (HsJSONPB.FromJSONPB ShowPopupRequest) where
  parseJSONPB
    = HsJSONPB.withObject
        "ShowPopupRequest"
        (\ obj
           -> Hs.pure ShowPopupRequest
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "title"))
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.Bytes Hs.ByteString) @Hs.ByteString)
                     (obj .: "components")))
instance (HsJSONPB.ToJSON ShowPopupRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON ShowPopupRequest) where
  parseJSON = HsJSONPB.parseJSONPB
data ShowPopupResponse
  = ShowPopupResponse {showPopupResponseButton :: Hs.Text,
                       showPopupResponseValues :: Hs.ByteString}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData ShowPopupResponse)
instance (HsProtobuf.Named ShowPopupResponse) where
  nameOf _ = Hs.fromString "ShowPopupResponse"
instance (HsProtobuf.HasDefault ShowPopupResponse)
instance (HsProtobuf.Message ShowPopupResponse) where
  encodeMessage
    _
    ShowPopupResponse {showPopupResponseButton,
                       showPopupResponseValues}
    = Hs.mappend
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 1)
           ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              showPopupResponseButton))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 2)
           ((Hs.coerce @Hs.ByteString @(HsProtobuf.Bytes Hs.ByteString))
              showPopupResponseValues))
  decodeMessage _
    = Hs.pure ShowPopupResponse
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          ((HsProtobuf.coerceOver
              @(HsProtobuf.Bytes Hs.ByteString) @Hs.ByteString)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "button") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2) (HsProtobufAST.Prim HsProtobufAST.Bytes)
         (HsProtobufAST.Single "values") [] ""]
instance (HsJSONPB.ToJSONPB ShowPopupResponse) where
  toJSONPB (ShowPopupResponse f1 f2)
    = HsJSONPB.object
        ["button"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "values"
           .=
             ((Hs.coerce @Hs.ByteString @(HsProtobuf.Bytes Hs.ByteString)) f2)]
  toEncodingPB (ShowPopupResponse f1 f2)
    = HsJSONPB.pairs
        ["button"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "values"
           .=
             ((Hs.coerce @Hs.ByteString @(HsProtobuf.Bytes Hs.ByteString)) f2)]
instance (HsJSONPB.FromJSONPB ShowPopupResponse) where
  parseJSONPB
    = HsJSONPB.withObject
        "ShowPopupResponse"
        (\ obj
           -> Hs.pure ShowPopupResponse
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "button"))
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.Bytes Hs.ByteString) @Hs.ByteString)
                     (obj .: "values")))
instance (HsJSONPB.ToJSON ShowPopupResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON ShowPopupResponse) where
  parseJSON = HsJSONPB.parseJSONPB
