{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE NegativeLiterals #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeOperators #-}
{-# OPTIONS_GHC -fno-warn-missing-export-lists #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-- | Generated by Haskell protocol buffer compiler. DO NOT EDIT!
module Effects.Session where

import Control.Applicative ((<$>), (<*>), (<|>))
import Control.Applicative qualified as Hs
import Control.DeepSeq qualified as Hs
import Control.Monad qualified as Hs
import Data.ByteString qualified as Hs
import Data.Coerce qualified as Hs
import Data.Int qualified as Hs (Int16, Int32, Int64)
import Data.List.NonEmpty qualified as Hs (NonEmpty (..))
import Data.Map qualified as Hs (Map, mapKeysMonotonic)
import Data.Proxy qualified as Proxy
import Data.String qualified as Hs (fromString)
import Data.Text.Lazy qualified as Hs (Text)
import Data.Vector qualified as Hs (Vector)
import Data.Word qualified as Hs (Word16, Word32, Word64)
import GHC.Enum qualified as Hs
import GHC.Generics qualified as Hs
import Google.Protobuf.Wrappers.Polymorphic qualified as HsProtobuf
  ( Wrapped (..),
  )
import Proto3.Suite.Class qualified as HsProtobuf
import Proto3.Suite.DotProto qualified as HsProtobufAST
import Proto3.Suite.JSONPB ((.:), (.=))
import Proto3.Suite.JSONPB qualified as HsJSONPB
import Proto3.Suite.Types qualified as HsProtobuf
import Proto3.Wire qualified as HsProtobuf
import Proto3.Wire.Decode qualified as HsProtobuf
  ( Parser,
    RawField,
  )
import Unsafe.Coerce qualified as Hs
import Prelude qualified as Hs

newtype RegisterClaudeSessionRequest
  = RegisterClaudeSessionRequest {registerClaudeSessionRequestClaudeSessionId :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData RegisterClaudeSessionRequest)

instance (HsProtobuf.Named RegisterClaudeSessionRequest) where
  nameOf _ = Hs.fromString "RegisterClaudeSessionRequest"

instance (HsProtobuf.HasDefault RegisterClaudeSessionRequest)

instance (HsProtobuf.Message RegisterClaudeSessionRequest) where
  encodeMessage
    _
    RegisterClaudeSessionRequest {registerClaudeSessionRequestClaudeSessionId} =
      ( HsProtobuf.encodeMessageField
          (HsProtobuf.FieldNumber 1)
          ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              registerClaudeSessionRequestClaudeSessionId
          )
      )
  decodeMessage _ =
    Hs.pure RegisterClaudeSessionRequest
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 1)
              )
          )
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "claude_session_id")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB RegisterClaudeSessionRequest) where
  toJSONPB (RegisterClaudeSessionRequest f1) =
    HsJSONPB.object
      [ "claude_session_id"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1)
      ]
  toEncodingPB (RegisterClaudeSessionRequest f1) =
    HsJSONPB.pairs
      [ "claude_session_id"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1)
      ]

instance (HsJSONPB.FromJSONPB RegisterClaudeSessionRequest) where
  parseJSONPB =
    HsJSONPB.withObject
      "RegisterClaudeSessionRequest"
      ( \obj ->
          Hs.pure RegisterClaudeSessionRequest
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "claude_session_id")
                )
      )

instance (HsJSONPB.ToJSON RegisterClaudeSessionRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON RegisterClaudeSessionRequest) where
  parseJSON = HsJSONPB.parseJSONPB

newtype RegisterClaudeSessionResponse
  = RegisterClaudeSessionResponse {registerClaudeSessionResponseSuccess :: Hs.Bool}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData RegisterClaudeSessionResponse)

instance (HsProtobuf.Named RegisterClaudeSessionResponse) where
  nameOf _ = Hs.fromString "RegisterClaudeSessionResponse"

instance (HsProtobuf.HasDefault RegisterClaudeSessionResponse)

instance (HsProtobuf.Message RegisterClaudeSessionResponse) where
  encodeMessage
    _
    RegisterClaudeSessionResponse {registerClaudeSessionResponseSuccess} =
      ( HsProtobuf.encodeMessageField
          (HsProtobuf.FieldNumber 1)
          registerClaudeSessionResponseSuccess
      )
  decodeMessage _ =
    Hs.pure RegisterClaudeSessionResponse
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 1)
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.Bool)
        (HsProtobufAST.Single "success")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB RegisterClaudeSessionResponse) where
  toJSONPB (RegisterClaudeSessionResponse f1) =
    HsJSONPB.object ["success" .= f1]
  toEncodingPB (RegisterClaudeSessionResponse f1) =
    HsJSONPB.pairs ["success" .= f1]

instance (HsJSONPB.FromJSONPB RegisterClaudeSessionResponse) where
  parseJSONPB =
    HsJSONPB.withObject
      "RegisterClaudeSessionResponse"
      ( \obj ->
          Hs.pure RegisterClaudeSessionResponse <*> obj .: "success"
      )

instance (HsJSONPB.ToJSON RegisterClaudeSessionResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON RegisterClaudeSessionResponse) where
  parseJSON = HsJSONPB.parseJSONPB
