{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE NegativeLiterals #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeOperators #-}
{-# OPTIONS_GHC -fno-warn-missing-export-lists #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-- | Generated by Haskell protocol buffer compiler. DO NOT EDIT!
module Effects.Session where
import qualified Prelude as Hs
import qualified Proto3.Suite.Class as HsProtobuf
import qualified Proto3.Suite.DotProto as HsProtobufAST
import qualified Proto3.Suite.JSONPB as HsJSONPB
import Proto3.Suite.JSONPB ( (.=), (.:) )
import qualified Proto3.Suite.Types as HsProtobuf
import qualified Proto3.Wire as HsProtobuf
import qualified Proto3.Wire.Decode as HsProtobuf
    ( Parser, RawField )
import qualified Control.Applicative as Hs
import Control.Applicative ( (<*>), (<|>), (<$>) )
import qualified Control.DeepSeq as Hs
import qualified Control.Monad as Hs
import qualified Data.ByteString as Hs
import qualified Data.Coerce as Hs
import qualified Data.Int as Hs ( Int16, Int32, Int64 )
import qualified Data.List.NonEmpty as Hs ( NonEmpty(..) )
import qualified Data.Map as Hs ( Map, mapKeysMonotonic )
import qualified Data.Proxy as Proxy
import qualified Data.String as Hs ( fromString )
import qualified Data.Text.Lazy as Hs ( Text )
import qualified Data.Vector as Hs ( Vector )
import qualified Data.Word as Hs ( Word16, Word32, Word64 )
import qualified GHC.Enum as Hs
import qualified GHC.Generics as Hs
import qualified Google.Protobuf.Wrappers.Polymorphic as HsProtobuf
    ( Wrapped(..) )
import qualified Unsafe.Coerce as Hs




newtype RegisterClaudeSessionRequest
  = RegisterClaudeSessionRequest {registerClaudeSessionRequestClaudeSessionId :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData RegisterClaudeSessionRequest)
instance (HsProtobuf.Named RegisterClaudeSessionRequest) where
  nameOf _ = Hs.fromString "RegisterClaudeSessionRequest"
instance (HsProtobuf.HasDefault RegisterClaudeSessionRequest)
instance (HsProtobuf.Message RegisterClaudeSessionRequest) where
  encodeMessage
    _
    RegisterClaudeSessionRequest {registerClaudeSessionRequestClaudeSessionId}
    = (HsProtobuf.encodeMessageField
         (HsProtobuf.FieldNumber 1)
         ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
            registerClaudeSessionRequestClaudeSessionId))
  decodeMessage _
    = Hs.pure RegisterClaudeSessionRequest
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "claude_session_id") [] ""]
instance (HsJSONPB.ToJSONPB RegisterClaudeSessionRequest) where
  toJSONPB (RegisterClaudeSessionRequest f1)
    = HsJSONPB.object
        ["claude_session_id"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1)]
  toEncodingPB (RegisterClaudeSessionRequest f1)
    = HsJSONPB.pairs
        ["claude_session_id"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1)]
instance (HsJSONPB.FromJSONPB RegisterClaudeSessionRequest) where
  parseJSONPB
    = HsJSONPB.withObject
        "RegisterClaudeSessionRequest"
        (\ obj
           -> Hs.pure RegisterClaudeSessionRequest
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "claude_session_id")))
instance (HsJSONPB.ToJSON RegisterClaudeSessionRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON RegisterClaudeSessionRequest) where
  parseJSON = HsJSONPB.parseJSONPB
newtype RegisterClaudeSessionResponse
  = RegisterClaudeSessionResponse {registerClaudeSessionResponseSuccess :: Hs.Bool}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData RegisterClaudeSessionResponse)
instance (HsProtobuf.Named RegisterClaudeSessionResponse) where
  nameOf _ = Hs.fromString "RegisterClaudeSessionResponse"
instance (HsProtobuf.HasDefault RegisterClaudeSessionResponse)
instance (HsProtobuf.Message RegisterClaudeSessionResponse) where
  encodeMessage
    _
    RegisterClaudeSessionResponse {registerClaudeSessionResponseSuccess}
    = (HsProtobuf.encodeMessageField
         (HsProtobuf.FieldNumber 1) registerClaudeSessionResponseSuccess)
  decodeMessage _
    = Hs.pure RegisterClaudeSessionResponse
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1) (HsProtobufAST.Prim HsProtobufAST.Bool)
         (HsProtobufAST.Single "success") [] ""]
instance (HsJSONPB.ToJSONPB RegisterClaudeSessionResponse) where
  toJSONPB (RegisterClaudeSessionResponse f1)
    = HsJSONPB.object ["success" .= f1]
  toEncodingPB (RegisterClaudeSessionResponse f1)
    = HsJSONPB.pairs ["success" .= f1]
instance (HsJSONPB.FromJSONPB RegisterClaudeSessionResponse) where
  parseJSONPB
    = HsJSONPB.withObject
        "RegisterClaudeSessionResponse"
        (\ obj
           -> Hs.pure RegisterClaudeSessionResponse <*> obj .: "success")
instance (HsJSONPB.ToJSON RegisterClaudeSessionResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON RegisterClaudeSessionResponse) where
  parseJSON = HsJSONPB.parseJSONPB
