{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE NegativeLiterals #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeOperators #-}
{-# OPTIONS_GHC -fno-warn-missing-export-lists #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-- | Generated by Haskell protocol buffer compiler. DO NOT EDIT!
module ExoMonad.Common where
import qualified Prelude as Hs
import qualified Proto3.Suite.Class as HsProtobuf
import qualified Proto3.Suite.DotProto as HsProtobufAST
import qualified Proto3.Suite.JSONPB as HsJSONPB
import Proto3.Suite.JSONPB ( (.=), (.:) )
import qualified Proto3.Suite.Types as HsProtobuf
import qualified Proto3.Wire as HsProtobuf
import qualified Proto3.Wire.Decode as HsProtobuf
    ( Parser, RawField )
import qualified Control.Applicative as Hs
import Control.Applicative ( (<*>), (<|>), (<$>) )
import qualified Control.DeepSeq as Hs
import qualified Control.Monad as Hs
import qualified Data.ByteString as Hs
import qualified Data.Coerce as Hs
import qualified Data.Int as Hs ( Int16, Int32, Int64 )
import qualified Data.List.NonEmpty as Hs ( NonEmpty(..) )
import qualified Data.Map as Hs ( Map, mapKeysMonotonic )
import qualified Data.Proxy as Proxy
import qualified Data.String as Hs ( fromString )
import qualified Data.Text.Lazy as Hs ( Text )
import qualified Data.Vector as Hs ( Vector )
import qualified Data.Word as Hs ( Word16, Word32, Word64 )
import qualified GHC.Enum as Hs
import qualified GHC.Generics as Hs
import qualified Google.Protobuf.Wrappers.Polymorphic as HsProtobuf
    ( Wrapped(..) )
import qualified Unsafe.Coerce as Hs
newtype SessionId
  = SessionId {sessionIdValue :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData SessionId)
instance (HsProtobuf.Named SessionId) where
  nameOf _ = Hs.fromString "SessionId"
instance (HsProtobuf.HasDefault SessionId)
instance (HsProtobuf.Message SessionId) where
  encodeMessage _ SessionId {sessionIdValue}
    = (HsProtobuf.encodeMessageField
         (HsProtobuf.FieldNumber 1)
         ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) sessionIdValue))
  decodeMessage _
    = Hs.pure SessionId
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "value") [] ""]
instance (HsJSONPB.ToJSONPB SessionId) where
  toJSONPB (SessionId f1)
    = HsJSONPB.object
        ["value" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1)]
  toEncodingPB (SessionId f1)
    = HsJSONPB.pairs
        ["value" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1)]
instance (HsJSONPB.FromJSONPB SessionId) where
  parseJSONPB
    = HsJSONPB.withObject
        "SessionId"
        (\ obj
           -> Hs.pure SessionId
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "value")))
instance (HsJSONPB.ToJSON SessionId) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON SessionId) where
  parseJSON = HsJSONPB.parseJSONPB
data Role
  = RoleROLE_UNSPECIFIED |
    RoleROLE_DEV |
    RoleROLE_TL |
    RoleROLE_PM |
    RoleROLE_REVIEWER
  deriving (Hs.Show, Hs.Eq, Hs.Generic, Hs.NFData)
instance (HsProtobuf.Named Role) where
  nameOf _ = Hs.fromString "Role"
instance (HsProtobuf.HasDefault Role)
instance (Hs.Bounded Role) where
  minBound = RoleROLE_UNSPECIFIED
  maxBound = RoleROLE_REVIEWER
instance (Hs.Ord Role) where
  compare x y
    = Hs.compare
        (HsProtobuf.fromProtoEnum x) (HsProtobuf.fromProtoEnum y)
instance (HsProtobuf.ProtoEnum Role) where
  toProtoEnumMay 0 = Hs.Just RoleROLE_UNSPECIFIED
  toProtoEnumMay 1 = Hs.Just RoleROLE_DEV
  toProtoEnumMay 2 = Hs.Just RoleROLE_TL
  toProtoEnumMay 3 = Hs.Just RoleROLE_PM
  toProtoEnumMay 4 = Hs.Just RoleROLE_REVIEWER
  toProtoEnumMay _ = Hs.Nothing
  fromProtoEnum RoleROLE_UNSPECIFIED = 0
  fromProtoEnum RoleROLE_DEV = 1
  fromProtoEnum RoleROLE_TL = 2
  fromProtoEnum RoleROLE_PM = 3
  fromProtoEnum RoleROLE_REVIEWER = 4
instance (HsJSONPB.ToJSONPB Role) where
  toJSONPB x _ = HsJSONPB.enumFieldString x
  toEncodingPB x _ = HsJSONPB.enumFieldEncoding x
instance (HsJSONPB.FromJSONPB Role) where
  parseJSONPB (HsJSONPB.String "ROLE_UNSPECIFIED")
    = Hs.pure RoleROLE_UNSPECIFIED
  parseJSONPB (HsJSONPB.String "ROLE_DEV") = Hs.pure RoleROLE_DEV
  parseJSONPB (HsJSONPB.String "ROLE_TL") = Hs.pure RoleROLE_TL
  parseJSONPB (HsJSONPB.String "ROLE_PM") = Hs.pure RoleROLE_PM
  parseJSONPB (HsJSONPB.String "ROLE_REVIEWER")
    = Hs.pure RoleROLE_REVIEWER
  parseJSONPB v = HsJSONPB.typeMismatch "Role" v
instance (HsJSONPB.ToJSON Role) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON Role) where
  parseJSON = HsJSONPB.parseJSONPB
instance (HsProtobuf.Finite Role)
data ToolPermission
  = ToolPermissionTOOL_PERMISSION_UNSPECIFIED |
    ToolPermissionTOOL_PERMISSION_ALLOW |
    ToolPermissionTOOL_PERMISSION_DENY |
    ToolPermissionTOOL_PERMISSION_ASK |
    ToolPermissionTOOL_PERMISSION_SKIP
  deriving (Hs.Show, Hs.Eq, Hs.Generic, Hs.NFData)
instance (HsProtobuf.Named ToolPermission) where
  nameOf _ = Hs.fromString "ToolPermission"
instance (HsProtobuf.HasDefault ToolPermission)
instance (Hs.Bounded ToolPermission) where
  minBound = ToolPermissionTOOL_PERMISSION_UNSPECIFIED
  maxBound = ToolPermissionTOOL_PERMISSION_SKIP
instance (Hs.Ord ToolPermission) where
  compare x y
    = Hs.compare
        (HsProtobuf.fromProtoEnum x) (HsProtobuf.fromProtoEnum y)
instance (HsProtobuf.ProtoEnum ToolPermission) where
  toProtoEnumMay 0
    = Hs.Just ToolPermissionTOOL_PERMISSION_UNSPECIFIED
  toProtoEnumMay 1 = Hs.Just ToolPermissionTOOL_PERMISSION_ALLOW
  toProtoEnumMay 2 = Hs.Just ToolPermissionTOOL_PERMISSION_DENY
  toProtoEnumMay 3 = Hs.Just ToolPermissionTOOL_PERMISSION_ASK
  toProtoEnumMay 4 = Hs.Just ToolPermissionTOOL_PERMISSION_SKIP
  toProtoEnumMay _ = Hs.Nothing
  fromProtoEnum ToolPermissionTOOL_PERMISSION_UNSPECIFIED = 0
  fromProtoEnum ToolPermissionTOOL_PERMISSION_ALLOW = 1
  fromProtoEnum ToolPermissionTOOL_PERMISSION_DENY = 2
  fromProtoEnum ToolPermissionTOOL_PERMISSION_ASK = 3
  fromProtoEnum ToolPermissionTOOL_PERMISSION_SKIP = 4
instance (HsJSONPB.ToJSONPB ToolPermission) where
  toJSONPB x _ = HsJSONPB.enumFieldString x
  toEncodingPB x _ = HsJSONPB.enumFieldEncoding x
instance (HsJSONPB.FromJSONPB ToolPermission) where
  parseJSONPB (HsJSONPB.String "TOOL_PERMISSION_UNSPECIFIED")
    = Hs.pure ToolPermissionTOOL_PERMISSION_UNSPECIFIED
  parseJSONPB (HsJSONPB.String "TOOL_PERMISSION_ALLOW")
    = Hs.pure ToolPermissionTOOL_PERMISSION_ALLOW
  parseJSONPB (HsJSONPB.String "TOOL_PERMISSION_DENY")
    = Hs.pure ToolPermissionTOOL_PERMISSION_DENY
  parseJSONPB (HsJSONPB.String "TOOL_PERMISSION_ASK")
    = Hs.pure ToolPermissionTOOL_PERMISSION_ASK
  parseJSONPB (HsJSONPB.String "TOOL_PERMISSION_SKIP")
    = Hs.pure ToolPermissionTOOL_PERMISSION_SKIP
  parseJSONPB v = HsJSONPB.typeMismatch "ToolPermission" v
instance (HsJSONPB.ToJSON ToolPermission) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON ToolPermission) where
  parseJSON = HsJSONPB.parseJSONPB
instance (HsProtobuf.Finite ToolPermission)
newtype GitBranch
  = GitBranch {gitBranchName :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData GitBranch)
instance (HsProtobuf.Named GitBranch) where
  nameOf _ = Hs.fromString "GitBranch"
instance (HsProtobuf.HasDefault GitBranch)
instance (HsProtobuf.Message GitBranch) where
  encodeMessage _ GitBranch {gitBranchName}
    = (HsProtobuf.encodeMessageField
         (HsProtobuf.FieldNumber 1)
         ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) gitBranchName))
  decodeMessage _
    = Hs.pure GitBranch
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "name") [] ""]
instance (HsJSONPB.ToJSONPB GitBranch) where
  toJSONPB (GitBranch f1)
    = HsJSONPB.object
        ["name" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1)]
  toEncodingPB (GitBranch f1)
    = HsJSONPB.pairs
        ["name" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1)]
instance (HsJSONPB.FromJSONPB GitBranch) where
  parseJSONPB
    = HsJSONPB.withObject
        "GitBranch"
        (\ obj
           -> Hs.pure GitBranch
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "name")))
instance (HsJSONPB.ToJSON GitBranch) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON GitBranch) where
  parseJSON = HsJSONPB.parseJSONPB
data GitCommit
  = GitCommit {gitCommitSha :: Hs.Text,
               gitCommitMessage :: Hs.Text,
               gitCommitAuthor :: Hs.Text,
               gitCommitTimestampUnix :: Hs.Int64}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData GitCommit)
instance (HsProtobuf.Named GitCommit) where
  nameOf _ = Hs.fromString "GitCommit"
instance (HsProtobuf.HasDefault GitCommit)
instance (HsProtobuf.Message GitCommit) where
  encodeMessage
    _
    GitCommit {gitCommitSha, gitCommitMessage, gitCommitAuthor,
               gitCommitTimestampUnix}
    = Hs.mappend
        (Hs.mappend
           (Hs.mappend
              (HsProtobuf.encodeMessageField
                 (HsProtobuf.FieldNumber 1)
                 ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) gitCommitSha))
              (HsProtobuf.encodeMessageField
                 (HsProtobuf.FieldNumber 2)
                 ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                    gitCommitMessage)))
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 3)
              ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                 gitCommitAuthor)))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 4) gitCommitTimestampUnix)
  decodeMessage _
    = Hs.pure GitCommit
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 3)))
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 4)
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "sha") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "message") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 3)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "author") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 4) (HsProtobufAST.Prim HsProtobufAST.Int64)
         (HsProtobufAST.Single "timestamp_unix") [] ""]
instance (HsJSONPB.ToJSONPB GitCommit) where
  toJSONPB (GitCommit f1 f2 f3 f4)
    = HsJSONPB.object
        ["sha" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "message"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
         "author" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3),
         "timestamp_unix" .= f4]
  toEncodingPB (GitCommit f1 f2 f3 f4)
    = HsJSONPB.pairs
        ["sha" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "message"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
         "author" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3),
         "timestamp_unix" .= f4]
instance (HsJSONPB.FromJSONPB GitCommit) where
  parseJSONPB
    = HsJSONPB.withObject
        "GitCommit"
        (\ obj
           -> Hs.pure GitCommit
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "sha"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "message"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "author"))
                <*> obj .: "timestamp_unix")
instance (HsJSONPB.ToJSON GitCommit) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON GitCommit) where
  parseJSON = HsJSONPB.parseJSONPB
newtype FilePath
  = FilePath {filePathPath :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData FilePath)
instance (HsProtobuf.Named FilePath) where
  nameOf _ = Hs.fromString "FilePath"
instance (HsProtobuf.HasDefault FilePath)
instance (HsProtobuf.Message FilePath) where
  encodeMessage _ FilePath {filePathPath}
    = (HsProtobuf.encodeMessageField
         (HsProtobuf.FieldNumber 1)
         ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) filePathPath))
  decodeMessage _
    = Hs.pure FilePath
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "path") [] ""]
instance (HsJSONPB.ToJSONPB FilePath) where
  toJSONPB (FilePath f1)
    = HsJSONPB.object
        ["path" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1)]
  toEncodingPB (FilePath f1)
    = HsJSONPB.pairs
        ["path" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1)]
instance (HsJSONPB.FromJSONPB FilePath) where
  parseJSONPB
    = HsJSONPB.withObject
        "FilePath"
        (\ obj
           -> Hs.pure FilePath
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "path")))
instance (HsJSONPB.ToJSON FilePath) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON FilePath) where
  parseJSON = HsJSONPB.parseJSONPB
newtype DirectoryPath
  = DirectoryPath {directoryPathPath :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData DirectoryPath)
instance (HsProtobuf.Named DirectoryPath) where
  nameOf _ = Hs.fromString "DirectoryPath"
instance (HsProtobuf.HasDefault DirectoryPath)
instance (HsProtobuf.Message DirectoryPath) where
  encodeMessage _ DirectoryPath {directoryPathPath}
    = (HsProtobuf.encodeMessageField
         (HsProtobuf.FieldNumber 1)
         ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
            directoryPathPath))
  decodeMessage _
    = Hs.pure DirectoryPath
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "path") [] ""]
instance (HsJSONPB.ToJSONPB DirectoryPath) where
  toJSONPB (DirectoryPath f1)
    = HsJSONPB.object
        ["path" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1)]
  toEncodingPB (DirectoryPath f1)
    = HsJSONPB.pairs
        ["path" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1)]
instance (HsJSONPB.FromJSONPB DirectoryPath) where
  parseJSONPB
    = HsJSONPB.withObject
        "DirectoryPath"
        (\ obj
           -> Hs.pure DirectoryPath
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "path")))
instance (HsJSONPB.ToJSON DirectoryPath) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON DirectoryPath) where
  parseJSON = HsJSONPB.parseJSONPB
data IssueRef
  = IssueRef {issueRefOwner :: Hs.Text,
              issueRefRepo :: Hs.Text,
              issueRefNumber :: Hs.Int32}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData IssueRef)
instance (HsProtobuf.Named IssueRef) where
  nameOf _ = Hs.fromString "IssueRef"
instance (HsProtobuf.HasDefault IssueRef)
instance (HsProtobuf.Message IssueRef) where
  encodeMessage
    _
    IssueRef {issueRefOwner, issueRefRepo, issueRefNumber}
    = Hs.mappend
        (Hs.mappend
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 1)
              ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) issueRefOwner))
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 2)
              ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) issueRefRepo)))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 3) issueRefNumber)
  decodeMessage _
    = Hs.pure IssueRef
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)))
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 3)
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "owner") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "repo") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 3) (HsProtobufAST.Prim HsProtobufAST.Int32)
         (HsProtobufAST.Single "number") [] ""]
instance (HsJSONPB.ToJSONPB IssueRef) where
  toJSONPB (IssueRef f1 f2 f3)
    = HsJSONPB.object
        ["owner" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "repo" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
         "number" .= f3]
  toEncodingPB (IssueRef f1 f2 f3)
    = HsJSONPB.pairs
        ["owner" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "repo" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
         "number" .= f3]
instance (HsJSONPB.FromJSONPB IssueRef) where
  parseJSONPB
    = HsJSONPB.withObject
        "IssueRef"
        (\ obj
           -> Hs.pure IssueRef
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "owner"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "repo"))
                <*> obj .: "number")
instance (HsJSONPB.ToJSON IssueRef) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON IssueRef) where
  parseJSON = HsJSONPB.parseJSONPB
data PullRequestRef
  = PullRequestRef {pullRequestRefOwner :: Hs.Text,
                    pullRequestRefRepo :: Hs.Text,
                    pullRequestRefNumber :: Hs.Int32}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData PullRequestRef)
instance (HsProtobuf.Named PullRequestRef) where
  nameOf _ = Hs.fromString "PullRequestRef"
instance (HsProtobuf.HasDefault PullRequestRef)
instance (HsProtobuf.Message PullRequestRef) where
  encodeMessage
    _
    PullRequestRef {pullRequestRefOwner, pullRequestRefRepo,
                    pullRequestRefNumber}
    = Hs.mappend
        (Hs.mappend
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 1)
              ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                 pullRequestRefOwner))
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 2)
              ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                 pullRequestRefRepo)))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 3) pullRequestRefNumber)
  decodeMessage _
    = Hs.pure PullRequestRef
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)))
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 3)
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "owner") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "repo") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 3) (HsProtobufAST.Prim HsProtobufAST.Int32)
         (HsProtobufAST.Single "number") [] ""]
instance (HsJSONPB.ToJSONPB PullRequestRef) where
  toJSONPB (PullRequestRef f1 f2 f3)
    = HsJSONPB.object
        ["owner" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "repo" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
         "number" .= f3]
  toEncodingPB (PullRequestRef f1 f2 f3)
    = HsJSONPB.pairs
        ["owner" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "repo" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
         "number" .= f3]
instance (HsJSONPB.FromJSONPB PullRequestRef) where
  parseJSONPB
    = HsJSONPB.withObject
        "PullRequestRef"
        (\ obj
           -> Hs.pure PullRequestRef
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "owner"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "repo"))
                <*> obj .: "number")
instance (HsJSONPB.ToJSON PullRequestRef) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON PullRequestRef) where
  parseJSON = HsJSONPB.parseJSONPB