{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE NegativeLiterals #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeOperators #-}
{-# OPTIONS_GHC -fno-warn-missing-export-lists #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-- | Generated by Haskell protocol buffer compiler. DO NOT EDIT!
module ExoMonad.Hook where

import Control.Applicative ((<$>), (<*>), (<|>))
import Control.Applicative qualified as Hs
import Control.DeepSeq qualified as Hs
import Control.Monad qualified as Hs
import Data.ByteString qualified as Hs
import Data.Coerce qualified as Hs
import Data.Int qualified as Hs (Int16, Int32, Int64)
import Data.List.NonEmpty qualified as Hs (NonEmpty (..))
import Data.Map qualified as Hs (Map, mapKeysMonotonic)
import Data.Proxy qualified as Proxy
import Data.String qualified as Hs (fromString)
import Data.Text.Lazy qualified as Hs (Text)
import Data.Vector qualified as Hs (Vector)
import Data.Word qualified as Hs (Word16, Word32, Word64)
import ExoMonad.Common qualified
import GHC.Enum qualified as Hs
import GHC.Generics qualified as Hs
import Google.Protobuf.Wrappers.Polymorphic qualified as HsProtobuf
  ( Wrapped (..),
  )
import Proto3.Suite.Class qualified as HsProtobuf
import Proto3.Suite.DotProto qualified as HsProtobufAST
import Proto3.Suite.JSONPB ((.:), (.=))
import Proto3.Suite.JSONPB qualified as HsJSONPB
import Proto3.Suite.Types qualified as HsProtobuf
import Proto3.Wire qualified as HsProtobuf
import Proto3.Wire.Decode qualified as HsProtobuf
  ( Parser,
    RawField,
  )
import Unsafe.Coerce qualified as Hs
import Prelude qualified as Hs

data HookType
  = HookTypeHOOK_TYPE_UNSPECIFIED
  | HookTypeHOOK_TYPE_PRE_TOOL_USE
  | HookTypeHOOK_TYPE_POST_TOOL_USE
  | HookTypeHOOK_TYPE_SESSION_START
  | HookTypeHOOK_TYPE_SESSION_END
  | HookTypeHOOK_TYPE_SUBAGENT_STOP
  | HookTypeHOOK_TYPE_NOTIFICATION
  | HookTypeHOOK_TYPE_STOP
  | HookTypeHOOK_TYPE_PRE_COMPACT
  | HookTypeHOOK_TYPE_PERMISSION_REQUEST
  | HookTypeHOOK_TYPE_USER_PROMPT_SUBMIT
  deriving (Hs.Show, Hs.Eq, Hs.Generic, Hs.NFData)

instance (HsProtobuf.Named HookType) where
  nameOf _ = Hs.fromString "HookType"

instance (HsProtobuf.HasDefault HookType)

instance (Hs.Bounded HookType) where
  minBound = HookTypeHOOK_TYPE_UNSPECIFIED
  maxBound = HookTypeHOOK_TYPE_USER_PROMPT_SUBMIT

instance (Hs.Ord HookType) where
  compare x y =
    Hs.compare
      (HsProtobuf.fromProtoEnum x)
      (HsProtobuf.fromProtoEnum y)

instance (HsProtobuf.ProtoEnum HookType) where
  toProtoEnumMay 0 = Hs.Just HookTypeHOOK_TYPE_UNSPECIFIED
  toProtoEnumMay 1 = Hs.Just HookTypeHOOK_TYPE_PRE_TOOL_USE
  toProtoEnumMay 2 = Hs.Just HookTypeHOOK_TYPE_POST_TOOL_USE
  toProtoEnumMay 3 = Hs.Just HookTypeHOOK_TYPE_SESSION_START
  toProtoEnumMay 4 = Hs.Just HookTypeHOOK_TYPE_SESSION_END
  toProtoEnumMay 5 = Hs.Just HookTypeHOOK_TYPE_SUBAGENT_STOP
  toProtoEnumMay 6 = Hs.Just HookTypeHOOK_TYPE_NOTIFICATION
  toProtoEnumMay 7 = Hs.Just HookTypeHOOK_TYPE_STOP
  toProtoEnumMay 8 = Hs.Just HookTypeHOOK_TYPE_PRE_COMPACT
  toProtoEnumMay 9 = Hs.Just HookTypeHOOK_TYPE_PERMISSION_REQUEST
  toProtoEnumMay 10 = Hs.Just HookTypeHOOK_TYPE_USER_PROMPT_SUBMIT
  toProtoEnumMay _ = Hs.Nothing
  fromProtoEnum HookTypeHOOK_TYPE_UNSPECIFIED = 0
  fromProtoEnum HookTypeHOOK_TYPE_PRE_TOOL_USE = 1
  fromProtoEnum HookTypeHOOK_TYPE_POST_TOOL_USE = 2
  fromProtoEnum HookTypeHOOK_TYPE_SESSION_START = 3
  fromProtoEnum HookTypeHOOK_TYPE_SESSION_END = 4
  fromProtoEnum HookTypeHOOK_TYPE_SUBAGENT_STOP = 5
  fromProtoEnum HookTypeHOOK_TYPE_NOTIFICATION = 6
  fromProtoEnum HookTypeHOOK_TYPE_STOP = 7
  fromProtoEnum HookTypeHOOK_TYPE_PRE_COMPACT = 8
  fromProtoEnum HookTypeHOOK_TYPE_PERMISSION_REQUEST = 9
  fromProtoEnum HookTypeHOOK_TYPE_USER_PROMPT_SUBMIT = 10

instance (HsJSONPB.ToJSONPB HookType) where
  toJSONPB x _ = HsJSONPB.enumFieldString x
  toEncodingPB x _ = HsJSONPB.enumFieldEncoding x

instance (HsJSONPB.FromJSONPB HookType) where
  parseJSONPB (HsJSONPB.String "HOOK_TYPE_UNSPECIFIED") =
    Hs.pure HookTypeHOOK_TYPE_UNSPECIFIED
  parseJSONPB (HsJSONPB.String "HOOK_TYPE_PRE_TOOL_USE") =
    Hs.pure HookTypeHOOK_TYPE_PRE_TOOL_USE
  parseJSONPB (HsJSONPB.String "HOOK_TYPE_POST_TOOL_USE") =
    Hs.pure HookTypeHOOK_TYPE_POST_TOOL_USE
  parseJSONPB (HsJSONPB.String "HOOK_TYPE_SESSION_START") =
    Hs.pure HookTypeHOOK_TYPE_SESSION_START
  parseJSONPB (HsJSONPB.String "HOOK_TYPE_SESSION_END") =
    Hs.pure HookTypeHOOK_TYPE_SESSION_END
  parseJSONPB (HsJSONPB.String "HOOK_TYPE_SUBAGENT_STOP") =
    Hs.pure HookTypeHOOK_TYPE_SUBAGENT_STOP
  parseJSONPB (HsJSONPB.String "HOOK_TYPE_NOTIFICATION") =
    Hs.pure HookTypeHOOK_TYPE_NOTIFICATION
  parseJSONPB (HsJSONPB.String "HOOK_TYPE_STOP") =
    Hs.pure HookTypeHOOK_TYPE_STOP
  parseJSONPB (HsJSONPB.String "HOOK_TYPE_PRE_COMPACT") =
    Hs.pure HookTypeHOOK_TYPE_PRE_COMPACT
  parseJSONPB (HsJSONPB.String "HOOK_TYPE_PERMISSION_REQUEST") =
    Hs.pure HookTypeHOOK_TYPE_PERMISSION_REQUEST
  parseJSONPB (HsJSONPB.String "HOOK_TYPE_USER_PROMPT_SUBMIT") =
    Hs.pure HookTypeHOOK_TYPE_USER_PROMPT_SUBMIT
  parseJSONPB v = HsJSONPB.typeMismatch "HookType" v

instance (HsJSONPB.ToJSON HookType) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON HookType) where
  parseJSON = HsJSONPB.parseJSONPB

instance (HsProtobuf.Finite HookType)

data StopDecision
  = StopDecisionSTOP_DECISION_UNSPECIFIED
  | StopDecisionSTOP_DECISION_ALLOW
  | StopDecisionSTOP_DECISION_BLOCK
  | StopDecisionSTOP_DECISION_ASK
  deriving (Hs.Show, Hs.Eq, Hs.Generic, Hs.NFData)

instance (HsProtobuf.Named StopDecision) where
  nameOf _ = Hs.fromString "StopDecision"

instance (HsProtobuf.HasDefault StopDecision)

instance (Hs.Bounded StopDecision) where
  minBound = StopDecisionSTOP_DECISION_UNSPECIFIED
  maxBound = StopDecisionSTOP_DECISION_ASK

instance (Hs.Ord StopDecision) where
  compare x y =
    Hs.compare
      (HsProtobuf.fromProtoEnum x)
      (HsProtobuf.fromProtoEnum y)

instance (HsProtobuf.ProtoEnum StopDecision) where
  toProtoEnumMay 0 = Hs.Just StopDecisionSTOP_DECISION_UNSPECIFIED
  toProtoEnumMay 1 = Hs.Just StopDecisionSTOP_DECISION_ALLOW
  toProtoEnumMay 2 = Hs.Just StopDecisionSTOP_DECISION_BLOCK
  toProtoEnumMay 3 = Hs.Just StopDecisionSTOP_DECISION_ASK
  toProtoEnumMay _ = Hs.Nothing
  fromProtoEnum StopDecisionSTOP_DECISION_UNSPECIFIED = 0
  fromProtoEnum StopDecisionSTOP_DECISION_ALLOW = 1
  fromProtoEnum StopDecisionSTOP_DECISION_BLOCK = 2
  fromProtoEnum StopDecisionSTOP_DECISION_ASK = 3

instance (HsJSONPB.ToJSONPB StopDecision) where
  toJSONPB x _ = HsJSONPB.enumFieldString x
  toEncodingPB x _ = HsJSONPB.enumFieldEncoding x

instance (HsJSONPB.FromJSONPB StopDecision) where
  parseJSONPB (HsJSONPB.String "STOP_DECISION_UNSPECIFIED") =
    Hs.pure StopDecisionSTOP_DECISION_UNSPECIFIED
  parseJSONPB (HsJSONPB.String "STOP_DECISION_ALLOW") =
    Hs.pure StopDecisionSTOP_DECISION_ALLOW
  parseJSONPB (HsJSONPB.String "STOP_DECISION_BLOCK") =
    Hs.pure StopDecisionSTOP_DECISION_BLOCK
  parseJSONPB (HsJSONPB.String "STOP_DECISION_ASK") =
    Hs.pure StopDecisionSTOP_DECISION_ASK
  parseJSONPB v = HsJSONPB.typeMismatch "StopDecision" v

instance (HsJSONPB.ToJSON StopDecision) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON StopDecision) where
  parseJSON = HsJSONPB.parseJSONPB

instance (HsProtobuf.Finite StopDecision)

data PreToolUseInput
  = PreToolUseInput
  { preToolUseInputToolName :: Hs.Text,
    preToolUseInputToolInput :: Hs.Text,
    preToolUseInputToolUseId :: Hs.Text,
    preToolUseInputSessionId :: (Hs.Maybe ExoMonad.Common.SessionId)
  }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData PreToolUseInput)

instance (HsProtobuf.Named PreToolUseInput) where
  nameOf _ = Hs.fromString "PreToolUseInput"

instance (HsProtobuf.HasDefault PreToolUseInput)

instance (HsProtobuf.Message PreToolUseInput) where
  encodeMessage
    _
    PreToolUseInput
      { preToolUseInputToolName,
        preToolUseInputToolInput,
        preToolUseInputToolUseId,
        preToolUseInputSessionId
      } =
      Hs.mappend
        ( Hs.mappend
            ( Hs.mappend
                ( HsProtobuf.encodeMessageField
                    (HsProtobuf.FieldNumber 1)
                    ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                        preToolUseInputToolName
                    )
                )
                ( HsProtobuf.encodeMessageField
                    (HsProtobuf.FieldNumber 2)
                    ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                        preToolUseInputToolInput
                    )
                )
            )
            ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 3)
                ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                    preToolUseInputToolUseId
                )
            )
        )
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 4)
            ( ( Hs.coerce
                  @(Hs.Maybe ExoMonad.Common.SessionId)
                  @(HsProtobuf.Nested ExoMonad.Common.SessionId)
              )
                preToolUseInputSessionId
            )
        )
  decodeMessage _ =
    Hs.pure PreToolUseInput
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 1)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 2)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 3)
              )
          )
      <*> ( ( HsProtobuf.coerceOver
                @(HsProtobuf.Nested ExoMonad.Common.SessionId)
                @(Hs.Maybe ExoMonad.Common.SessionId)
            )
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 4)
              )
          )
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "tool_name")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 2)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "tool_input")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 3)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "tool_use_id")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 4)
        ( HsProtobufAST.Prim
            ( HsProtobufAST.Named
                ( HsProtobufAST.Dots
                    (HsProtobufAST.Path ("exomonad" Hs.:| ["common", "SessionId"]))
                )
            )
        )
        (HsProtobufAST.Single "session_id")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB PreToolUseInput) where
  toJSONPB (PreToolUseInput f1 f2 f3 f4) =
    HsJSONPB.object
      [ "tool_name"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
        "tool_input"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
        "tool_use_id"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3),
        "session_id"
          .= ( ( Hs.coerce
                   @(Hs.Maybe ExoMonad.Common.SessionId)
                   @(HsProtobuf.Nested ExoMonad.Common.SessionId)
               )
                 f4
             )
      ]
  toEncodingPB (PreToolUseInput f1 f2 f3 f4) =
    HsJSONPB.pairs
      [ "tool_name"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
        "tool_input"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
        "tool_use_id"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3),
        "session_id"
          .= ( ( Hs.coerce
                   @(Hs.Maybe ExoMonad.Common.SessionId)
                   @(HsProtobuf.Nested ExoMonad.Common.SessionId)
               )
                 f4
             )
      ]

instance (HsJSONPB.FromJSONPB PreToolUseInput) where
  parseJSONPB =
    HsJSONPB.withObject
      "PreToolUseInput"
      ( \obj ->
          Hs.pure PreToolUseInput
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "tool_name")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "tool_input")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "tool_use_id")
                )
            <*> ( ( HsProtobuf.coerceOver
                      @(HsProtobuf.Nested ExoMonad.Common.SessionId)
                      @(Hs.Maybe ExoMonad.Common.SessionId)
                  )
                    (obj .: "session_id")
                )
      )

instance (HsJSONPB.ToJSON PreToolUseInput) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON PreToolUseInput) where
  parseJSON = HsJSONPB.parseJSONPB

data PreToolUseOutput
  = PreToolUseOutput
  { preToolUseOutputPermission :: (HsProtobuf.Enumerated ExoMonad.Common.ToolPermission),
    preToolUseOutputReason :: Hs.Text,
    preToolUseOutputUpdatedInput :: Hs.Text
  }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData PreToolUseOutput)

instance (HsProtobuf.Named PreToolUseOutput) where
  nameOf _ = Hs.fromString "PreToolUseOutput"

instance (HsProtobuf.HasDefault PreToolUseOutput)

instance (HsProtobuf.Message PreToolUseOutput) where
  encodeMessage
    _
    PreToolUseOutput
      { preToolUseOutputPermission,
        preToolUseOutputReason,
        preToolUseOutputUpdatedInput
      } =
      Hs.mappend
        ( Hs.mappend
            ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 1)
                preToolUseOutputPermission
            )
            ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 2)
                ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                    preToolUseOutputReason
                )
            )
        )
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 3)
            ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                preToolUseOutputUpdatedInput
            )
        )
  decodeMessage _ =
    Hs.pure PreToolUseOutput
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 1)
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 2)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 3)
              )
          )
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        ( HsProtobufAST.Prim
            ( HsProtobufAST.Named
                ( HsProtobufAST.Dots
                    ( HsProtobufAST.Path
                        ("exomonad" Hs.:| ["common", "ToolPermission"])
                    )
                )
            )
        )
        (HsProtobufAST.Single "permission")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 2)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "reason")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 3)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "updated_input")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB PreToolUseOutput) where
  toJSONPB (PreToolUseOutput f1 f2 f3) =
    HsJSONPB.object
      [ "permission" .= f1,
        "reason" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
        "updated_input"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3)
      ]
  toEncodingPB (PreToolUseOutput f1 f2 f3) =
    HsJSONPB.pairs
      [ "permission" .= f1,
        "reason" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
        "updated_input"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3)
      ]

instance (HsJSONPB.FromJSONPB PreToolUseOutput) where
  parseJSONPB =
    HsJSONPB.withObject
      "PreToolUseOutput"
      ( \obj ->
          Hs.pure PreToolUseOutput
            <*> obj .: "permission"
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "reason")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "updated_input")
                )
      )

instance (HsJSONPB.ToJSON PreToolUseOutput) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON PreToolUseOutput) where
  parseJSON = HsJSONPB.parseJSONPB

data PostToolUseInput
  = PostToolUseInput
  { postToolUseInputToolName :: Hs.Text,
    postToolUseInputToolInput :: Hs.Text,
    postToolUseInputToolResponse :: Hs.Text,
    postToolUseInputToolUseId :: Hs.Text,
    postToolUseInputSessionId :: (Hs.Maybe ExoMonad.Common.SessionId)
  }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData PostToolUseInput)

instance (HsProtobuf.Named PostToolUseInput) where
  nameOf _ = Hs.fromString "PostToolUseInput"

instance (HsProtobuf.HasDefault PostToolUseInput)

instance (HsProtobuf.Message PostToolUseInput) where
  encodeMessage
    _
    PostToolUseInput
      { postToolUseInputToolName,
        postToolUseInputToolInput,
        postToolUseInputToolResponse,
        postToolUseInputToolUseId,
        postToolUseInputSessionId
      } =
      Hs.mappend
        ( Hs.mappend
            ( Hs.mappend
                ( Hs.mappend
                    ( HsProtobuf.encodeMessageField
                        (HsProtobuf.FieldNumber 1)
                        ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                            postToolUseInputToolName
                        )
                    )
                    ( HsProtobuf.encodeMessageField
                        (HsProtobuf.FieldNumber 2)
                        ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                            postToolUseInputToolInput
                        )
                    )
                )
                ( HsProtobuf.encodeMessageField
                    (HsProtobuf.FieldNumber 3)
                    ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                        postToolUseInputToolResponse
                    )
                )
            )
            ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 4)
                ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                    postToolUseInputToolUseId
                )
            )
        )
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 5)
            ( ( Hs.coerce
                  @(Hs.Maybe ExoMonad.Common.SessionId)
                  @(HsProtobuf.Nested ExoMonad.Common.SessionId)
              )
                postToolUseInputSessionId
            )
        )
  decodeMessage _ =
    Hs.pure PostToolUseInput
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 1)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 2)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 3)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 4)
              )
          )
      <*> ( ( HsProtobuf.coerceOver
                @(HsProtobuf.Nested ExoMonad.Common.SessionId)
                @(Hs.Maybe ExoMonad.Common.SessionId)
            )
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 5)
              )
          )
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "tool_name")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 2)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "tool_input")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 3)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "tool_response")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 4)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "tool_use_id")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 5)
        ( HsProtobufAST.Prim
            ( HsProtobufAST.Named
                ( HsProtobufAST.Dots
                    (HsProtobufAST.Path ("exomonad" Hs.:| ["common", "SessionId"]))
                )
            )
        )
        (HsProtobufAST.Single "session_id")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB PostToolUseInput) where
  toJSONPB (PostToolUseInput f1 f2 f3 f4 f5) =
    HsJSONPB.object
      [ "tool_name"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
        "tool_input"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
        "tool_response"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3),
        "tool_use_id"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f4),
        "session_id"
          .= ( ( Hs.coerce
                   @(Hs.Maybe ExoMonad.Common.SessionId)
                   @(HsProtobuf.Nested ExoMonad.Common.SessionId)
               )
                 f5
             )
      ]
  toEncodingPB (PostToolUseInput f1 f2 f3 f4 f5) =
    HsJSONPB.pairs
      [ "tool_name"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
        "tool_input"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
        "tool_response"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3),
        "tool_use_id"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f4),
        "session_id"
          .= ( ( Hs.coerce
                   @(Hs.Maybe ExoMonad.Common.SessionId)
                   @(HsProtobuf.Nested ExoMonad.Common.SessionId)
               )
                 f5
             )
      ]

instance (HsJSONPB.FromJSONPB PostToolUseInput) where
  parseJSONPB =
    HsJSONPB.withObject
      "PostToolUseInput"
      ( \obj ->
          Hs.pure PostToolUseInput
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "tool_name")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "tool_input")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "tool_response")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "tool_use_id")
                )
            <*> ( ( HsProtobuf.coerceOver
                      @(HsProtobuf.Nested ExoMonad.Common.SessionId)
                      @(Hs.Maybe ExoMonad.Common.SessionId)
                  )
                    (obj .: "session_id")
                )
      )

instance (HsJSONPB.ToJSON PostToolUseInput) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON PostToolUseInput) where
  parseJSON = HsJSONPB.parseJSONPB

newtype PostToolUseOutput
  = PostToolUseOutput {postToolUseOutputAdditionalContext :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData PostToolUseOutput)

instance (HsProtobuf.Named PostToolUseOutput) where
  nameOf _ = Hs.fromString "PostToolUseOutput"

instance (HsProtobuf.HasDefault PostToolUseOutput)

instance (HsProtobuf.Message PostToolUseOutput) where
  encodeMessage
    _
    PostToolUseOutput {postToolUseOutputAdditionalContext} =
      ( HsProtobuf.encodeMessageField
          (HsProtobuf.FieldNumber 1)
          ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              postToolUseOutputAdditionalContext
          )
      )
  decodeMessage _ =
    Hs.pure PostToolUseOutput
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 1)
              )
          )
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "additional_context")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB PostToolUseOutput) where
  toJSONPB (PostToolUseOutput f1) =
    HsJSONPB.object
      [ "additional_context"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1)
      ]
  toEncodingPB (PostToolUseOutput f1) =
    HsJSONPB.pairs
      [ "additional_context"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1)
      ]

instance (HsJSONPB.FromJSONPB PostToolUseOutput) where
  parseJSONPB =
    HsJSONPB.withObject
      "PostToolUseOutput"
      ( \obj ->
          Hs.pure PostToolUseOutput
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "additional_context")
                )
      )

instance (HsJSONPB.ToJSON PostToolUseOutput) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON PostToolUseOutput) where
  parseJSON = HsJSONPB.parseJSONPB

data SessionStartInput
  = SessionStartInput
  { sessionStartInputSessionId :: (Hs.Maybe ExoMonad.Common.SessionId),
    sessionStartInputWorkingDirectory :: Hs.Text,
    sessionStartInputPermissionMode :: Hs.Text
  }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData SessionStartInput)

instance (HsProtobuf.Named SessionStartInput) where
  nameOf _ = Hs.fromString "SessionStartInput"

instance (HsProtobuf.HasDefault SessionStartInput)

instance (HsProtobuf.Message SessionStartInput) where
  encodeMessage
    _
    SessionStartInput
      { sessionStartInputSessionId,
        sessionStartInputWorkingDirectory,
        sessionStartInputPermissionMode
      } =
      Hs.mappend
        ( Hs.mappend
            ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 1)
                ( ( Hs.coerce
                      @(Hs.Maybe ExoMonad.Common.SessionId)
                      @(HsProtobuf.Nested ExoMonad.Common.SessionId)
                  )
                    sessionStartInputSessionId
                )
            )
            ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 2)
                ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                    sessionStartInputWorkingDirectory
                )
            )
        )
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 3)
            ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                sessionStartInputPermissionMode
            )
        )
  decodeMessage _ =
    Hs.pure SessionStartInput
      <*> ( ( HsProtobuf.coerceOver
                @(HsProtobuf.Nested ExoMonad.Common.SessionId)
                @(Hs.Maybe ExoMonad.Common.SessionId)
            )
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 1)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 2)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 3)
              )
          )
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        ( HsProtobufAST.Prim
            ( HsProtobufAST.Named
                ( HsProtobufAST.Dots
                    (HsProtobufAST.Path ("exomonad" Hs.:| ["common", "SessionId"]))
                )
            )
        )
        (HsProtobufAST.Single "session_id")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 2)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "working_directory")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 3)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "permission_mode")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB SessionStartInput) where
  toJSONPB (SessionStartInput f1 f2 f3) =
    HsJSONPB.object
      [ "session_id"
          .= ( ( Hs.coerce
                   @(Hs.Maybe ExoMonad.Common.SessionId)
                   @(HsProtobuf.Nested ExoMonad.Common.SessionId)
               )
                 f1
             ),
        "working_directory"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
        "permission_mode"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3)
      ]
  toEncodingPB (SessionStartInput f1 f2 f3) =
    HsJSONPB.pairs
      [ "session_id"
          .= ( ( Hs.coerce
                   @(Hs.Maybe ExoMonad.Common.SessionId)
                   @(HsProtobuf.Nested ExoMonad.Common.SessionId)
               )
                 f1
             ),
        "working_directory"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
        "permission_mode"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3)
      ]

instance (HsJSONPB.FromJSONPB SessionStartInput) where
  parseJSONPB =
    HsJSONPB.withObject
      "SessionStartInput"
      ( \obj ->
          Hs.pure SessionStartInput
            <*> ( ( HsProtobuf.coerceOver
                      @(HsProtobuf.Nested ExoMonad.Common.SessionId)
                      @(Hs.Maybe ExoMonad.Common.SessionId)
                  )
                    (obj .: "session_id")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "working_directory")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "permission_mode")
                )
      )

instance (HsJSONPB.ToJSON SessionStartInput) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON SessionStartInput) where
  parseJSON = HsJSONPB.parseJSONPB

newtype SessionStartOutput
  = SessionStartOutput {sessionStartOutputSystemMessage :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData SessionStartOutput)

instance (HsProtobuf.Named SessionStartOutput) where
  nameOf _ = Hs.fromString "SessionStartOutput"

instance (HsProtobuf.HasDefault SessionStartOutput)

instance (HsProtobuf.Message SessionStartOutput) where
  encodeMessage
    _
    SessionStartOutput {sessionStartOutputSystemMessage} =
      ( HsProtobuf.encodeMessageField
          (HsProtobuf.FieldNumber 1)
          ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              sessionStartOutputSystemMessage
          )
      )
  decodeMessage _ =
    Hs.pure SessionStartOutput
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 1)
              )
          )
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "system_message")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB SessionStartOutput) where
  toJSONPB (SessionStartOutput f1) =
    HsJSONPB.object
      [ "system_message"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1)
      ]
  toEncodingPB (SessionStartOutput f1) =
    HsJSONPB.pairs
      [ "system_message"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1)
      ]

instance (HsJSONPB.FromJSONPB SessionStartOutput) where
  parseJSONPB =
    HsJSONPB.withObject
      "SessionStartOutput"
      ( \obj ->
          Hs.pure SessionStartOutput
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "system_message")
                )
      )

instance (HsJSONPB.ToJSON SessionStartOutput) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON SessionStartOutput) where
  parseJSON = HsJSONPB.parseJSONPB

data SessionEndInput
  = SessionEndInput
  { sessionEndInputSessionId :: (Hs.Maybe ExoMonad.Common.SessionId),
    sessionEndInputTranscriptPath :: Hs.Text
  }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData SessionEndInput)

instance (HsProtobuf.Named SessionEndInput) where
  nameOf _ = Hs.fromString "SessionEndInput"

instance (HsProtobuf.HasDefault SessionEndInput)

instance (HsProtobuf.Message SessionEndInput) where
  encodeMessage
    _
    SessionEndInput
      { sessionEndInputSessionId,
        sessionEndInputTranscriptPath
      } =
      Hs.mappend
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 1)
            ( ( Hs.coerce
                  @(Hs.Maybe ExoMonad.Common.SessionId)
                  @(HsProtobuf.Nested ExoMonad.Common.SessionId)
              )
                sessionEndInputSessionId
            )
        )
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 2)
            ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                sessionEndInputTranscriptPath
            )
        )
  decodeMessage _ =
    Hs.pure SessionEndInput
      <*> ( ( HsProtobuf.coerceOver
                @(HsProtobuf.Nested ExoMonad.Common.SessionId)
                @(Hs.Maybe ExoMonad.Common.SessionId)
            )
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 1)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 2)
              )
          )
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        ( HsProtobufAST.Prim
            ( HsProtobufAST.Named
                ( HsProtobufAST.Dots
                    (HsProtobufAST.Path ("exomonad" Hs.:| ["common", "SessionId"]))
                )
            )
        )
        (HsProtobufAST.Single "session_id")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 2)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "transcript_path")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB SessionEndInput) where
  toJSONPB (SessionEndInput f1 f2) =
    HsJSONPB.object
      [ "session_id"
          .= ( ( Hs.coerce
                   @(Hs.Maybe ExoMonad.Common.SessionId)
                   @(HsProtobuf.Nested ExoMonad.Common.SessionId)
               )
                 f1
             ),
        "transcript_path"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)
      ]
  toEncodingPB (SessionEndInput f1 f2) =
    HsJSONPB.pairs
      [ "session_id"
          .= ( ( Hs.coerce
                   @(Hs.Maybe ExoMonad.Common.SessionId)
                   @(HsProtobuf.Nested ExoMonad.Common.SessionId)
               )
                 f1
             ),
        "transcript_path"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)
      ]

instance (HsJSONPB.FromJSONPB SessionEndInput) where
  parseJSONPB =
    HsJSONPB.withObject
      "SessionEndInput"
      ( \obj ->
          Hs.pure SessionEndInput
            <*> ( ( HsProtobuf.coerceOver
                      @(HsProtobuf.Nested ExoMonad.Common.SessionId)
                      @(Hs.Maybe ExoMonad.Common.SessionId)
                  )
                    (obj .: "session_id")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "transcript_path")
                )
      )

instance (HsJSONPB.ToJSON SessionEndInput) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON SessionEndInput) where
  parseJSON = HsJSONPB.parseJSONPB

data SessionEndOutput
  = SessionEndOutput {}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData SessionEndOutput)

instance (HsProtobuf.Named SessionEndOutput) where
  nameOf _ = Hs.fromString "SessionEndOutput"

instance (HsProtobuf.HasDefault SessionEndOutput)

instance (HsProtobuf.Message SessionEndOutput) where
  encodeMessage _ SessionEndOutput {} = Hs.mempty
  decodeMessage _ = Hs.pure SessionEndOutput
  dotProto _ = []

instance (HsJSONPB.ToJSONPB SessionEndOutput) where
  toJSONPB SessionEndOutput = HsJSONPB.object []
  toEncodingPB SessionEndOutput = HsJSONPB.pairs []

instance (HsJSONPB.FromJSONPB SessionEndOutput) where
  parseJSONPB =
    HsJSONPB.withObject
      "SessionEndOutput"
      (\obj -> Hs.pure SessionEndOutput)

instance (HsJSONPB.ToJSON SessionEndOutput) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON SessionEndOutput) where
  parseJSON = HsJSONPB.parseJSONPB

data SubagentStopInput
  = SubagentStopInput
  { subagentStopInputSessionId :: (Hs.Maybe ExoMonad.Common.SessionId),
    subagentStopInputStopHookActive :: Hs.Bool
  }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData SubagentStopInput)

instance (HsProtobuf.Named SubagentStopInput) where
  nameOf _ = Hs.fromString "SubagentStopInput"

instance (HsProtobuf.HasDefault SubagentStopInput)

instance (HsProtobuf.Message SubagentStopInput) where
  encodeMessage
    _
    SubagentStopInput
      { subagentStopInputSessionId,
        subagentStopInputStopHookActive
      } =
      Hs.mappend
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 1)
            ( ( Hs.coerce
                  @(Hs.Maybe ExoMonad.Common.SessionId)
                  @(HsProtobuf.Nested ExoMonad.Common.SessionId)
              )
                subagentStopInputSessionId
            )
        )
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 2)
            subagentStopInputStopHookActive
        )
  decodeMessage _ =
    Hs.pure SubagentStopInput
      <*> ( ( HsProtobuf.coerceOver
                @(HsProtobuf.Nested ExoMonad.Common.SessionId)
                @(Hs.Maybe ExoMonad.Common.SessionId)
            )
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 1)
              )
          )
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 2)
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        ( HsProtobufAST.Prim
            ( HsProtobufAST.Named
                ( HsProtobufAST.Dots
                    (HsProtobufAST.Path ("exomonad" Hs.:| ["common", "SessionId"]))
                )
            )
        )
        (HsProtobufAST.Single "session_id")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 2)
        (HsProtobufAST.Prim HsProtobufAST.Bool)
        (HsProtobufAST.Single "stop_hook_active")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB SubagentStopInput) where
  toJSONPB (SubagentStopInput f1 f2) =
    HsJSONPB.object
      [ "session_id"
          .= ( ( Hs.coerce
                   @(Hs.Maybe ExoMonad.Common.SessionId)
                   @(HsProtobuf.Nested ExoMonad.Common.SessionId)
               )
                 f1
             ),
        "stop_hook_active" .= f2
      ]
  toEncodingPB (SubagentStopInput f1 f2) =
    HsJSONPB.pairs
      [ "session_id"
          .= ( ( Hs.coerce
                   @(Hs.Maybe ExoMonad.Common.SessionId)
                   @(HsProtobuf.Nested ExoMonad.Common.SessionId)
               )
                 f1
             ),
        "stop_hook_active" .= f2
      ]

instance (HsJSONPB.FromJSONPB SubagentStopInput) where
  parseJSONPB =
    HsJSONPB.withObject
      "SubagentStopInput"
      ( \obj ->
          Hs.pure SubagentStopInput
            <*> ( ( HsProtobuf.coerceOver
                      @(HsProtobuf.Nested ExoMonad.Common.SessionId)
                      @(Hs.Maybe ExoMonad.Common.SessionId)
                  )
                    (obj .: "session_id")
                )
            <*> obj .: "stop_hook_active"
      )

instance (HsJSONPB.ToJSON SubagentStopInput) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON SubagentStopInput) where
  parseJSON = HsJSONPB.parseJSONPB

data SubagentStopOutput
  = SubagentStopOutput
  { subagentStopOutputDecision :: (HsProtobuf.Enumerated ExoMonad.Hook.StopDecision),
    subagentStopOutputReason :: Hs.Text
  }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData SubagentStopOutput)

instance (HsProtobuf.Named SubagentStopOutput) where
  nameOf _ = Hs.fromString "SubagentStopOutput"

instance (HsProtobuf.HasDefault SubagentStopOutput)

instance (HsProtobuf.Message SubagentStopOutput) where
  encodeMessage
    _
    SubagentStopOutput
      { subagentStopOutputDecision,
        subagentStopOutputReason
      } =
      Hs.mappend
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 1)
            subagentStopOutputDecision
        )
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 2)
            ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                subagentStopOutputReason
            )
        )
  decodeMessage _ =
    Hs.pure SubagentStopOutput
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 1)
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 2)
              )
          )
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        ( HsProtobufAST.Prim
            (HsProtobufAST.Named (HsProtobufAST.Single "StopDecision"))
        )
        (HsProtobufAST.Single "decision")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 2)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "reason")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB SubagentStopOutput) where
  toJSONPB (SubagentStopOutput f1 f2) =
    HsJSONPB.object
      [ "decision" .= f1,
        "reason" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)
      ]
  toEncodingPB (SubagentStopOutput f1 f2) =
    HsJSONPB.pairs
      [ "decision" .= f1,
        "reason" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)
      ]

instance (HsJSONPB.FromJSONPB SubagentStopOutput) where
  parseJSONPB =
    HsJSONPB.withObject
      "SubagentStopOutput"
      ( \obj ->
          Hs.pure SubagentStopOutput
            <*> obj .: "decision"
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "reason")
                )
      )

instance (HsJSONPB.ToJSON SubagentStopOutput) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON SubagentStopOutput) where
  parseJSON = HsJSONPB.parseJSONPB

data HookInput
  = HookInput
  { hookInputHookType :: (HsProtobuf.Enumerated ExoMonad.Hook.HookType),
    hookInputInput :: (Hs.Maybe HookInputInput)
  }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData HookInput)

instance (HsProtobuf.Named HookInput) where
  nameOf _ = Hs.fromString "HookInput"

instance (HsProtobuf.HasDefault HookInput)

instance (HsProtobuf.Message HookInput) where
  encodeMessage _ HookInput {hookInputHookType, hookInputInput} =
    Hs.mappend
      ( HsProtobuf.encodeMessageField
          (HsProtobuf.FieldNumber 1)
          hookInputHookType
      )
      ( case hookInputInput of
          Hs.Nothing -> Hs.mempty
          Hs.Just x ->
            case x of
              HookInputInputPreToolUse y ->
                HsProtobuf.encodeMessageField
                  (HsProtobuf.FieldNumber 2)
                  ( ( Hs.coerce
                        @(Hs.Maybe ExoMonad.Hook.PreToolUseInput)
                        @(HsProtobuf.Nested ExoMonad.Hook.PreToolUseInput)
                    )
                      (Hs.Just y)
                  )
              HookInputInputPostToolUse y ->
                HsProtobuf.encodeMessageField
                  (HsProtobuf.FieldNumber 3)
                  ( ( Hs.coerce
                        @(Hs.Maybe ExoMonad.Hook.PostToolUseInput)
                        @(HsProtobuf.Nested ExoMonad.Hook.PostToolUseInput)
                    )
                      (Hs.Just y)
                  )
              HookInputInputSessionStart y ->
                HsProtobuf.encodeMessageField
                  (HsProtobuf.FieldNumber 4)
                  ( ( Hs.coerce
                        @(Hs.Maybe ExoMonad.Hook.SessionStartInput)
                        @(HsProtobuf.Nested ExoMonad.Hook.SessionStartInput)
                    )
                      (Hs.Just y)
                  )
              HookInputInputSessionEnd y ->
                HsProtobuf.encodeMessageField
                  (HsProtobuf.FieldNumber 5)
                  ( ( Hs.coerce
                        @(Hs.Maybe ExoMonad.Hook.SessionEndInput)
                        @(HsProtobuf.Nested ExoMonad.Hook.SessionEndInput)
                    )
                      (Hs.Just y)
                  )
              HookInputInputSubagentStop y ->
                HsProtobuf.encodeMessageField
                  (HsProtobuf.FieldNumber 6)
                  ( ( Hs.coerce
                        @(Hs.Maybe ExoMonad.Hook.SubagentStopInput)
                        @(HsProtobuf.Nested ExoMonad.Hook.SubagentStopInput)
                    )
                      (Hs.Just y)
                  )
      )
  decodeMessage _ =
    Hs.pure HookInput
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 1)
      <*> HsProtobuf.oneof
        Hs.Nothing
        [ ( (HsProtobuf.FieldNumber 2),
            Hs.pure (Hs.fmap HookInputInputPreToolUse)
              <*> ( ( HsProtobuf.coerceOver
                        @(HsProtobuf.Nested ExoMonad.Hook.PreToolUseInput)
                        @(Hs.Maybe ExoMonad.Hook.PreToolUseInput)
                    )
                      HsProtobuf.decodeMessageField
                  )
          ),
          ( (HsProtobuf.FieldNumber 3),
            Hs.pure (Hs.fmap HookInputInputPostToolUse)
              <*> ( ( HsProtobuf.coerceOver
                        @(HsProtobuf.Nested ExoMonad.Hook.PostToolUseInput)
                        @(Hs.Maybe ExoMonad.Hook.PostToolUseInput)
                    )
                      HsProtobuf.decodeMessageField
                  )
          ),
          ( (HsProtobuf.FieldNumber 4),
            Hs.pure (Hs.fmap HookInputInputSessionStart)
              <*> ( ( HsProtobuf.coerceOver
                        @(HsProtobuf.Nested ExoMonad.Hook.SessionStartInput)
                        @(Hs.Maybe ExoMonad.Hook.SessionStartInput)
                    )
                      HsProtobuf.decodeMessageField
                  )
          ),
          ( (HsProtobuf.FieldNumber 5),
            Hs.pure (Hs.fmap HookInputInputSessionEnd)
              <*> ( ( HsProtobuf.coerceOver
                        @(HsProtobuf.Nested ExoMonad.Hook.SessionEndInput)
                        @(Hs.Maybe ExoMonad.Hook.SessionEndInput)
                    )
                      HsProtobuf.decodeMessageField
                  )
          ),
          ( (HsProtobuf.FieldNumber 6),
            Hs.pure (Hs.fmap HookInputInputSubagentStop)
              <*> ( ( HsProtobuf.coerceOver
                        @(HsProtobuf.Nested ExoMonad.Hook.SubagentStopInput)
                        @(Hs.Maybe ExoMonad.Hook.SubagentStopInput)
                    )
                      HsProtobuf.decodeMessageField
                  )
          )
        ]
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        ( HsProtobufAST.Prim
            (HsProtobufAST.Named (HsProtobufAST.Single "HookType"))
        )
        (HsProtobufAST.Single "hook_type")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB HookInput) where
  toJSONPB (HookInput f1 f2_or_f3_or_f4_or_f5_or_f6) =
    HsJSONPB.object
      [ "hook_type" .= f1,
        ( let encodeInput =
                ( case f2_or_f3_or_f4_or_f5_or_f6 of
                    Hs.Just (HookInputInputPreToolUse f2) ->
                      HsJSONPB.pair "pre_tool_use" f2
                    Hs.Just (HookInputInputPostToolUse f3) ->
                      HsJSONPB.pair "post_tool_use" f3
                    Hs.Just (HookInputInputSessionStart f4) ->
                      HsJSONPB.pair "session_start" f4
                    Hs.Just (HookInputInputSessionEnd f5) ->
                      HsJSONPB.pair "session_end" f5
                    Hs.Just (HookInputInputSubagentStop f6) ->
                      HsJSONPB.pair "subagent_stop" f6
                    Hs.Nothing -> Hs.mempty
                )
           in ( \options ->
                  if HsJSONPB.optEmitNamedOneof options
                    then
                      ("input" .= HsJSONPB.objectOrNull [encodeInput] options) options
                    else
                      encodeInput options
              )
        )
      ]
  toEncodingPB (HookInput f1 f2_or_f3_or_f4_or_f5_or_f6) =
    HsJSONPB.pairs
      [ "hook_type" .= f1,
        ( let encodeInput =
                ( case f2_or_f3_or_f4_or_f5_or_f6 of
                    Hs.Just (HookInputInputPreToolUse f2) ->
                      HsJSONPB.pair "pre_tool_use" f2
                    Hs.Just (HookInputInputPostToolUse f3) ->
                      HsJSONPB.pair "post_tool_use" f3
                    Hs.Just (HookInputInputSessionStart f4) ->
                      HsJSONPB.pair "session_start" f4
                    Hs.Just (HookInputInputSessionEnd f5) ->
                      HsJSONPB.pair "session_end" f5
                    Hs.Just (HookInputInputSubagentStop f6) ->
                      HsJSONPB.pair "subagent_stop" f6
                    Hs.Nothing -> Hs.mempty
                )
           in ( \options ->
                  if HsJSONPB.optEmitNamedOneof options
                    then
                      ("input" .= HsJSONPB.pairsOrNull [encodeInput] options) options
                    else
                      encodeInput options
              )
        )
      ]

instance (HsJSONPB.FromJSONPB HookInput) where
  parseJSONPB =
    HsJSONPB.withObject
      "HookInput"
      ( \obj ->
          Hs.pure HookInput
            <*> obj .: "hook_type"
            <*> ( let parseInput parseObj =
                        Hs.msum
                          [ Hs.Just Hs.. HookInputInputPreToolUse
                              <$> HsJSONPB.parseField parseObj "pre_tool_use",
                            Hs.Just Hs.. HookInputInputPostToolUse
                              <$> HsJSONPB.parseField parseObj "post_tool_use",
                            Hs.Just Hs.. HookInputInputSessionStart
                              <$> HsJSONPB.parseField parseObj "session_start",
                            Hs.Just Hs.. HookInputInputSessionEnd
                              <$> HsJSONPB.parseField parseObj "session_end",
                            Hs.Just Hs.. HookInputInputSubagentStop
                              <$> HsJSONPB.parseField parseObj "subagent_stop",
                            Hs.pure Hs.Nothing
                          ]
                   in (obj .: "input" Hs.>>= HsJSONPB.withObject "input" parseInput)
                        <|> (parseInput obj)
                )
      )

instance (HsJSONPB.ToJSON HookInput) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON HookInput) where
  parseJSON = HsJSONPB.parseJSONPB

data HookInputInput
  = HookInputInputPreToolUse ExoMonad.Hook.PreToolUseInput
  | HookInputInputPostToolUse ExoMonad.Hook.PostToolUseInput
  | HookInputInputSessionStart ExoMonad.Hook.SessionStartInput
  | HookInputInputSessionEnd ExoMonad.Hook.SessionEndInput
  | HookInputInputSubagentStop ExoMonad.Hook.SubagentStopInput
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData HookInputInput)

instance (HsProtobuf.Named HookInputInput) where
  nameOf _ = Hs.fromString "HookInputInput"

data HookOutput
  = HookOutput
  { hookOutputContinue_ :: Hs.Bool,
    hookOutputStopReason :: Hs.Text,
    hookOutputSuppressOutput :: Hs.Bool,
    hookOutputSystemMessage :: Hs.Text,
    hookOutputOutput :: (Hs.Maybe HookOutputOutput)
  }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData HookOutput)

instance (HsProtobuf.Named HookOutput) where
  nameOf _ = Hs.fromString "HookOutput"

instance (HsProtobuf.HasDefault HookOutput)

instance (HsProtobuf.Message HookOutput) where
  encodeMessage
    _
    HookOutput
      { hookOutputContinue_,
        hookOutputStopReason,
        hookOutputSuppressOutput,
        hookOutputSystemMessage,
        hookOutputOutput
      } =
      Hs.mappend
        ( Hs.mappend
            ( Hs.mappend
                ( Hs.mappend
                    ( HsProtobuf.encodeMessageField
                        (HsProtobuf.FieldNumber 1)
                        hookOutputContinue_
                    )
                    ( HsProtobuf.encodeMessageField
                        (HsProtobuf.FieldNumber 2)
                        ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                            hookOutputStopReason
                        )
                    )
                )
                ( HsProtobuf.encodeMessageField
                    (HsProtobuf.FieldNumber 3)
                    hookOutputSuppressOutput
                )
            )
            ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 4)
                ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                    hookOutputSystemMessage
                )
            )
        )
        ( case hookOutputOutput of
            Hs.Nothing -> Hs.mempty
            Hs.Just x ->
              case x of
                HookOutputOutputPreToolUse y ->
                  HsProtobuf.encodeMessageField
                    (HsProtobuf.FieldNumber 10)
                    ( ( Hs.coerce
                          @(Hs.Maybe ExoMonad.Hook.PreToolUseOutput)
                          @(HsProtobuf.Nested ExoMonad.Hook.PreToolUseOutput)
                      )
                        (Hs.Just y)
                    )
                HookOutputOutputPostToolUse y ->
                  HsProtobuf.encodeMessageField
                    (HsProtobuf.FieldNumber 11)
                    ( ( Hs.coerce
                          @(Hs.Maybe ExoMonad.Hook.PostToolUseOutput)
                          @(HsProtobuf.Nested ExoMonad.Hook.PostToolUseOutput)
                      )
                        (Hs.Just y)
                    )
                HookOutputOutputSessionStart y ->
                  HsProtobuf.encodeMessageField
                    (HsProtobuf.FieldNumber 12)
                    ( ( Hs.coerce
                          @(Hs.Maybe ExoMonad.Hook.SessionStartOutput)
                          @(HsProtobuf.Nested ExoMonad.Hook.SessionStartOutput)
                      )
                        (Hs.Just y)
                    )
                HookOutputOutputSessionEnd y ->
                  HsProtobuf.encodeMessageField
                    (HsProtobuf.FieldNumber 13)
                    ( ( Hs.coerce
                          @(Hs.Maybe ExoMonad.Hook.SessionEndOutput)
                          @(HsProtobuf.Nested ExoMonad.Hook.SessionEndOutput)
                      )
                        (Hs.Just y)
                    )
                HookOutputOutputSubagentStop y ->
                  HsProtobuf.encodeMessageField
                    (HsProtobuf.FieldNumber 14)
                    ( ( Hs.coerce
                          @(Hs.Maybe ExoMonad.Hook.SubagentStopOutput)
                          @(HsProtobuf.Nested ExoMonad.Hook.SubagentStopOutput)
                      )
                        (Hs.Just y)
                    )
        )
  decodeMessage _ =
    Hs.pure HookOutput
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 1)
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 2)
              )
          )
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 3)
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 4)
              )
          )
      <*> HsProtobuf.oneof
        Hs.Nothing
        [ ( (HsProtobuf.FieldNumber 10),
            Hs.pure (Hs.fmap HookOutputOutputPreToolUse)
              <*> ( ( HsProtobuf.coerceOver
                        @(HsProtobuf.Nested ExoMonad.Hook.PreToolUseOutput)
                        @(Hs.Maybe ExoMonad.Hook.PreToolUseOutput)
                    )
                      HsProtobuf.decodeMessageField
                  )
          ),
          ( (HsProtobuf.FieldNumber 11),
            Hs.pure (Hs.fmap HookOutputOutputPostToolUse)
              <*> ( ( HsProtobuf.coerceOver
                        @(HsProtobuf.Nested ExoMonad.Hook.PostToolUseOutput)
                        @(Hs.Maybe ExoMonad.Hook.PostToolUseOutput)
                    )
                      HsProtobuf.decodeMessageField
                  )
          ),
          ( (HsProtobuf.FieldNumber 12),
            Hs.pure (Hs.fmap HookOutputOutputSessionStart)
              <*> ( ( HsProtobuf.coerceOver
                        @(HsProtobuf.Nested ExoMonad.Hook.SessionStartOutput)
                        @(Hs.Maybe ExoMonad.Hook.SessionStartOutput)
                    )
                      HsProtobuf.decodeMessageField
                  )
          ),
          ( (HsProtobuf.FieldNumber 13),
            Hs.pure (Hs.fmap HookOutputOutputSessionEnd)
              <*> ( ( HsProtobuf.coerceOver
                        @(HsProtobuf.Nested ExoMonad.Hook.SessionEndOutput)
                        @(Hs.Maybe ExoMonad.Hook.SessionEndOutput)
                    )
                      HsProtobuf.decodeMessageField
                  )
          ),
          ( (HsProtobuf.FieldNumber 14),
            Hs.pure (Hs.fmap HookOutputOutputSubagentStop)
              <*> ( ( HsProtobuf.coerceOver
                        @(HsProtobuf.Nested ExoMonad.Hook.SubagentStopOutput)
                        @(Hs.Maybe ExoMonad.Hook.SubagentStopOutput)
                    )
                      HsProtobuf.decodeMessageField
                  )
          )
        ]
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.Bool)
        (HsProtobufAST.Single "continue_")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 2)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "stop_reason")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 3)
        (HsProtobufAST.Prim HsProtobufAST.Bool)
        (HsProtobufAST.Single "suppress_output")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 4)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "system_message")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB HookOutput) where
  toJSONPB (HookOutput f1 f2 f3 f4 f10_or_f11_or_f12_or_f13_or_f14) =
    HsJSONPB.object
      [ "continue_" .= f1,
        "stop_reason"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
        "suppress_output" .= f3,
        "system_message"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f4),
        ( let encodeOutput =
                ( case f10_or_f11_or_f12_or_f13_or_f14 of
                    Hs.Just (HookOutputOutputPreToolUse f10) ->
                      HsJSONPB.pair "pre_tool_use" f10
                    Hs.Just (HookOutputOutputPostToolUse f11) ->
                      HsJSONPB.pair "post_tool_use" f11
                    Hs.Just (HookOutputOutputSessionStart f12) ->
                      HsJSONPB.pair "session_start" f12
                    Hs.Just (HookOutputOutputSessionEnd f13) ->
                      HsJSONPB.pair "session_end" f13
                    Hs.Just (HookOutputOutputSubagentStop f14) ->
                      HsJSONPB.pair "subagent_stop" f14
                    Hs.Nothing -> Hs.mempty
                )
           in ( \options ->
                  if HsJSONPB.optEmitNamedOneof options
                    then
                      ("output" .= HsJSONPB.objectOrNull [encodeOutput] options) options
                    else
                      encodeOutput options
              )
        )
      ]
  toEncodingPB
    (HookOutput f1 f2 f3 f4 f10_or_f11_or_f12_or_f13_or_f14) =
      HsJSONPB.pairs
        [ "continue_" .= f1,
          "stop_reason"
            .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
          "suppress_output" .= f3,
          "system_message"
            .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f4),
          ( let encodeOutput =
                  ( case f10_or_f11_or_f12_or_f13_or_f14 of
                      Hs.Just (HookOutputOutputPreToolUse f10) ->
                        HsJSONPB.pair "pre_tool_use" f10
                      Hs.Just (HookOutputOutputPostToolUse f11) ->
                        HsJSONPB.pair "post_tool_use" f11
                      Hs.Just (HookOutputOutputSessionStart f12) ->
                        HsJSONPB.pair "session_start" f12
                      Hs.Just (HookOutputOutputSessionEnd f13) ->
                        HsJSONPB.pair "session_end" f13
                      Hs.Just (HookOutputOutputSubagentStop f14) ->
                        HsJSONPB.pair "subagent_stop" f14
                      Hs.Nothing -> Hs.mempty
                  )
             in ( \options ->
                    if HsJSONPB.optEmitNamedOneof options
                      then
                        ("output" .= HsJSONPB.pairsOrNull [encodeOutput] options) options
                      else
                        encodeOutput options
                )
          )
        ]

instance (HsJSONPB.FromJSONPB HookOutput) where
  parseJSONPB =
    HsJSONPB.withObject
      "HookOutput"
      ( \obj ->
          Hs.pure HookOutput
            <*> obj .: "continue_"
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "stop_reason")
                )
            <*> obj .: "suppress_output"
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "system_message")
                )
            <*> ( let parseOutput parseObj =
                        Hs.msum
                          [ Hs.Just Hs.. HookOutputOutputPreToolUse
                              <$> HsJSONPB.parseField parseObj "pre_tool_use",
                            Hs.Just Hs.. HookOutputOutputPostToolUse
                              <$> HsJSONPB.parseField parseObj "post_tool_use",
                            Hs.Just Hs.. HookOutputOutputSessionStart
                              <$> HsJSONPB.parseField parseObj "session_start",
                            Hs.Just Hs.. HookOutputOutputSessionEnd
                              <$> HsJSONPB.parseField parseObj "session_end",
                            Hs.Just Hs.. HookOutputOutputSubagentStop
                              <$> HsJSONPB.parseField parseObj "subagent_stop",
                            Hs.pure Hs.Nothing
                          ]
                   in (obj .: "output" Hs.>>= HsJSONPB.withObject "output" parseOutput)
                        <|> (parseOutput obj)
                )
      )

instance (HsJSONPB.ToJSON HookOutput) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON HookOutput) where
  parseJSON = HsJSONPB.parseJSONPB

data HookOutputOutput
  = HookOutputOutputPreToolUse ExoMonad.Hook.PreToolUseOutput
  | HookOutputOutputPostToolUse ExoMonad.Hook.PostToolUseOutput
  | HookOutputOutputSessionStart ExoMonad.Hook.SessionStartOutput
  | HookOutputOutputSessionEnd ExoMonad.Hook.SessionEndOutput
  | HookOutputOutputSubagentStop ExoMonad.Hook.SubagentStopOutput
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData HookOutputOutput)

instance (HsProtobuf.Named HookOutputOutput) where
  nameOf _ = Hs.fromString "HookOutputOutput"
