// Auto-generated by generate-ts-package - DO NOT EDIT

import type { GraphId } from './graphs.js';
import type { GraphWasmExports } from './exports.js';

export interface GraphFns {
  initialize: (json: string) => string;
  step: (json: string) => string;
  getGraphInfo: () => string;
  getGraphState: () => string;
}

/**
 * Get type-safe graph functions for a specific graph.
 *
 * Uses unified FFI - graphId is baked in, caller just passes data.
 * No more switch statement needed - all graphs use same 4 exports.
 */
export function getGraphFns(graphId: GraphId, exports: GraphWasmExports): GraphFns {
  return {
    initialize: (json: string) => exports.initialize(graphId, json),
    step: (json: string) => exports.step(graphId, json),
    getGraphInfo: () => exports.getGraphInfo(graphId),
    getGraphState: () => exports.getGraphState(graphId),
  };
}
