// Auto-generated by generate-ts-package - DO NOT EDIT

// Unified WASM FFI interface - 4 exports that take graphId as parameter
// This replaces the previous 4N exports (4 per graph)
export interface GraphWasmExports {
  // Unified FFI (new)
  initialize: (graphId: string, json: string) => string;
  step: (graphId: string, json: string) => string;
  getGraphInfo: (graphId: string) => string;
  getGraphState: (graphId: string) => string;
}
