{-# LANGUAGE StrictData #-}
-- | Theme system for Tidepool GUI
--
-- Provides a flexible theming system with color palettes and CSS generation.
-- Domain-specific themes (like DM.GUI.Theme) define the actual colors.
module Tidepool.GUI.Theme
  ( -- * Theme type
    Theme(..)
  , ColorPalette(..)
    -- * CSS generation
  , themeToCSS
  , applyTheme
    -- * Utility
  , cssVar
  , rgba
  ) where

import Control.Monad (void)
import Data.Text (Text)
import qualified Data.Text as T
import Graphics.UI.Threepenny.Core

-- | Color palette for a theme
data ColorPalette = ColorPalette
  { cpBackground    :: Text  -- ^ Primary background
  , cpBackgroundAlt :: Text  -- ^ Secondary/card background
  , cpBackgroundHover :: Text -- ^ Hover state background
  , cpAccent        :: Text  -- ^ Primary accent color
  , cpAccentDim     :: Text  -- ^ Dimmed accent
  , cpText          :: Text  -- ^ Primary text
  , cpTextMuted     :: Text  -- ^ Secondary/muted text
  , cpTextDim       :: Text  -- ^ Very muted text
  , cpSuccess       :: Text  -- ^ Success/positive
  , cpWarning       :: Text  -- ^ Warning/caution
  , cpDanger        :: Text  -- ^ Danger/negative
  , cpCritical      :: Text  -- ^ Critical/special
  }
  deriving (Show, Eq)

-- | A complete theme definition
data Theme = Theme
  { themeName    :: Text
  , themeColors  :: ColorPalette
  , themeFontMain :: Text
  , themeFontMono :: Text
  }
  deriving (Show, Eq)

-- | Generate CSS custom properties from a theme
themeToCSS :: Theme -> Text
themeToCSS theme = T.unlines
  [ ":root {"
  , "  --bg-primary: " <> colors.cpBackground <> ";"
  , "  --bg-secondary: " <> colors.cpBackgroundAlt <> ";"
  , "  --bg-hover: " <> colors.cpBackgroundHover <> ";"
  , "  --accent: " <> colors.cpAccent <> ";"
  , "  --accent-dim: " <> colors.cpAccentDim <> ";"
  , "  --text-primary: " <> colors.cpText <> ";"
  , "  --text-muted: " <> colors.cpTextMuted <> ";"
  , "  --text-dim: " <> colors.cpTextDim <> ";"
  , "  --success: " <> colors.cpSuccess <> ";"
  , "  --warning: " <> colors.cpWarning <> ";"
  , "  --danger: " <> colors.cpDanger <> ";"
  , "  --critical: " <> colors.cpCritical <> ";"
  , "  --font-main: " <> theme.themeFontMain <> ";"
  , "  --font-mono: " <> theme.themeFontMono <> ";"
  , "}"
  , ""
  , "* { box-sizing: border-box; margin: 0; padding: 0; }"
  , ""
  , "body {"
  , "  background: var(--bg-primary);"
  , "  color: var(--text-primary);"
  , "  font-family: var(--font-main);"
  , "  font-size: 16px;"
  , "  line-height: 1.5;"
  , "}"
  , ""
  , "/* Layout */"
  , ".tidepool-root {"
  , "  display: flex;"
  , "  height: 100vh;"
  , "  overflow: hidden;"
  , "}"
  , ""
  , ".sidebar {"
  , "  width: 200px;"
  , "  background: var(--bg-secondary);"
  , "  padding: 16px;"
  , "  overflow-y: auto;"
  , "  border-right: 1px solid var(--bg-hover);"
  , "}"
  , ""
  , ".main-panel {"
  , "  flex: 1;"
  , "  display: flex;"
  , "  flex-direction: column;"
  , "  overflow: hidden;"
  , "}"
  , ""
  , ".debug-panel {"
  , "  width: 280px;"
  , "  background: var(--bg-secondary);"
  , "  padding: 16px;"
  , "  overflow-y: auto;"
  , "  border-left: 1px solid var(--bg-hover);"
  , "  font-family: var(--font-mono);"
  , "  font-size: 12px;"
  , "}"
  , ""
  , ".debug-panel.collapsed {"
  , "  width: 40px;"
  , "  padding: 8px;"
  , "}"
  , ""
  , "/* Header */"
  , ".mood-header {"
  , "  padding: 16px;"
  , "  background: var(--bg-secondary);"
  , "  border-bottom: 1px solid var(--bg-hover);"
  , "}"
  , ""
  , ".mood-label {"
  , "  font-size: 12px;"
  , "  font-weight: bold;"
  , "  color: var(--accent);"
  , "  text-transform: uppercase;"
  , "  letter-spacing: 1px;"
  , "}"
  , ""
  , ".mood-description {"
  , "  color: var(--text-muted);"
  , "  font-size: 14px;"
  , "}"
  , ""
  , "/* Tabs */"
  , ".tab-bar {"
  , "  display: flex;"
  , "  background: var(--bg-secondary);"
  , "  border-bottom: 1px solid var(--bg-hover);"
  , "}"
  , ""
  , ".tab {"
  , "  padding: 8px 16px;"
  , "  cursor: pointer;"
  , "  border-bottom: 2px solid transparent;"
  , "  color: var(--text-muted);"
  , "}"
  , ""
  , ".tab:hover {"
  , "  color: var(--text-primary);"
  , "}"
  , ""
  , ".tab.active {"
  , "  color: var(--accent);"
  , "  border-bottom-color: var(--accent);"
  , "}"
  , ""
  , ".tab:focus {"
  , "  outline: 2px solid var(--accent);"
  , "  outline-offset: -2px;"
  , "}"
  , ""
  , "/* Content */"
  , ".content-area {"
  , "  flex: 1;"
  , "  overflow-y: auto;"
  , "  padding: 16px;"
  , "}"
  , ""
  , "/* Narrative */"
  , ".narrative-entry {"
  , "  margin-bottom: 12px;"
  , "}"
  , ""
  , ".player-action {"
  , "  color: var(--accent);"
  , "  font-style: italic;"
  , "}"
  , ""
  , ".speech-bubble {"
  , "  background: var(--bg-secondary);"
  , "  border-radius: 8px;"
  , "  padding: 12px;"
  , "  margin: 8px 0;"
  , "  border-left: 3px solid var(--accent);"
  , "}"
  , ""
  , ".npc-name {"
  , "  font-weight: bold;"
  , "  color: var(--accent);"
  , "  font-size: 12px;"
  , "  text-transform: uppercase;"
  , "  letter-spacing: 0.5px;"
  , "  margin-bottom: 4px;"
  , "  display: block;"
  , "}"
  , ""
  , ".npc-speech {"
  , "  color: var(--text-primary);"
  , "  font-style: italic;"
  , "}"
  , ""
  , ".dm-narration {"
  , "  color: var(--text-primary);"
  , "  line-height: 1.6;"
  , "}"
  , ""
  , ".environment-shift {"
  , "  color: var(--text-muted);"
  , "  font-style: italic;"
  , "  padding: 8px 12px;"
  , "  border-left: 2px solid var(--text-dim);"
  , "  margin: 12px 0;"
  , "}"
  , ""
  , ".revelation {"
  , "  color: var(--accent);"
  , "  padding: 8px 12px;"
  , "  background: var(--bg-secondary);"
  , "  border-radius: 4px;"
  , "  text-align: center;"
  , "}"
  , ""
  , ".revelation-icon {"
  , "  color: var(--critical);"
  , "}"
  , ""
  , ".clock-tick {"
  , "  color: var(--warning);"
  , "  font-size: 13px;"
  , "  font-family: var(--font-mono);"
  , "  padding: 4px 0;"
  , "}"
  , ""
  , ".narrative-placeholder {"
  , "  color: var(--text-dim);"
  , "  font-style: italic;"
  , "  text-align: center;"
  , "  padding: 32px;"
  , "}"
  , ""
  , ".input-prompt {"
  , "  color: var(--text-muted);"
  , "  font-size: 14px;"
  , "  margin-bottom: 8px;"
  , "}"
  , ""
  , ".choice-prompt {"
  , "  color: var(--text-primary);"
  , "  font-size: 14px;"
  , "  margin-bottom: 12px;"
  , "}"
  , ""
  , "/* Input */"
  , ".input-area {"
  , "  padding: 16px;"
  , "  background: var(--bg-secondary);"
  , "  border-top: 1px solid var(--bg-hover);"
  , "}"
  , ""
  , ".text-input-container {"
  , "  display: flex;"
  , "  flex-direction: column;"
  , "  gap: 8px;"
  , "}"
  , ""
  , ".text-input-row {"
  , "  display: flex;"
  , "  gap: 8px;"
  , "}"
  , ""
  , ".text-input {"
  , "  flex: 1;"
  , "  padding: 12px;"
  , "  background: var(--bg-primary);"
  , "  border: 1px solid var(--bg-hover);"
  , "  border-radius: 4px;"
  , "  color: var(--text-primary);"
  , "  font-family: inherit;"
  , "  font-size: 14px;"
  , "}"
  , ""
  , ".text-input:focus {"
  , "  outline: none;"
  , "  border-color: var(--accent);"
  , "}"
  , ""
  , ".submit-btn {"
  , "  padding: 12px 24px;"
  , "  background: var(--accent);"
  , "  border: none;"
  , "  border-radius: 4px;"
  , "  color: var(--bg-primary);"
  , "  font-weight: bold;"
  , "  cursor: pointer;"
  , "}"
  , ""
  , ".submit-btn:hover {"
  , "  opacity: 0.9;"
  , "}"
  , ""
  , ".submit-btn:focus {"
  , "  outline: 2px solid var(--accent);"
  , "  outline-offset: 2px;"
  , "}"
  , ""
  , ".submit-btn:active {"
  , "  transform: translateY(1px);"
  , "}"
  , ""
  , "/* Suggestion Buttons */"
  , ".suggestions-container {"
  , "  display: flex;"
  , "  flex-wrap: wrap;"
  , "  gap: 8px;"
  , "  margin-bottom: 12px;"
  , "}"
  , ""
  , ".suggestion-btn {"
  , "  padding: 8px 16px;"
  , "  background: var(--bg-hover);"
  , "  border: 1px solid var(--bg-hover);"
  , "  border-radius: 4px;"
  , "  color: var(--text-secondary);"
  , "  font-family: inherit;"
  , "  font-size: 13px;"
  , "  cursor: pointer;"
  , "  transition: all 0.15s ease;"
  , "}"
  , ""
  , ".suggestion-btn:hover {"
  , "  background: var(--bg-primary);"
  , "  border-color: var(--accent);"
  , "  color: var(--accent);"
  , "}"
  , ""
  , ".suggestion-btn:focus {"
  , "  outline: 2px solid var(--accent);"
  , "  outline-offset: 2px;"
  , "}"
  , ""
  , ".suggestion-btn:active {"
  , "  transform: translateY(1px);"
  , "}"
  , ""
  , "/* Choice Cards */"
  , ".choice-wrapper {"
  , "  display: flex;"
  , "  flex-direction: column;"
  , "  gap: 12px;"
  , "}"
  , ""
  , ".choice-container {"
  , "  display: flex;"
  , "  flex-wrap: wrap;"
  , "  gap: 12px;"
  , "}"
  , ""
  , ".choice-card {"
  , "  padding: 16px 24px;"
  , "  background: var(--bg-secondary);"
  , "  border: 2px solid var(--bg-hover);"
  , "  border-radius: 8px;"
  , "  cursor: pointer;"
  , "  transition: all 0.2s;"
  , "}"
  , ""
  , ".choice-card:hover, .choice-card:focus {"
  , "  border-color: var(--accent);"
  , "  background: var(--bg-hover);"
  , "  outline: none;"
  , "}"
  , ""
  , ".choice-card:active {"
  , "  transform: translateY(1px);"
  , "  background: var(--bg-primary);"
  , "}"
  , ""
  , ".choice-num {"
  , "  color: var(--accent);"
  , "  font-weight: bold;"
  , "  opacity: 0.7;"
  , "}"
  , ""
  , "/* Dice */"
  , ".dice-wrapper {"
  , "  display: flex;"
  , "  flex-direction: column;"
  , "  gap: 12px;"
  , "}"
  , ""
  , ".dice-container {"
  , "  display: flex;"
  , "  gap: 16px;"
  , "  flex-wrap: wrap;"
  , "}"
  , ""
  , ".dice-card {"
  , "  position: relative;"
  , "  display: flex;"
  , "  flex-direction: column;"
  , "  align-items: center;"
  , "  padding: 16px;"
  , "  padding-top: 24px;"  -- Extra space for number hint
  , "  background: var(--bg-secondary);"
  , "  border: 3px solid var(--bg-hover);"
  , "  border-radius: 8px;"
  , "  cursor: pointer;"
  , "  transition: all 0.2s;"
  , "  min-width: 80px;"
  , "}"
  , ""
  , ".dice-card:hover, .dice-card:focus {"
  , "  transform: translateY(-2px);"
  , "  outline: none;"
  , "  box-shadow: 0 4px 12px rgba(0,0,0,0.3);"
  , "}"
  , ""
  , ".dice-card:active {"
  , "  transform: translateY(0);"
  , "  box-shadow: none;"
  , "}"
  , ""
  , ".dice-num {"
  , "  position: absolute;"
  , "  top: 4px;"
  , "  left: 8px;"
  , "  font-size: 11px;"
  , "  color: var(--text-dim);"
  , "  font-weight: bold;"
  , "}"
  , ""
  , ".die-face {"
  , "  font-size: 48px;"
  , "  line-height: 1;"
  , "}"
  , ""
  , ".tier-label {"
  , "  font-size: 11px;"
  , "  font-weight: bold;"
  , "  text-transform: uppercase;"
  , "  letter-spacing: 0.5px;"
  , "  margin-top: 8px;"
  , "}"
  , ""
  , "/* Stats */"
  , ".stat-group {"
  , "  margin-bottom: 16px;"
  , "}"
  , ""
  , ".stat-label {"
  , "  font-size: 11px;"
  , "  color: var(--text-muted);"
  , "  text-transform: uppercase;"
  , "  letter-spacing: 0.5px;"
  , "  margin-bottom: 4px;"
  , "}"
  , ""
  , ".stat-bar {"
  , "  display: flex;"
  , "  gap: 2px;"
  , "}"
  , ""
  , ".stat-segment {"
  , "  width: 16px;"
  , "  height: 16px;"
  , "  border-radius: 2px;"
  , "}"
  , ""
  , ".stat-segment.filled {"
  , "  background: var(--accent);"
  , "}"
  , ""
  , ".stat-segment.empty {"
  , "  background: var(--bg-hover);"
  , "}"
  , ""
  , ".stat-value {"
  , "  font-size: 24px;"
  , "  font-weight: bold;"
  , "  color: var(--accent);"
  , "}"
  , ""
  , "/* Pips (for wanted level) */"
  , ".pip-container {"
  , "  display: flex;"
  , "  gap: 4px;"
  , "}"
  , ""
  , ".pip {"
  , "  width: 12px;"
  , "  height: 12px;"
  , "  border-radius: 50%;"
  , "}"
  , ""
  , ".pip.filled {"
  , "  background: var(--danger);"
  , "}"
  , ""
  , ".pip.empty {"
  , "  background: var(--bg-hover);"
  , "}"
  , ""
  , "/* Trauma tags */"
  , ".trauma-list {"
  , "  display: flex;"
  , "  flex-wrap: wrap;"
  , "  gap: 4px;"
  , "}"
  , ""
  , ".trauma-tag {"
  , "  padding: 2px 8px;"
  , "  background: var(--danger);"
  , "  border-radius: 4px;"
  , "  font-size: 11px;"
  , "  color: var(--text-primary);"
  , "}"
  , ""
  , "/* Dice pool display */"
  , ".dice-pool-display {"
  , "  display: flex;"
  , "  gap: 6px;"
  , "  flex-wrap: wrap;"
  , "}"
  , ""
  , ".die-display {"
  , "  font-size: 24px;"
  , "  cursor: default;"
  , "}"
  , ""
  , ".dice-empty {"
  , "  color: var(--text-muted);"
  , "  font-style: italic;"
  , "  font-size: 12px;"
  , "}"
  , ""
  , "/* Clocks */"
  , ".clock-widget {"
  , "  display: flex;"
  , "  align-items: center;"
  , "  gap: 8px;"
  , "  margin-bottom: 8px;"
  , "  position: relative;"
  , "}"
  , ""
  , ".clock-face {"
  , "  width: 32px;"
  , "  height: 32px;"
  , "}"
  , ""
  , ".clock-name {"
  , "  font-size: 13px;"
  , "}"
  , ""
  , ".clock-tooltip {"
  , "  position: absolute;"
  , "  left: 100%;"
  , "  top: 0;"
  , "  margin-left: 8px;"
  , "  padding: 8px;"
  , "  background: var(--bg-primary);"
  , "  border: 1px solid var(--bg-hover);"
  , "  border-radius: 4px;"
  , "  font-size: 12px;"
  , "  white-space: nowrap;"
  , "  z-index: 100;"
  , "}"
  , ""
  , "/* Loading */"
  , ".loading-overlay {"
  , "  position: absolute;"
  , "  inset: 0;"
  , "  background: rgba(0,0,0,0.7);"
  , "  display: flex;"
  , "  flex-direction: column;"
  , "  align-items: center;"
  , "  justify-content: center;"
  , "  z-index: 1000;"
  , "}"
  , ""
  , ".spinner {"
  , "  width: 40px;"
  , "  height: 40px;"
  , "  border: 3px solid var(--bg-hover);"
  , "  border-top-color: var(--accent);"
  , "  border-radius: 50%;"
  , "  animation: spin 1s linear infinite;"
  , "}"
  , ""
  , "@keyframes spin {"
  , "  to { transform: rotate(360deg); }"
  , "}"
  , ""
  , ".loading-text {"
  , "  margin-top: 16px;"
  , "  color: var(--text-muted);"
  , "}"
  , ""
  , "/* Debug */"
  , ".debug-section {"
  , "  margin-bottom: 16px;"
  , "}"
  , ""
  , ".debug-section-title {"
  , "  font-size: 10px;"
  , "  color: var(--text-dim);"
  , "  text-transform: uppercase;"
  , "  letter-spacing: 1px;"
  , "  margin-bottom: 4px;"
  , "}"
  , ""
  , ".debug-entry {"
  , "  font-size: 11px;"
  , "  padding: 4px 0;"
  , "  border-bottom: 1px solid var(--bg-hover);"
  , "}"
  , ""
  , ".debug-timestamp {"
  , "  color: var(--text-dim);"
  , "}"
  , ""
  , ".debug-level {"
  , "  font-weight: bold;"
  , "  margin: 0 4px;"
  , "}"
  , ""
  , ".debug-level.debug { color: var(--text-dim); }"
  , ".debug-level.info { color: var(--text-muted); }"
  , ".debug-level.warn { color: var(--warning); }"
  , ".debug-level.error { color: var(--danger); }"
  , ""
  , ".debug-time {"
  , "  color: var(--text-dim);"
  , "  font-family: var(--font-mono);"
  , "  font-size: 10px;"
  , "  margin-right: 6px;"
  , "}"
  , ""
  , ".debug-message {"
  , "  color: var(--text-primary);"
  , "}"
  , ""
  , ".debug-context {"
  , "  margin-top: 4px;"
  , "  margin-left: 16px;"
  , "}"
  , ""
  , ".debug-toggle {"
  , "  color: var(--accent);"
  , "  cursor: pointer;"
  , "  font-size: 10px;"
  , "  user-select: none;"
  , "}"
  , ""
  , ".debug-toggle:hover {"
  , "  text-decoration: underline;"
  , "}"
  , ""
  , ".debug-json {"
  , "  background: var(--bg-primary);"
  , "  border: 1px solid var(--bg-hover);"
  , "  border-radius: 4px;"
  , "  padding: 8px;"
  , "  margin-top: 4px;"
  , "  font-family: var(--font-mono);"
  , "  font-size: 10px;"
  , "  color: var(--text-muted);"
  , "  white-space: pre-wrap;"
  , "  word-break: break-all;"
  , "  max-height: 300px;"
  , "  overflow-y: auto;"
  , "}"
  , ""
  , "/* State Inspector */"
  , ".state-inspector {"
  , "  border-top: 1px solid var(--bg-hover);"
  , "  margin-top: 12px;"
  , "  padding-top: 12px;"
  , "}"
  , ""
  , ".state-inspector-title {"
  , "  font-size: 10px;"
  , "  color: var(--text-dim);"
  , "  text-transform: uppercase;"
  , "  letter-spacing: 1px;"
  , "  margin-bottom: 8px;"
  , "  cursor: pointer;"
  , "}"
  , ""
  , ".state-inspector-title:hover {"
  , "  color: var(--accent);"
  , "}"
  , ""
  , ".state-json {"
  , "  background: var(--bg-primary);"
  , "  border: 1px solid var(--bg-hover);"
  , "  border-radius: 4px;"
  , "  padding: 8px;"
  , "  font-family: var(--font-mono);"
  , "  font-size: 10px;"
  , "  color: var(--text-muted);"
  , "  white-space: pre-wrap;"
  , "  word-break: break-all;"
  , "  max-height: 400px;"
  , "  overflow-y: auto;"
  , "}"
  , ""
  , "/* DM State Inspector - Collapsible Tree */"
  , ".dm-state-inspector {"
  , "  border-top: 1px solid var(--bg-hover);"
  , "  margin-top: 12px;"
  , "  padding-top: 12px;"
  , "}"
  , ""
  , ".state-inspector-content {"
  , "  max-height: 500px;"
  , "  overflow-y: auto;"
  , "  padding-right: 4px;"
  , "}"
  , ""
  , "/* Collapsible sections using details/summary */"
  , ".state-section {"
  , "  margin-bottom: 4px;"
  , "  border: 1px solid var(--bg-hover);"
  , "  border-radius: 4px;"
  , "  background: var(--bg-primary);"
  , "}"
  , ""
  , ".state-section[open] {"
  , "  background: var(--bg-secondary);"
  , "}"
  , ""
  , ".state-section-title {"
  , "  font-size: 11px;"
  , "  font-weight: 600;"
  , "  color: var(--accent);"
  , "  padding: 6px 10px;"
  , "  cursor: pointer;"
  , "  list-style: none;"
  , "  user-select: none;"
  , "}"
  , ""
  , ".state-section-title::-webkit-details-marker {"
  , "  display: none;"
  , "}"
  , ""
  , ".state-section-title::before {"
  , "  content: '▶ ';"
  , "  font-size: 9px;"
  , "  color: var(--text-dim);"
  , "}"
  , ""
  , ".state-section[open] > .state-section-title::before {"
  , "  content: '▼ ';"
  , "}"
  , ""
  , ".state-section-title:hover {"
  , "  background: var(--bg-hover);"
  , "}"
  , ""
  , ".state-section-content {"
  , "  padding: 8px 10px;"
  , "  border-top: 1px solid var(--bg-hover);"
  , "}"
  , ""
  , "/* Nested items (factions, npcs, etc) */"
  , ".state-item {"
  , "  margin: 4px 0;"
  , "  background: var(--bg-primary);"
  , "  border-radius: 3px;"
  , "}"
  , ""
  , ".state-item-title {"
  , "  font-size: 10px;"
  , "  color: var(--text-muted);"
  , "  padding: 4px 8px;"
  , "  cursor: pointer;"
  , "  list-style: none;"
  , "}"
  , ""
  , ".state-item-title::-webkit-details-marker {"
  , "  display: none;"
  , "}"
  , ""
  , ".state-item-title::before {"
  , "  content: '› ';"
  , "  color: var(--text-dim);"
  , "}"
  , ""
  , ".state-item[open] > .state-item-title::before {"
  , "  content: '⌄ ';"
  , "}"
  , ""
  , ".state-item-title:hover {"
  , "  color: var(--text-primary);"
  , "}"
  , ""
  , ".state-item-content {"
  , "  padding: 4px 8px 8px 16px;"
  , "  font-size: 10px;"
  , "}"
  , ""
  , "/* Field labels and values */"
  , ".state-field {"
  , "  margin: 2px 0;"
  , "  font-size: 10px;"
  , "  line-height: 1.4;"
  , "}"
  , ""
  , ".state-field-label {"
  , "  color: var(--text-dim);"
  , "}"
  , ""
  , ".state-field-value {"
  , "  color: var(--text-muted);"
  , "}"
  , ""
  , "/* History Tab */"
  , ".history-tab {"
  , "  padding: 8px 0;"
  , "}"
  , ""
  , ".history-section {"
  , "  margin-bottom: 24px;"
  , "}"
  , ""
  , ".history-summary {"
  , "  background: var(--bg-secondary);"
  , "  padding: 12px;"
  , "  border-radius: 6px;"
  , "  margin-bottom: 12px;"
  , "}"
  , ""
  , ".history-summary p {"
  , "  margin-bottom: 8px;"
  , "}"
  , ""
  , ".key-beats {"
  , "  list-style: none;"
  , "  padding-left: 12px;"
  , "  border-left: 2px solid var(--accent-dim);"
  , "}"
  , ""
  , ".key-beats li {"
  , "  font-size: 13px;"
  , "  color: var(--text-muted);"
  , "  padding: 2px 0;"
  , "}"
  , ""
  , "/* Sidebar title */"
  , ".sidebar-title {"
  , "  font-size: 14px;"
  , "  font-weight: bold;"
  , "  letter-spacing: 2px;"
  , "  color: var(--accent);"
  , "  margin-bottom: 16px;"
  , "}"
  , ""
  , "/* Narrative pane */"
  , ".narrative-pane {"
  , "  min-height: 200px;"
  , "}"
  , ""
  , "/* Character Creation */"
  , ".character-creation {"
  , "  display: flex;"
  , "  flex-direction: column;"
  , "  align-items: center;"
  , "  justify-content: center;"
  , "  min-height: 100vh;"
  , "  padding: 40px;"
  , "  background: var(--bg-primary);"
  , "}"
  , ""
  , ".creation-title {"
  , "  font-size: 36px;"
  , "  font-weight: bold;"
  , "  letter-spacing: 4px;"
  , "  color: var(--accent);"
  , "  margin-bottom: 8px;"
  , "  text-align: center;"
  , "}"
  , ""
  , ".creation-subtitle {"
  , "  font-size: 18px;"
  , "  color: var(--text-muted);"
  , "  font-style: italic;"
  , "  margin-bottom: 40px;"
  , "  text-align: center;"
  , "}"
  , ""
  , ".creation-step {"
  , "  width: 100%;"
  , "  max-width: 600px;"
  , "}"
  , ""
  , ".creation-prompt {"
  , "  font-size: 20px;"
  , "  color: var(--text-primary);"
  , "  margin-bottom: 24px;"
  , "  text-align: center;"
  , "}"
  , ""
  , ".creation-content {"
  , "  width: 100%;"
  , "  max-width: 800px;"
  , "}"
  , ""
  , ".creation-input {"
  , "  width: 100%;"
  , "  padding: 16px;"
  , "  font-size: 18px;"
  , "  background: var(--bg-secondary);"
  , "  border: 2px solid var(--bg-hover);"
  , "  border-radius: 8px;"
  , "  color: var(--text-primary);"
  , "  font-family: inherit;"
  , "  margin-bottom: 16px;"
  , "  text-align: center;"
  , "}"
  , ""
  , ".creation-input:focus {"
  , "  outline: none;"
  , "  border-color: var(--accent);"
  , "}"
  , ""
  , ".creation-input::placeholder {"
  , "  color: var(--text-dim);"
  , "}"
  , ""
  , ".creation-btn {"
  , "  display: block;"
  , "  width: 100%;"
  , "  padding: 16px 32px;"
  , "  font-size: 16px;"
  , "  font-weight: bold;"
  , "  letter-spacing: 2px;"
  , "  text-transform: uppercase;"
  , "  background: var(--accent);"
  , "  border: none;"
  , "  border-radius: 8px;"
  , "  color: var(--bg-primary);"
  , "  cursor: pointer;"
  , "  transition: all 0.2s;"
  , "}"
  , ""
  , ".creation-btn:hover:not([disabled]) {"
  , "  opacity: 0.9;"
  , "  transform: translateY(-1px);"
  , "}"
  , ""
  , ".creation-btn:active:not([disabled]) {"
  , "  transform: translateY(1px);"
  , "}"
  , ""
  , ".creation-btn[disabled] {"
  , "  opacity: 0.5;"
  , "  cursor: not-allowed;"
  , "}"
  , ""
  , ".creation-btn:focus {"
  , "  outline: 2px solid var(--accent);"
  , "  outline-offset: 2px;"
  , "}"
  , ""
  , ".creation-choices {"
  , "  display: flex;"
  , "  flex-wrap: wrap;"
  , "  gap: 16px;"
  , "  justify-content: center;"
  , "  margin-bottom: 24px;"
  , "}"
  , ""
  , ".creation-card {"
  , "  padding: 20px 32px;"
  , "  background: var(--bg-secondary);"
  , "  border: 2px solid var(--bg-hover);"
  , "  border-radius: 8px;"
  , "  cursor: pointer;"
  , "  transition: all 0.2s;"
  , "  text-align: center;"
  , "  min-width: 140px;"
  , "}"
  , ""
  , ".creation-card:hover, .creation-card:focus {"
  , "  border-color: var(--accent);"
  , "  background: var(--bg-hover);"
  , "  outline: none;"
  , "  transform: translateY(-2px);"
  , "}"
  , ""
  , ".creation-card:active {"
  , "  transform: translateY(0);"
  , "}"
  , ""
  , ".creation-card-label {"
  , "  font-size: 18px;"
  , "  font-weight: bold;"
  , "  color: var(--accent);"
  , "  margin-bottom: 4px;"
  , "}"
  , ""
  , ".creation-card-desc {"
  , "  font-size: 13px;"
  , "  color: var(--text-muted);"
  , "}"
  , ""
  , ".creation-custom {"
  , "  display: flex;"
  , "  align-items: center;"
  , "  justify-content: center;"
  , "  gap: 12px;"
  , "  color: var(--text-muted);"
  , "}"
  , ""
  , ".creation-input-small {"
  , "  padding: 8px 12px;"
  , "  font-size: 14px;"
  , "  background: var(--bg-secondary);"
  , "  border: 1px solid var(--bg-hover);"
  , "  border-radius: 4px;"
  , "  color: var(--text-primary);"
  , "  font-family: inherit;"
  , "  width: 120px;"
  , "}"
  , ""
  , ".creation-input-small:focus {"
  , "  outline: none;"
  , "  border-color: var(--accent);"
  , "}"
  , ""
  , ".creation-btn-small {"
  , "  padding: 8px 16px;"
  , "  font-size: 12px;"
  , "  font-weight: bold;"
  , "  text-transform: uppercase;"
  , "  background: var(--bg-hover);"
  , "  border: 1px solid var(--accent-dim);"
  , "  border-radius: 4px;"
  , "  color: var(--accent);"
  , "  cursor: pointer;"
  , "}"
  , ""
  , ".creation-btn-small:hover {"
  , "  background: var(--accent-dim);"
  , "  color: var(--bg-primary);"
  , "}"
  , ""
  , ".archetype-grid {"
  , "  display: grid;"
  , "  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));"
  , "  gap: 12px;"
  , "  max-width: 100%;"
  , "}"
  , ""
  , ".archetype-card {"
  , "  min-width: unset;"
  , "  padding: 16px;"
  , "}"
  , ""
  , ".archetype-card .creation-card-desc {"
  , "  font-size: 12px;"
  , "  line-height: 1.4;"
  , "}"
  , ""
  , ".tarot-step {"
  , "  max-width: 900px;"
  , "}"
  , ""
  , ".tarot-spread {"
  , "  display: flex;"
  , "  gap: 24px;"
  , "  justify-content: center;"
  , "  flex-wrap: wrap;"
  , "  margin-bottom: 32px;"
  , "}"
  , ""
  , ".tarot-card {"
  , "  background: var(--bg-secondary);"
  , "  border: 2px solid var(--accent-dim);"
  , "  border-radius: 12px;"
  , "  padding: 24px;"
  , "  width: 220px;"
  , "  text-align: center;"
  , "}"
  , ""
  , ".tarot-position {"
  , "  font-size: 11px;"
  , "  font-weight: bold;"
  , "  letter-spacing: 2px;"
  , "  text-transform: uppercase;"
  , "  color: var(--text-dim);"
  , "  margin-bottom: 12px;"
  , "}"
  , ""
  , ".tarot-name {"
  , "  font-size: 18px;"
  , "  font-weight: bold;"
  , "  color: var(--accent);"
  , "  margin-bottom: 12px;"
  , "}"
  , ""
  , ".tarot-meaning {"
  , "  font-size: 13px;"
  , "  color: var(--text-muted);"
  , "  font-style: italic;"
  , "  line-height: 1.5;"
  , "}"
  , ""
  , ".tarot-continue {"
  , "  max-width: 300px;"
  , "  margin: 0 auto;"
  , "}"
  ]
  where
    colors = theme.themeColors

-- | Apply a theme to a window by injecting CSS and external resources
applyTheme :: Theme -> Window -> UI ()
applyTheme theme window = do
  let css = themeToCSS theme
  -- Font Awesome CDN
  fontAwesome <- mkElement "link"
    # set (attr "rel") "stylesheet"
    # set (attr "href") "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
    # set (attr "crossorigin") "anonymous"
  void $ getHead window #+
    [ element fontAwesome
    , mkElement "style" # set text (T.unpack css)
    ]

-- | Create a CSS variable reference
cssVar :: Text -> Text
cssVar name = "var(--" <> name <> ")"

-- | Create an rgba color string
rgba :: Int -> Int -> Int -> Double -> Text
rgba r g b a = "rgba(" <> T.pack (show r) <> "," <> T.pack (show g) <> ","
            <> T.pack (show b) <> "," <> T.pack (show a) <> ")"
