{-# LANGUAGE StrictData #-}
-- | Theme system for Tidepool GUI
--
-- Provides a flexible theming system with color palettes and CSS generation.
-- Domain-specific themes (like DM.GUI.Theme) define the actual colors.
module Tidepool.GUI.Theme
  ( -- * Theme type
    Theme(..)
  , ColorPalette(..)
    -- * CSS generation
  , themeToCSS
  , applyTheme
    -- * Utility
  , cssVar
  , rgba
  ) where

import Data.Text (Text)
import qualified Data.Text as T
import Graphics.UI.Threepenny.Core

-- | Color palette for a theme
data ColorPalette = ColorPalette
  { cpBackground    :: Text  -- ^ Primary background
  , cpBackgroundAlt :: Text  -- ^ Secondary/card background
  , cpBackgroundHover :: Text -- ^ Hover state background
  , cpAccent        :: Text  -- ^ Primary accent color
  , cpAccentDim     :: Text  -- ^ Dimmed accent
  , cpText          :: Text  -- ^ Primary text
  , cpTextMuted     :: Text  -- ^ Secondary/muted text
  , cpTextDim       :: Text  -- ^ Very muted text
  , cpSuccess       :: Text  -- ^ Success/positive
  , cpWarning       :: Text  -- ^ Warning/caution
  , cpDanger        :: Text  -- ^ Danger/negative
  , cpCritical      :: Text  -- ^ Critical/special
  }
  deriving (Show, Eq)

-- | A complete theme definition
data Theme = Theme
  { themeName    :: Text
  , themeColors  :: ColorPalette
  , themeFontMain :: Text
  , themeFontMono :: Text
  }
  deriving (Show, Eq)

-- | Generate CSS custom properties from a theme
themeToCSS :: Theme -> Text
themeToCSS theme = T.unlines
  [ ":root {"
  , "  --bg-primary: " <> colors.cpBackground <> ";"
  , "  --bg-secondary: " <> colors.cpBackgroundAlt <> ";"
  , "  --bg-hover: " <> colors.cpBackgroundHover <> ";"
  , "  --accent: " <> colors.cpAccent <> ";"
  , "  --accent-dim: " <> colors.cpAccentDim <> ";"
  , "  --text-primary: " <> colors.cpText <> ";"
  , "  --text-muted: " <> colors.cpTextMuted <> ";"
  , "  --text-dim: " <> colors.cpTextDim <> ";"
  , "  --success: " <> colors.cpSuccess <> ";"
  , "  --warning: " <> colors.cpWarning <> ";"
  , "  --danger: " <> colors.cpDanger <> ";"
  , "  --critical: " <> colors.cpCritical <> ";"
  , "  --font-main: " <> theme.themeFontMain <> ";"
  , "  --font-mono: " <> theme.themeFontMono <> ";"
  , "}"
  , ""
  , "* { box-sizing: border-box; margin: 0; padding: 0; }"
  , ""
  , "body {"
  , "  background: var(--bg-primary);"
  , "  color: var(--text-primary);"
  , "  font-family: var(--font-main);"
  , "  font-size: 16px;"
  , "  line-height: 1.5;"
  , "}"
  , ""
  , "/* Layout */"
  , ".tidepool-root {"
  , "  display: flex;"
  , "  height: 100vh;"
  , "  overflow: hidden;"
  , "}"
  , ""
  , ".sidebar {"
  , "  width: 200px;"
  , "  background: var(--bg-secondary);"
  , "  padding: 16px;"
  , "  overflow-y: auto;"
  , "  border-right: 1px solid var(--bg-hover);"
  , "}"
  , ""
  , ".main-panel {"
  , "  flex: 1;"
  , "  display: flex;"
  , "  flex-direction: column;"
  , "  overflow: hidden;"
  , "}"
  , ""
  , ".debug-panel {"
  , "  width: 280px;"
  , "  background: var(--bg-secondary);"
  , "  padding: 16px;"
  , "  overflow-y: auto;"
  , "  border-left: 1px solid var(--bg-hover);"
  , "  font-family: var(--font-mono);"
  , "  font-size: 12px;"
  , "}"
  , ""
  , ".debug-panel.collapsed {"
  , "  width: 40px;"
  , "  padding: 8px;"
  , "}"
  , ""
  , "/* Header */"
  , ".mood-header {"
  , "  padding: 16px;"
  , "  background: var(--bg-secondary);"
  , "  border-bottom: 1px solid var(--bg-hover);"
  , "}"
  , ""
  , ".mood-label {"
  , "  font-size: 12px;"
  , "  font-weight: bold;"
  , "  color: var(--accent);"
  , "  text-transform: uppercase;"
  , "  letter-spacing: 1px;"
  , "}"
  , ""
  , ".mood-description {"
  , "  color: var(--text-muted);"
  , "  font-size: 14px;"
  , "}"
  , ""
  , "/* Tabs */"
  , ".tab-bar {"
  , "  display: flex;"
  , "  background: var(--bg-secondary);"
  , "  border-bottom: 1px solid var(--bg-hover);"
  , "}"
  , ""
  , ".tab {"
  , "  padding: 8px 16px;"
  , "  cursor: pointer;"
  , "  border-bottom: 2px solid transparent;"
  , "  color: var(--text-muted);"
  , "}"
  , ""
  , ".tab:hover {"
  , "  color: var(--text-primary);"
  , "}"
  , ""
  , ".tab.active {"
  , "  color: var(--accent);"
  , "  border-bottom-color: var(--accent);"
  , "}"
  , ""
  , "/* Content */"
  , ".content-area {"
  , "  flex: 1;"
  , "  overflow-y: auto;"
  , "  padding: 16px;"
  , "}"
  , ""
  , "/* Narrative */"
  , ".narrative-entry {"
  , "  margin-bottom: 12px;"
  , "}"
  , ""
  , ".player-action {"
  , "  color: var(--accent);"
  , "  font-style: italic;"
  , "}"
  , ""
  , ".speech-bubble {"
  , "  background: var(--bg-secondary);"
  , "  border-radius: 8px;"
  , "  padding: 12px;"
  , "  margin: 8px 0;"
  , "  border-left: 3px solid var(--accent);"
  , "}"
  , ""
  , ".npc-name {"
  , "  font-weight: bold;"
  , "  color: var(--accent);"
  , "  font-size: 12px;"
  , "  text-transform: uppercase;"
  , "  letter-spacing: 0.5px;"
  , "  margin-bottom: 4px;"
  , "  display: block;"
  , "}"
  , ""
  , ".npc-speech {"
  , "  color: var(--text-primary);"
  , "  font-style: italic;"
  , "}"
  , ""
  , "/* Input */"
  , ".input-area {"
  , "  padding: 16px;"
  , "  background: var(--bg-secondary);"
  , "  border-top: 1px solid var(--bg-hover);"
  , "}"
  , ""
  , ".text-input-container {"
  , "  display: flex;"
  , "  gap: 8px;"
  , "}"
  , ""
  , ".text-input {"
  , "  flex: 1;"
  , "  padding: 12px;"
  , "  background: var(--bg-primary);"
  , "  border: 1px solid var(--bg-hover);"
  , "  border-radius: 4px;"
  , "  color: var(--text-primary);"
  , "  font-family: inherit;"
  , "  font-size: 14px;"
  , "}"
  , ""
  , ".text-input:focus {"
  , "  outline: none;"
  , "  border-color: var(--accent);"
  , "}"
  , ""
  , ".submit-btn {"
  , "  padding: 12px 24px;"
  , "  background: var(--accent);"
  , "  border: none;"
  , "  border-radius: 4px;"
  , "  color: var(--bg-primary);"
  , "  font-weight: bold;"
  , "  cursor: pointer;"
  , "}"
  , ""
  , ".submit-btn:hover {"
  , "  opacity: 0.9;"
  , "}"
  , ""
  , "/* Choice Cards */"
  , ".choice-container {"
  , "  display: flex;"
  , "  flex-wrap: wrap;"
  , "  gap: 12px;"
  , "}"
  , ""
  , ".choice-card {"
  , "  padding: 16px 24px;"
  , "  background: var(--bg-secondary);"
  , "  border: 2px solid var(--bg-hover);"
  , "  border-radius: 8px;"
  , "  cursor: pointer;"
  , "  transition: all 0.2s;"
  , "}"
  , ""
  , ".choice-card:hover {"
  , "  border-color: var(--accent);"
  , "  background: var(--bg-hover);"
  , "}"
  , ""
  , "/* Dice */"
  , ".dice-container {"
  , "  display: flex;"
  , "  gap: 16px;"
  , "  flex-wrap: wrap;"
  , "}"
  , ""
  , ".dice-card {"
  , "  display: flex;"
  , "  flex-direction: column;"
  , "  align-items: center;"
  , "  padding: 16px;"
  , "  background: var(--bg-secondary);"
  , "  border: 3px solid var(--bg-hover);"
  , "  border-radius: 8px;"
  , "  cursor: pointer;"
  , "  transition: all 0.2s;"
  , "  min-width: 80px;"
  , "}"
  , ""
  , ".dice-card:hover {"
  , "  transform: translateY(-2px);"
  , "}"
  , ""
  , ".die-face {"
  , "  font-size: 48px;"
  , "  line-height: 1;"
  , "}"
  , ""
  , ".tier-label {"
  , "  font-size: 11px;"
  , "  font-weight: bold;"
  , "  text-transform: uppercase;"
  , "  letter-spacing: 0.5px;"
  , "  margin-top: 8px;"
  , "}"
  , ""
  , "/* Stats */"
  , ".stat-group {"
  , "  margin-bottom: 16px;"
  , "}"
  , ""
  , ".stat-label {"
  , "  font-size: 11px;"
  , "  color: var(--text-muted);"
  , "  text-transform: uppercase;"
  , "  letter-spacing: 0.5px;"
  , "  margin-bottom: 4px;"
  , "}"
  , ""
  , ".stat-bar {"
  , "  display: flex;"
  , "  gap: 2px;"
  , "}"
  , ""
  , ".stat-segment {"
  , "  width: 16px;"
  , "  height: 16px;"
  , "  border-radius: 2px;"
  , "}"
  , ""
  , ".stat-segment.filled {"
  , "  background: var(--accent);"
  , "}"
  , ""
  , ".stat-segment.empty {"
  , "  background: var(--bg-hover);"
  , "}"
  , ""
  , ".stat-value {"
  , "  font-size: 24px;"
  , "  font-weight: bold;"
  , "  color: var(--accent);"
  , "}"
  , ""
  , "/* Pips (for wanted level) */"
  , ".pip-container {"
  , "  display: flex;"
  , "  gap: 4px;"
  , "}"
  , ""
  , ".pip {"
  , "  width: 12px;"
  , "  height: 12px;"
  , "  border-radius: 50%;"
  , "}"
  , ""
  , ".pip.filled {"
  , "  background: var(--danger);"
  , "}"
  , ""
  , ".pip.empty {"
  , "  background: var(--bg-hover);"
  , "}"
  , ""
  , "/* Trauma tags */"
  , ".trauma-list {"
  , "  display: flex;"
  , "  flex-wrap: wrap;"
  , "  gap: 4px;"
  , "}"
  , ""
  , ".trauma-tag {"
  , "  padding: 2px 8px;"
  , "  background: var(--danger);"
  , "  border-radius: 4px;"
  , "  font-size: 11px;"
  , "  color: var(--text-primary);"
  , "}"
  , ""
  , "/* Clocks */"
  , ".clock-widget {"
  , "  display: flex;"
  , "  align-items: center;"
  , "  gap: 8px;"
  , "  margin-bottom: 8px;"
  , "  position: relative;"
  , "}"
  , ""
  , ".clock-face {"
  , "  width: 32px;"
  , "  height: 32px;"
  , "}"
  , ""
  , ".clock-name {"
  , "  font-size: 13px;"
  , "}"
  , ""
  , ".clock-tooltip {"
  , "  position: absolute;"
  , "  left: 100%;"
  , "  top: 0;"
  , "  margin-left: 8px;"
  , "  padding: 8px;"
  , "  background: var(--bg-primary);"
  , "  border: 1px solid var(--bg-hover);"
  , "  border-radius: 4px;"
  , "  font-size: 12px;"
  , "  white-space: nowrap;"
  , "  z-index: 100;"
  , "}"
  , ""
  , "/* Loading */"
  , ".loading-overlay {"
  , "  position: absolute;"
  , "  inset: 0;"
  , "  background: rgba(0,0,0,0.7);"
  , "  display: flex;"
  , "  flex-direction: column;"
  , "  align-items: center;"
  , "  justify-content: center;"
  , "  z-index: 1000;"
  , "}"
  , ""
  , ".spinner {"
  , "  width: 40px;"
  , "  height: 40px;"
  , "  border: 3px solid var(--bg-hover);"
  , "  border-top-color: var(--accent);"
  , "  border-radius: 50%;"
  , "  animation: spin 1s linear infinite;"
  , "}"
  , ""
  , "@keyframes spin {"
  , "  to { transform: rotate(360deg); }"
  , "}"
  , ""
  , ".loading-text {"
  , "  margin-top: 16px;"
  , "  color: var(--text-muted);"
  , "}"
  , ""
  , "/* Debug */"
  , ".debug-section {"
  , "  margin-bottom: 16px;"
  , "}"
  , ""
  , ".debug-section-title {"
  , "  font-size: 10px;"
  , "  color: var(--text-dim);"
  , "  text-transform: uppercase;"
  , "  letter-spacing: 1px;"
  , "  margin-bottom: 4px;"
  , "}"
  , ""
  , ".debug-entry {"
  , "  font-size: 11px;"
  , "  padding: 4px 0;"
  , "  border-bottom: 1px solid var(--bg-hover);"
  , "}"
  , ""
  , ".debug-timestamp {"
  , "  color: var(--text-dim);"
  , "}"
  , ""
  , ".debug-level {"
  , "  font-weight: bold;"
  , "  margin: 0 4px;"
  , "}"
  , ""
  , ".debug-level.debug { color: var(--text-dim); }"
  , ".debug-level.info { color: var(--text-muted); }"
  , ".debug-level.warn { color: var(--warning); }"
  , ".debug-level.error { color: var(--danger); }"
  ]
  where
    colors = theme.themeColors

-- | Apply a theme to a window by injecting CSS
applyTheme :: Theme -> Window -> UI ()
applyTheme theme window = do
  let css = themeToCSS theme
  void $ getHead window #+ [mkElement "style" # set text (T.unpack css)]

-- | Create a CSS variable reference
cssVar :: Text -> Text
cssVar name = "var(--" <> name <> ")"

-- | Create an rgba color string
rgba :: Int -> Int -> Int -> Double -> Text
rgba r g b a = "rgba(" <> T.pack (show r) <> "," <> T.pack (show g) <> ","
            <> T.pack (show b) <> "," <> T.pack (show a) <> ")"
